### ISSUE TITLE
Ember Data 1.0.0-beta.14.1/15 does not reload belongsTo relationship after reloading the record.

### ISSUE THREAD

**Issue by stepanhav** [emberjs/data#2795] opened 2015-02-16 22:32 UTC
After upgrading to version 1.0.0-beta.14.1 I noticed that after the record is reloaded, the belongsTo relationships that was changed are not restored to original value.

Here is the jsbin that demonstrate that http://jsbin.com/cuxozoneji/1/edit?html,js,output

In previous version 1.0.0-beta.12 this worked as I would expected. 1.0.0-beta.15 works the same as 1.0.0-beta.14.1.

**Comment by bmac** [comment] 2015-02-16 23:16
Thanks for opening this @stepanhav. Its defiantly a bug. I suspect this is related to some of the relationship refactoring that went into `1.0.0-beta.14.1`. I'll dig into this some more to try and identify where the relationship should be reset.

**Comment by jcollins1991-zenefits** [comment] 2015-03-25 04:52
@igorT ping? running into this ;(

**Comment by nfc036** [comment] 2015-04-28 09:10
+1. Bug still exists in ember-data#1.0.0-beta.16.1 !?

**Comment by wecc** [comment] 2015-09-16 22:13
This seem to still be an issue in ED 1.13 / 2.0

**Comment by wecc** [comment] 2016-10-22 16:41
I'm going to close this since I'm unable to reproduce this issue using Ember `release` and Ember Data `canary`, see https://ember-twiddle.com/0fc88a0a411c2aae0f712fcbc26babd8

As you can see `model.rollbackAttributes()` is needed to rollback the actual attributes, but the relationship is always updated. This will improve with https://github.com/emberjs/rfcs/pull/21

**Closed by wecc** 2016-10-22 16:41 UTC
Labels: Bug
