### ISSUE TITLE
Metadata and setMetadataFor()

### ISSUE THREAD

**Issue by thaume** [emberjs/data#2938] opened 2015-03-25 18:00 UTC
Hello guys,

As discussed with @wecc on IRC, I had a problem today with metadata. Get ready it will be a bit verbose :)

I have 2 Ember routes: `/posts`and `/dashboard`. `/posts` shows all the posts a certain user has written and `/dashboard` shows website-wide analytics (all the posts on the platform, number of published posts, number of drafts...). The `/dashboard` route is only accessible by admins.

**On the `/posts` route** I want to show the user how many posts he wrote, how many are published and how many are drafts. I obviously don't want to get all records and call `.length` on them so I decided to use metadata to get those.

**On the `/dashboard` route** I want to show the admin what's going on on the platform (). Once again I don't want to retrieve all the posts from the API so I use metadata.

When I tried to transition from `/posts` to `/dashboard` the [setMetadataFor()](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1198) method broke. 

After debugging, I found that the `Ember.merge` was unable to merge the old metadata with the new one fetched. @Grapho told me that he had the same issue and that the problem comes from the fact that once the metadata is binded into the template, it becomes an Ember object and you can't merge a POJO (the metadata) with an Ember object.

The quickfix was to set `Ember.copy(metadata)` as a property in the `setupController` hook and use this property in the template.

Should this be fixed ? Should I attempt to write a failing test ? Or is it the way we want to interact with metadata ?

Thanks !

**Comment by grapho** [comment] 2015-03-25 18:32
I don't know if this qualifies as a bug that requires fixing. It does indeed seem like the intended behavior.

That said, is it reasonable to propose that an DS.Meta class be defined that can be easily bound to a template or controller, in a similar way that DS.Error (for example) can be? or are the use cases to narrow in scope?

**Comment by thaume** [comment] 2015-03-25 18:45
I don't think it is a bug either, more a 'could be handled better' case.

It questions the very basis of the 'meta' attribute. Should it only be manipulated in controllers and never binded in a template ?

**Comment by wecc** [comment] 2016-10-22 15:56
I'm closing this as we're tracking improved meta and link support in https://github.com/emberjs/rfcs/pull/160

**Closed by wecc** 2016-10-22 15:56 UTC
Labels: meta
