### ISSUE TITLE
Computed alias incompatible with relationships

### ISSUE THREAD

**Issue by Asherlc** [emberjs/data#3902] opened 2015-11-02 19:55 UTC
It appears that Ember.computed.alias doesn’t work for populating relationships:

http://emberjs.jsbin.com/kopive/4/edit?html,css,js,output (with alias, non-working), vs this: http://emberjs.jsbin.com/kopive/2/edit?html,css,js,output (sans alias, working)

**Comment by wecc** [comment] 2015-11-03 07:32
If your relationship is named `volume` instead of `book` you have to update your payload to reflect the name of the relationship:

```js
relationships: {
  volume: {
    data: { type: 'books', id: '1' }
  }
}
```

**Comment by Asherlc** [comment] 2015-11-03 17:09
Right, but wouldn't the expected behavior of `alias` be that it would allow for the relationship name change?

**Comment by wecc** [comment] 2015-11-03 19:14
Ah, I see what you mean. No, that's not possible :( Relationships are special CPs that ED has to know about beforehand so the alias wouldn't be discovered by ED as a relationship.

**Comment by pangratz** [comment] 2015-11-03 19:16
If you want to use a different name for a relationship in your payload, you can specify this within your serializer via the `attrs` hash:

``` js
App.AuthorSerializer = DS.JSONAPISerializer.extend({
  attrs: {
    book: { key: 'volume' }
  }
});
```

Note that there was a bug in `JSONAPISerializer` when using `attrs` with relationships. This has been fixed in #3847, available in `v2.2.0-beta.2.

**Comment by Asherlc** [comment] 2015-11-03 19:21
Ah, that's unfortunate :(. I was hoping it would behave like Rails' `alias_attr`, which allows exactly that, and is quite useful for me.

**Comment by bmac** [comment] 2015-12-23 15:34
Closing this issue as its working as intended. `Ember.computed.alias` sets up an alias when working in app code while the serializer is use to configure the payload sent and received by the server.

**Closed by bmac** 2015-12-23 15:34 UTC
