### ISSUE TITLE
createObject not giving data in response

### ISSUE THREAD

**Issue by ersuryapurohit** [emberjs/data#4211] opened 2016-03-05 11:22 UTC
When we use createRecord in store for any model, it does not give the data in response, in the _internalModel>_data & _attributes, bothe are empty. I found that in store.js, the funtion **buildInternalModel** accepts 3 parameters but when we call createRecord, it's calling **buildInternalModel** with 2 parameters, and not sending the data to the function. I've create a pull reqeust emberjs/data#4210 for the same. Thanks

**Comment by pangratz** [comment] 2016-03-05 11:38
Can you provide some code which demonstrates the issue you're having? What version of `ember-data` and wich adapter are you using? You can use [this ember-twiddle](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8?fileTreeShown=false&numColumns=2&openFiles=initializers.pretender.js%2Cmodels.person.js) as a starting point.

**Comment by bmac** [comment] 2016-03-05 20:01
@ersuryapurohit I'm not sure I understand what the issue is. When you create a record with some data you should be able to immediately access the data.

```js
var record = store.createRecord('author', { name: 'Mark Twain' });
record.get('name'); // 'Mark Twain'
```

I created a jsbin http://emberjs.jsbin.com/leviqebuco/1/edit?html,js,output to demonstrate.


The reason the 3rd argument to `buildInternalModel` is not used inside `createRecord` is because Ember Data tracks data that has been acknowledged as saved by the server different from data that the user has created or modified locally so it can roll back the changes if needed. The 3rd argument is for data from the server and when using `store.createRecord` the record initially only exists on the client.

**Comment by pangratz** [comment] 2016-05-27 17:28
I am closing this issue as it cannot be reproduced. @ersuryapurohit please reopen if you can show some code which demonstrates the issue you're having. Thanks!

**Closed by pangratz** 2016-05-27 17:28 UTC

**Comment by ersuryapurohit** [comment] 2016-05-30 06:55
Ok, can you please send me a twiddle link which can directly access data
from the server, and the server response is a normal json result, not a
record which ember supports ie. not normalised/serialised.

Thanks and Regards
*Er. Surya Purohit*
*+91-8607474746*
*Facebook <https://www.facebook.com/spsharma11> | Google+
<https://plus.google.com/+ErSuryaPurohit>*

**Comment by ersuryapurohit** [comment] 2016-05-30 07:11
The response I need to send from the server will contain the json only. Here in the example by @bmac the json is ember supported json ie.

`{
  "data": [
    {
      "id": 1,
      "type": "authors",
      "attributes": {
        "name": "Mark Twain"
      }
    },
    {
      "id": 2,
      "type": "authors",
      "attributes": {
        "name": "Ernest Hemingway"
      }
    },
    {
      "id": 3,
      "type": "authors",
      "attributes": {
        "name": "Stephen King"
      }
    }
  ]
}`

But I wanna send response like below

`[
  {
    "id": 1,
    "name": "Mark Twain"
  },
  {
    "id": 2,
    "name": "Ernest Hemingway"
  },
  {
    "id": 3,
    "name": "Stephen King"
  }
]`

Thanks in advance :)

**Comment by pangratz** [comment] 2016-05-30 09:25
You'd need to overwrite your serializer and customize so [`normalizeArrayResponse`](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_normalizeArrayResponse) works for the payload you return. See [this ember-twiddle](https://ember-twiddle.com/f38c58d81fe25a6dc8486016b0d4b9a9?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cserializers.application.js) for an example on how to do that:

```js
import Serializer from "ember-data/serializers/rest";

export default Serializer.extend({
  normalizeArrayResponse(store, type, array, id, requestType) {
    let key = this.payloadKeyFromModelName(type.modelName);
    let pluralized = key.pluralize();

    let payload = {
      [pluralized]: array
    };

    return this._super(store, type, payload, id, requestType);
  }
});
```

If you have further questions, please ask them in the `#-ember-data` room on the embercommunity slack channel.
