### ISSUE TITLE
Cannot add duplicate models to a hasMany relationship

### ISSUE THREAD

**Issue by jdreux** [emberjs/data#3502] opened 2015-07-06 19:16 UTC
Adding the same model more than once to a relationship property doesn't do anything: 

    #order/model.coffee
    Order = DS.Model.extend {
      line_items: DS.hasMany 'product', {async: true}
    }

    #product/route.coffee
    ...
    actions:
        # Not actually my code but illustrates the problem
        addToCart: (product1, product2)->
          order = @modelFor 'order'
          console.log order.get('line_items.length') # prints 0

          order.get('line_items').pushObject product1
          console.log order.get('line_items.length') # prints 1

          order.get('line_items').pushObject product2
          console.log order.get('line_items.length') # prints 2

          order.get('line_items').pushObject product1
          console.log order.get('line_items.length') # prints 2

          order.get('line_items').pushObject product2
          console.log order.get('line_items.length') # prints 2
          ...

Related SO question: http://stackoverflow.com/questions/31150242/ember-data-does-not-allow-duplicate-entries-in-hasmany-relationships/31218890#31218890

**Comment by wecc** [comment] 2015-07-07 22:15
Having multiple instances of the same record in a relationship is not supported by Ember Data.

I would suggest something like having a separate model for `line-item` with a relationship to a `product`. That way you can easily create multiple `line-item` records related to the same `product` and add them all to the `order`.

**Comment by wecc** [comment] 2015-07-07 22:16
I'm closing as this is not a bug.

**Closed by wecc** 2015-07-07 22:16 UTC

**Comment by jdreux** [comment] 2015-07-08 00:54
@wecc thank you for your answer. I understand the separate `line-item` model approach, where I can store the quantity for each `product` in the `order`. However, it has the inconvenience that I need to keep generating IDs for each of these `line-item` models, even if they are loaded as an embedded relationship! This is a lot of overhead for a simple use case that my backend developer might not understand the need for. 
How would you suggest I go around this issue?
