### ISSUE TITLE
get meta informations from json

### ISSUE THREAD

**Issue by mikadev** [emberjs/data#4422] opened 2016-06-05 19:18 UTC
as i explain here [/stackoverflow](http://stackoverflow.com/questions/37645345/ember-js-get-meta-informations-from-json?noredirect=1#comment62771472_37645345) i can't get the meta information from my json data (when i use the findAll method).

**Comment by lpaluszk** [comment] 2016-07-26 20:40
I am also seeing this issue while sending other requests. Only `store.query` seems to be parsing metadata. Is this by design? Is there a reason why single record can't return and therefore refresh the metadata.

What about creating a new record and saving it? Would it now be handy to have the POST request return metadata?

**Comment by mikadev** [comment] 2016-07-30 22:01
It's seem to be by design the raison behind i don't know personnaly i don't use this framework anymore.

**Comment by wecc** [comment] 2016-10-21 13:55
@lstyles confirm, `store.query()` does support `meta`, we're working on implementing more `meta` support.

Closing this as we're tracking `meta` support in #2905

**Closed by wecc** 2016-10-21 13:55 UTC
Labels: meta
