### ISSUE TITLE
Cannot read property 'map' of null TypeError: Cannot read property 'map' of null in JSONSerializer

### ISSUE THREAD

**Issue by dschmidt** [emberjs/data#3518] opened 2015-07-08 15:38 UTC
Hey,

with #canary ED triggers this error for me:

```
Cannot read property 'map' of null TypeError: Cannot read property 'map' of null
    at http://localhost:4200/assets/vendor.js:79181:38
    at http://localhost:4200/assets/vendor.js:83372:20
    at Map.forEach.cb (http://localhost:4200/assets/vendor.js:26283:11)
    at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:26066:11)
    at Map.forEach (http://localhost:4200/assets/vendor.js:26287:18)
    at Function.ember$data$lib$system$model$$default.reopenClass.eachRelationship (http://localhost:4200/assets/vendor.js:83371:83)
    at ember$data$lib$system$serializer$$default.extend.extractRelationships (http://localhost:4200/assets/vendor.js:79172:20)
    at ember$data$lib$system$serializer$$default.extend.normalize (http://localhost:4200/assets/vendor.js:79084:33)
    at superFunction [as _super] (http://localhost:4200/assets/vendor.js:26497:20)
    at ember$data$lib$serializers$json$serializer$$default.extend.normalize (http://localhost:4200/assets/vendor.js:80613:21)
```

which 1.13.4 didn't do. 
Quoting @bmac from #ember-data:

```
bmac [5:28 PM] 
Its likely because of relationshipHash is undefined here https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-serializer.js#L610
1.13.4 doesn't call map directly on the object because of IE8 support.
```

BR,
Domme

**Comment by marcemira** [comment] 2015-07-09 13:46
I'm having the same issue when saving a record. Is any way to workaround this?

**Comment by wecc** [comment] 2015-07-09 21:12
What does your payload causing this look like?

**Comment by bmac** [comment] 2015-07-09 21:17
@wecc I suspect the payload is missing a value for a hasMany relationship. 

The value of `relationshipHash` is undefined here: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-serializer.js#L606

We should make Ember Data be smarter about handling these types of errors.

**Comment by wecc** [comment] 2015-07-09 21:19
@bmac yes, agree. I'm just curious as we're checking `hasOwnProperty` and why you'd want to pass `relationship: undefined` in your payload. If it's supported there should be a test for that case.

**Comment by dschmidt** [comment] 2015-07-10 00:17
I can try to track this down ... perfect occupational therapy for a sleepless night.

**Comment by dschmidt** [comment] 2015-07-10 00:52
Of course I cannot reproduce anymore ...  although I could before: 100% of the time.

**Comment by marcemira** [comment] 2015-07-10 00:59
@dschmidt what did change?

**Comment by dschmidt** [comment] 2015-07-10 01:03
If I knew... it was a charts thingie payload - which apparently changed in a way that's not triggering the error anymore. Still browsing around my page to trigger it again

**Comment by marcemira** [comment] 2015-07-10 01:14
@dschmidt This is the [payload](https://gist.github.com/marcemira/fcf4c3b4007757f43299) when I save the model (PUT). And these are the models: [mics](https://gist.github.com/marcemira/f2e321834e5977331d45) and [extra](https://gist.github.com/marcemira/c0552eb497d9387e6255).

I am also using custom serializers:


```javascript
// app/serializers/mics/extra
import DS from 'ember-data';

export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin,{

  isNewSerializerAPI: true,

  attrs: {
    price: { embedded: 'always' },
    delay: { embedded: 'always' }
  }

});
 
```

**Comment by dschmidt** [comment] 2015-07-10 01:19
Aaah, found something: 
I have a `Song` model, that has a relationship defined like this: `nowPlayingUsers: DS.hasMany('user', {async:true}),`, now when the payload contain `nowPlayingUsers: null`, the above error is triggered - unlike before. Although my payload is certainly bad - a better error would be very good. Even if it's only an assertion with a clear description of what's wrong - maybe containing the url that returned the bad response - in bigger projects it tends to be very hard to track the request down that actually triggered an ember-data error.

**Comment by marcemira** [comment] 2015-07-10 01:25
@dschmidt :disappointed: that's not my case... my payload is not empty. 

I think I might know what's the problem about. When I use async:true, the relationship is Array type, but when dealing with embedded, it is an Ember.Object with properties 1 2 3 4 which has normal objects that represents the payload.. Ember.Object doesn't have a map method, so it naturally fails.

Any thoughts? Thanks for helping me out

**Comment by wecc** [comment] 2015-07-10 12:24
@marcemira The `EmbeddedRecordsMixin` should take care of that I think.

I would love to dig deeper into this. Would it be possible to get a failing JSBin I can look at?

**Comment by chrismllr** [comment] 2015-08-05 22:30
@marcemira @wecc +1 . I am getting the same exact issue. 

`Error while processing route: search Ember.A(...).map is not a function TypeError: Ember.A(...).map is not a function`

Ember v1.13.5 Ember Data v1.13.5

**Comment by chrismllr** [comment] 2015-08-11 15:15
@marcemira Have you had any progress with this? I've also got a serializer using the `EmbeddedRecordsMixin`, using async relationships for the embedded records.. and getting the `Ember.A(...).map is not a function` error.

**Comment by chrismllr** [comment] 2015-08-21 20:48
@wecc @marcemira Any ideas on this? Still happening for me, Ember v1.13.7 Ember Data v1.13.7

**Comment by chrismllr** [comment] 2015-08-25 18:41
Got it. Checked all model declarations vs payloads, and one relationship was coming back as an object, but was specified as a `hasMany` on my model, therefor throwing that it could not be mapped.

All working well with the `isNewSerializerAPI` flag set to `true`

**Comment by wecc** [comment] 2015-08-26 22:17
@dschmidt, @marcemira what's the current status of this issue?

**Comment by dschmidt** [comment] 2015-08-27 07:24
Still on vacation. Can check tomorrow or so.

**Comment by marcemira** [comment] 2015-08-31 10:00
@wecc @chrismllr sorry, i'm on ED 2.0.0, can't reproduce this anymore :/

**Comment by cstengel88** [comment] 2015-10-02 15:03
this also occurs if a defined model has a hasMany Relationship which the payload does not provide which was ignored in old ED but causes problems now, we´re often leaving out nodes which are not needed for the current template to keep the payload compact which resolves in an error now, is there any way to define the node hasMany searches for can be null/undefined without an error ?

isNewSerializerApi flag does not help btw

**Comment by NeilAllen** [comment] 2015-11-18 15:39
Is there an update/resolution on this 1; getting the same issue where the relationship value is null.

**Comment by wecc** [comment] 2016-10-22 13:31
Is this still happening in ED 2.x? If so, would you be able to create a reproduction using JSBin or Ember Twiddle so that we can track this down?

**Comment by dschmidt** [comment] 2016-11-24 21:47
@wecc I can't say anything about the current state, I havent done any Ember work lately... If noone else is facing it, I'm certainly cool with closing this issue!

**Comment by sly7-7** [comment] 2016-11-25 08:43
@dschmidt Thanks for answer, I'm closing

**Closed by sly7-7** 2016-11-25 08:43 UTC
Labels: Needs Bug Verification
