### ISSUE TITLE
How to filter models based on async relationships?

### ISSUE THREAD

**Issue by flyswatter** [emberjs/data#2754] opened 2015-02-04 17:25 UTC
After having a lot of problems trying to get Ember to be happy with synchronous relationships, I've started to believe that async should be the default type of relationship for Ember models.

Only problem, is that some basic operations seem pretty strange when using async relationships!

Most recently I've hit a wall while trying to filter an array of objects based on properties of an object they are related to with an `async` relationship.  Even though those models are loaded already, the abstraction of promises + the observer chain seem to prevent me from finding an elegant solution.

I have [three different approaches](https://gist.github.com/flyswatter/386894cc297faae39c61) I've tried, but they all have various pitfalls and caveats.  I'm just looking for something that works.  Does anyone have a solution to this?

**Comment by thaume** [comment] 2015-02-04 17:50
That's good, because ED is going full async soon :)

I like to do what you're talking about this way:

```javascript
femaleAuthoredLongPosts: Ember.computed.filter('posts', function (post) {
    return post.get('author').then(function(user){
        return !user.get('male') && post.get('body.length') > 10000;
    });
}).property('post.[]'),
```

Is that answering your problem? Is that even working in your case?

**Comment by flyswatter** [comment] 2015-02-04 17:59
Hey @thaume, thanks for your reply.  I definitely think going full async is the right decision.  We just need solid reliable approaches to this kind of basic thing.

Your solution looks a lot like [my second solution](https://gist.github.com/flyswatter/386894cc297faae39c61#file-gistfile1-js-L20-L31), and the problem is you're returning a Promise to a `filter` function, which does not seem to recognize the promise, but instead recognizes it as a truthy object, thus not filtering anything out.

**Comment by flyswatter** [comment] 2015-02-04 18:05
I would point out that since this was something we both tried, some kind of promise-accepting filter would be a fantastic addition to Ember.

**Comment by flyswatter** [comment] 2015-02-04 18:30
I thought I had a real clever solution here, but now the view won't even load with this:

```javascript
femaleAuthoredLongPosts: function () {
  var posts = this.get('model');
  var promises = posts.map(function(post){
     return Em.RSVP.resolve(post);
   });

  var filterFn = function (post) {
    return post.get('user').then(function(user){
      return !user.get('male') && post.get('body.length') > 10000;
    });
  };
  
  return Em.RSVP.filter( promises, filterFn );
}.property('posts.[]')
```

**Comment by stefanpenner** [comment] 2015-02-04 18:31
unfortunately the above example is also somewhat incorrect, this makes me sad, as we are close but these ideas still need much fleshing out.

unfortunately the later is likely the verbose but correct way
```js
femaleAuthoredLongPosts: Ember.computed('posts.[]', function (post) {
    return DS.PromiseArray.create({
      promise: post.get('authors').then(function(user) {
        return !user.get('male') && post.get('body.length') > 10000;
      })
    });
}),
```

**Comment by thaume** [comment] 2015-02-04 18:34
Don't be sad @stefanpenner, ED is so awesome right now. Should this problem be fixed on Ember or in ED?

**Comment by flyswatter** [comment] 2015-02-04 18:45
I hadn't seen the `.{bracker,observer}` syntax before, but that's pretty cool.

I'm a little baffled by other aspects of this example, though, I'd appreciate if you could help me understand:

 - How is a normal `Ember.computed` able to know to pass in items within the array instead of the whole array.
 - How returning a whole `PromiseArray` per item, with a true/false resolution turns into a filter somehow.

I do think the idea of a `PromiseArray` with various promise-operating array functions is the way to go in the future for Ember.  If only some company would just hire you to work on Ember all day :hand:

**Comment by flyswatter** [comment] 2015-02-04 18:53
Oh, also, that `DS.PromiseArray` solution does the same thing as my previous "clever approach":  The route doesn't even load anymore :(

**Comment by stefanpenner** [comment] 2015-02-04 19:14
> Don't be sad @stefanpenner, ED is so awesome right now. Should this problem be fixed on Ember or in ED?

Ember. It's not __really__ a problem, it is just terrible :P. Although improvements are planned its a time thing. :(

**Comment by flyswatter** [comment] 2015-02-04 20:00
Well, I found a way to make it work.  It's one of the ugliest, most anti-pattern chunks of Ember code I've ever written (lie), but unlike all the other proposals so far, this works:

```javascript
// This is not a computed property, it's an array we update with an observer function:
femaleAuthoredLongPosts: [],

// Our observer function:
updateFemaleAuthoredLongPosts: function () {
  var self = this;
  var posts = this.get('model');
  this.set('femaleAuthoredLongPosts', []);

  posts.forEach(function(post){
    post.get('author').then(function(user){
      if( !user.get('male') && post.get('body.length') > 10000 ){
        self.get('femaleAuthoredLongPosts').pushObject(post);
      }
    });
  });
}.observes('model.@each.author.male', 'model.@each.body.length'),

// Lastly, for some reason we also need to trigger that method in the init function.
// I can't find another way to make it fire to start.
init: function (){
  this._super();
  this.updateFemaleAuthoredLongPosts();
}
```

**Comment by flyswatter** [comment] 2015-02-04 20:00
I'm going to leave this issue open as "There should be a sane way to do this."

**Comment by igorT** [comment] 2015-02-06 20:01
Have you tried https://github.com/emberjs/data/pull/2491 ?

**Comment by flyswatter** [comment] 2015-02-07 17:15
I haven't tried that, @IgorT.  I'm actually a bit unclear what I'm looking at.  I see that the `store` would then have a promise-accepting `filter` function, but then you can also set a `filterFunction` on any `recordArray`?  Is that right?

It looks pretty hopeful, I don't have time to look at those failing tests, but it might be one solid solution to this issue.

(I still really like Stefan's idea for adding this to all PromiseArrays, though!)

**Comment by christophermlne** [comment] 2015-02-09 02:04
I'm also tearing my hair out trying to do this. The solutions in this thread are too insane to even contemplate. No normal developer could write something like that. This has to be easier.

**Comment by flyswatter** [comment] 2015-02-09 02:09
My last solution with a few modifications is working for me for the moment, but I still believe it's very anti-Ember code, and needs a better solution.

**Comment by lolmaus** [comment] 2015-02-15 12:55
I was curious to try it, and @stefanpenner's solution worked right away:

**Comment by lolmaus** [comment] 2015-02-15 12:56
I was curious to try it, and @stefanpenner's solution worked right away:

http://emberjs.jsbin.com/moguci/1/edit?html,js,output

It's just Stefan has forgot the `.filter` function in his snippet. ^_^'

**Comment by Leooo** [comment] 2015-07-31 16:53
thanks @lolmaus

**Comment by lan0** [comment] 2015-11-05 09:46
Are there any updates on this? The code above doesn't seem to work anymore in 2.1.

**Comment by lolmaus** [comment] 2015-11-05 10:58
@lan0 Why not? What's the problem specifically?

Please reproduce the problem on http://ember-twiddle.com/ .

**Comment by nightire** [comment] 2015-11-06 04:09
@lolmaus May I ask where to put `$.mockjax` code in ember-twiddle?

**Comment by lolmaus** [comment] 2015-11-06 09:22
@nightire Uhm, you can't, I guess. Use https://emberjs.jsbin.com then.

**Comment by lan0** [comment] 2015-11-06 09:39
@nightire https://github.com/ember-cli/ember-twiddle/issues/62#issuecomment-135774816 has an example for using mockjax in a twiddle: https://ember-twiddle.com/e17b37f4aa8e458546d5

**Comment by nightire** [comment] 2015-11-06 10:49
@lan0 Actually I've tried the same thing at first: https://ember-twiddle.com/b52ef7dfecbd6a08c86d

But unfortunately it won't work because ember-twiddle won't allow pre-flight request??? I'm really confused...

**Comment by BrianTMaurer** [comment] 2016-01-06 04:45
I also have this issue. +1

**Comment by wecc** [comment] 2016-10-22 16:54
Is this still an issue since references were introduced?

**Comment by stefanpenner** [comment] 2017-04-18 03:15
> Is this still an issue since references were introduced?

I don't believe so.

**Closed by stefanpenner** 2017-04-18 03:15 UTC
Labels: Needs Bug Verification

**Comment by miguelcobain** [comment] 2018-01-16 17:12
@wecc @stefanpenner can any of you elaborate on how references solve this problem, please?
