### ISSUE TITLE
computed property prevents attributes to be set

### ISSUE THREAD

**Issue by luxferresum** [emberjs/data#5474] opened 2018-05-21 13:40 UTC
This is a *very* strange behaviour, and I tried to narrow it down a bit. A [git repo with a minimal example to demonstrate the problem is here](https://github.com/luxferresum/ember-data-swallows-attributes).

Basically we need a model `foo` that looks like this:

```
export default DS.Model.extend({
  quantity: DS.attr('number'),
  bar: DS.belongsTo('bar'),
});
```

and a model `bar` like this:

```
export default DS.Model.extend({
  foos: DS.hasMany('foo'),

  totalFoos: computed('foos.@each.quantity', {
    get() {
      return this.foos
        .map(f => f.get('quantity'))
        .reduce((a,b) => a + b, 0);
    }
  }),
});
```

Next `this.model` is a `bar` model with no `foo`s. Then this code creates a very strange state:

```
this.store.createRecord('foo', { bar: this.model, quantity: 3 });
this.model.foos.toArray().forEach(f => f.set('quantity', 5));
```

When the `totalFoos` CP is *not* displayed and not computed everything works as expected. However when I insert `{{model.totalFoos}}` into my template I have the following behaviour:

When using an `{{#each model.foos as |foo|}}{{foo.quantity}}{{/each}}` loop we get a `5` as expected. However in the `ember-inspector` we see the `quantity` as `3`. Also when we `.save()` the `foo` instance we sent a `3` to the server.

**Comment by runspired** [comment] 2018-06-03 09:10
Thanks for the bug report!  I suspect you are correct that the immediate second set is failing to set the dirty state of the model correctly. I'll dig in :)

**Comment by runspired** [comment] 2018-07-21 02:08
I think this may be related to array observers on the async proxy

**Comment by pkchsd** [comment] 2018-08-16 15:25
i was able to to synch, i will try nog more
Duplicate of #

**Comment by arschmitz** [comment] 2018-10-17 23:43
@runspired ran into this also using ember data 3.1.1 was fixed in 3.1.2 though so this can probably be closed

**Comment by jhitchins88** [comment] 2018-10-17 23:47
@arshmitz and I found that what triggered the issue was using `computed('foo.@each*.bar*',...`, which caused some sort of broken binding when dealing with new records.

**Comment by runspired** [comment] 2021-05-22 09:23
closing because it's very likely this was an issue with a specific version of Ember that was later fixed and because the code pattern in use is no longer the recommended way to compute such a value in Octane.

**Closed by runspired** 2021-05-22 09:23 UTC
Labels: Needs Bug Verification
