### ISSUE TITLE
[Meta Issue] remove instance state from ModelFactories

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#2528] opened 2014-11-27 20:31 UTC
specifically `Model.store` and anything else that pollutes.

this will let us fix:

- [ ] typeKey
- [ ] aspects of polymorphic
- [ ] likely more.

**Comment by igorT** [comment] 2015-05-25 01:55
This is a dupe of a similar tracking bug, and is currently being handled by https://github.com/emberjs/data/pull/3074

**Closed by igorT** 2015-05-25 01:55 UTC
Labels: blocking, Bug
