### ISSUE TITLE
hasMany bulk update or insert

### ISSUE THREAD

**Issue by hnf1991** [emberjs/data#4371] opened 2016-05-05 18:26 UTC
I have my parent model like this

```
export default Base.extend(Copyable, {
   //model properties
   'name': DS.attr('number'),
   'class': DS.attr('number'),
   
   'users': DS.hasMany('user', { async: true })
});
```

and my **user** model is like this

```
export default Base.extend(Copyable, {
   'Name': DS.attr(),
   'parentModel': DS.belongsTo('model')
});
```

Now what I want is to push users in my parent model an make a bulk insert/update request to server
what I am doing is:

```
for(var i=0;i<5;i++){
   let pcu = route.store.createRecord('user', {
       Name: '',
       parentModel: parentModel,
   });
   parentModel.get('users').pushObject(pcu);
}
parentModel.save();
```

After calling save I can't see ember sending my users relationships ([http://jsonapi.org/format/#crud-updating-to-many-relationships]).

Currently I am using **JSONAPISerializer**

**Comment by wecc** [comment] 2016-10-21 15:07
Serializing `hasMany` relationships are disabled in Ember Data by default since they could include **a lot** of data – the recommendation is to save the children instead but in a case like yours that would result in a lot of requests. You can use the [shouldSerializeHasMany](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_shouldSerializeHasMany) hook to have Ember Data include the IDs of the associated users.

**Comment by wecc** [comment] 2016-10-29 20:48
I'm closing this since it's the intended behavior of Ember Data and not a bug. Feel free to re-open if `shouldSerializeHasMany` is not working.

**Closed by wecc** 2016-10-29 20:48 UTC
Labels: coalescing
