### ISSUE TITLE
unloadRecord of child record causes hasMany relationship to be invalid using ember-data@2.13

### ISSUE THREAD

**Issue by sudowork** [emberjs/data#4986] opened 2017-05-16 00:01 UTC
## Example repo and integration test to reproduce the issue
- [ember-data 2.13.1 (broken)](https://github.com/sudowork/unloadrecord-ember-data-bug/tree/ember-data213)
- [ember-data 2.12.2 (working)](https://github.com/sudowork/unloadrecord-ember-data-bug/tree/ember-data212)

_Update_: I wrote a test case to test this behavior https://github.com/sudowork/data/commit/89a34ba7b59535bc679e8b6f7ea7108cc13fbf45. I bisected the issue to have started with 6d96eda226f15738b23032bc25c009e081070359 (from #4593).

_Update 2_: Converted the repo I had to an ember-twiddle now that I can load 2.13: [https://ember-twiddle.com/df7fa30d2eb3d32efe16185f4f376128?openFiles=controllers.todo-list.js%2C](ember-twiddle)

## Steps to reproduce:

```javascript
// models/todo-list.js
import DS from 'ember-data';
import { hasMany } from 'ember-data/relationships';

export default DS.Model.extend({
  todos: hasMany('todo', { async: false }),
});
```

1. Assume you have a model `todo-list` which `hasMany` `todo` items as `todos` already loaded in the store and is currently in scope.
1. Call [`todos.removeObject(todo)`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR29) to remove the item from the relationship
1. Call [`this.store.unloadRecord(todo)`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR31) to clean up the record from the store
1. Explicitly try accessing [`get(this, 'model.todos')`](https://github.com/sudowork/unloadrecord-ember-data-bug/commit/03f7d0e7393927ce725469937bf35482b78ea550#diff-78fe8209f0a401e3c9acab9bacd673ccR34) again to load the `todo` records. (Expected result: `[]`, Actual result: Assertion error thrown).

The assertion error thrown is due to [this assertion](https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-private/system/relationships/state/has-many.js#L244) that checks that `manyArray.isEvery('isEmpty', false)` on `[null]`.

### 2.13.1 (broken)

![unloadrecord213](https://cloud.githubusercontent.com/assets/1113327/26084294/f8503a48-398f-11e7-9228-cda3c4ec003c.gif)

### 2.12.2 (working)

![unloadrecord212](https://cloud.githubusercontent.com/assets/1113327/26084288/f1a92b5a-398f-11e7-900f-dfc5edd89408.gif)

Note: On 2.12, it does not even go through `getRecords()` when retrieving the records again.

**Comment by sudowork** [comment] 2017-05-16 00:02
Just briefly skimming the change log, this commit https://github.com/emberjs/data/pull/4593 looks suspicious. However, I don't currently know enough about the ember-data internals/haven't dug into it enough to have an educated guess.

**Comment by sudowork** [comment] 2017-05-16 05:16
I've written a test case for this here. Please let me know if my understanding of how this should behave is incorrect. https://github.com/sudowork/data/commit/89a34ba7b59535bc679e8b6f7ea7108cc13fbf45

And I've bisected to verify that ba5874bb does pass the test; however, 2f18405 (from #4593) fails the test.

**Comment by sudowork** [comment] 2017-05-16 06:25
Calling `clearRelationships()` instead of `destroyRelationships()` [here](https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-private/system/model/internal-model.js#L372) appears to do have the correct behavior. However, it does trigger extraneous `arrayWillChange` and `arrayDidChange` events on the `manyArray` for the relationship.

**Comment by sudowork** [comment] 2017-05-16 06:25
cc @hjdivad

**Comment by sly7-7** [comment] 2017-05-16 08:08
I just experienced this as well. I think that unloading records of a hasMany leaves the underlying many array with internalModels with null records. I'm not sure this is intended, and don't know what we want for the relationship (does the many array should be cleared, or still contain 'empty' internalModels ?)

**Comment by Kilowhisky** [comment] 2017-05-17 15:32
I had to rollback because i experienced this. 

When i unload records it doesn't seem to fully clear reflexive relationships. Any time i tried to access a hasMany relationship in another model where one of the hasMany has been unloaded it explodes saying that the record is undefined. The 'unloaded' record still appears in the hasMany canonicalState but it has the flag `isEmpty: true` and `isDestroyed: true`.   Reloading the record back into the store doesn't appear to fix this either. 

I tried to make twiddle for this but twiddle hasn't been updated to 2.13 yet.

**Comment by sudowork** [comment] 2017-05-23 21:00
I'm happy to attempt a fix for this as long as there's some agreement over what the correct behavior should be.

**Comment by sudowork** [comment] 2017-05-24 01:17
I'm happy to attempt a fix for this as long as there's some agreement over what the correct behavior should be @sly7-7 @stefanpenner @hjdivad

**Comment by IBue** [comment] 2017-05-29 15:16
Here is a little twiddle demonstrating the error in 2.13 when unloading an inverse hasMany-relationship:
https://ember-twiddle.com/243ca2dab9b4615dd67115fbb1d83881

ember-data version can be switched in twiddle.json

**Comment by sudowork** [comment] 2017-05-31 23:00
Now that ember-twiddle supports ember-data 2.13, here's the repo I had created as a Twiddle: https://ember-twiddle.com/df7fa30d2eb3d32efe16185f4f376128?openFiles=controllers.todo-list.js%2C

Some interesting things:
- If I use `createRecord` to create the child, then there is no issue with unloading the record. It seems to only be when the record was created when pushing the relationship into the store.

**Comment by workmanw** [comment] 2017-06-01 16:51
This is also a show stopper for us. I can appreciate the fact that it's nice to synchronize this unloadRecord action with the runloop to prevent redundancy. Unfortunately this broke in several things in our application. Most cases were as @sudowork stated, using `computed.map` or some similar helper to iterate over a list it never expected to be null. 

Also, FWIW some of these were also using `store.filter` arrays. Which I know is deprecated, but still usable.

**Comment by sly7-7** [comment] 2017-06-19 09:51
Maybe #5011 will fix this.
cc/ @runspired

**Comment by workmanw** [comment] 2017-06-20 00:52
Wondering if #5011 fixes this? I'll try in my app tomorrow.

**Comment by sly7-7** [comment] 2017-06-20 07:15
@workmanw I thought the same thing, but I tried in my app, and for relationships, the internalModel has still their records set to null.

**Comment by sudowork** [comment] 2017-06-20 07:47
@workmanw @sly7-7 I updated my test branch (#4987) to the latest master and the issue persists. I didn't attempt it yet in a real app.

**Comment by workmanw** [comment] 2017-06-20 14:45
Yeap, I can confirm that unfortunately this issue still exists in our application. We're stuck on ember-data-2.12.x for the time being.

**Comment by workmanw** [comment] 2017-06-21 00:24
So I've spent almost all day trying to refamiliarize myself with ember data internals which seem to be a moving target. Looking back at when this last worked, ember-data-2.12.x, did the following:

```javascript
clearRelationships() {
  this.eachRelationship((name, relationship) => {
    if (this._relationships.has(name)) {
      let rel = this._relationships.get(name);
      rel.clear();
      rel.destroy();
    }
  });
  Object.keys(this._implicitRelationships).forEach((key) => {
    this._implicitRelationships[key].clear();
    this._implicitRelationships[key].destroy();
  });
}
```
See: [v2.12.2/internal-model.js](https://github.com/emberjs/data/blob/v2.12.2/addon/-private/system/model/internal-model.js#L701-L708)

The key here is that it called `clear` on the relationship itself. Even when the inverseKey was undefined. Here's a stack from my app:
<img width="767" alt="screen shot 2017-06-20 at 5 13 14 pm" src="https://user-images.githubusercontent.com/825487/27356425-62007076-55dc-11e7-91a5-69869ea1018e.png">


-------------

However, with the update from #4593, it no longer takes this action when the inverseKey is undefined. The reason is that there is now a `destroyRelationships` which does not clear relationships. If `dematerializeRecord` called `clearRelationships` instead of `destroyRelationships`, this would resolve the issue. 

I can confirm that making this change fixes the issue with the test repo provided by @sudowork . However it still leaves an issue with my application which is using filtering. :(

**Comment by jamesarosen** [comment] 2017-06-28 20:17
I _think_ just the following will also cause this:
```js
// model:foo
save() {
  return this._super()
  .then(() => {
    if (!this.get('canHaveBars')) {
      this.get('bars').forEach((bar) => {
        bar.unloadRecord();
      });
    }
  });
}
```

**Comment by marcelitocs** [comment] 2017-06-28 21:40
I'm also waiting the resolution for this problem

**Comment by XaserAcheron** [comment] 2017-06-28 21:54
Could a maintainer at least acknowledge this? This is stopping me from upgrading too, and now that 2.14 is a thing, I'm a bit concerned about being two versions behind.

**Comment by stefanpenner** [comment] 2017-06-28 22:03
> Could a maintainer at least acknowledge this?

acknowledged + exploring.

**Comment by XaserAcheron** [comment] 2017-06-28 22:06
Thanks @stefanpenner  -- that sets the mind at ease. :)

**Comment by rinoldsimon** [comment] 2017-07-19 04:35
Facing similar problem. Is the bug fixed in ember version 2.14.0 ?

**Comment by rviney** [comment] 2017-07-19 08:23
@rinoldsimon We encountered this issue trying to upgrade to 2.14.4 and so are staying on 2.12.2 for now.

**Comment by stefanpenner** [comment] 2017-07-19 13:44
Just a quick update. We have found the issue, ED is working around behavior in ember. We have just landed a change in ember https://github.com/emberjs/ember.js/pull/15510 which will make fixing this issue in ember-data simpler.

I aim to land the fix sometime in the next week as time permits. Sorry about letting this one linger so long.

**Comment by sudowork** [comment] 2017-07-19 18:36
Awesome, thanks so much for the update @stefanpenner !

**Closed** 2017-07-25 23:11 UTC
