### ISSUE TITLE
store.findAll doesn't populate meta property when promise resolves

### ISSUE THREAD

**Issue by mehulkar** [emberjs/data#5337] opened 2018-01-25 22:01 UTC
## Issue 
In 2.18.0, `store.findAll` does not set the meta property on the resolved `RecordArray`. 

## Example
I wasn't sure how best to create a live example of this without a backend, but here's an example:

response:

```json
{
  "data": [
    { "id": "1", "type": "post", "attributes": {  "name": "Foo Bar" } },
    { "id": "2", "type": "post", "attributes": { "name": "Foo Bar" } }
  ],
  "included": [],
  "links": {},
  "meta": {
    "someProp": "a meta prop!",
    "anotherProp": 42
  }
}
```

```js
// meta is set
store.query('post', {}).then(result => result.get('meta'))

// meta is not set
store.findAll('post').then(result => result.get('meta')) 
```

## Cause 

The `query` method sets up the RecordArray with a RecordArrayManager which sets the `meta` property:

https://github.com/emberjs/data/blob/v2.18.0/addon/-private/system/store/finders.js#L166

whereas the `findAll` method does not use the manager.

## Failing test case

```js
test("meta is proxied correctly on the PromiseArray", function(assert) {
  let defered = RSVP.defer();

  env.registry.register('adapter:person', DS.Adapter.extend({
    findAll(store, type, query) {
      return defered.promise;
    }
  }));

  let result;
  run(function() {
    result = store.findAll('person');
  });

  assert.notOk(result.get('meta.foo'), 'precond: meta is not yet set');

  run(function() {
    defered.resolve({ data: [], meta: { foo: 'bar' } });
  });

  assert.equal(result.get('meta.foo'), 'bar');
});
```

I just copied the one for `query` and replaced it with `findAll`:  https://github.com/emberjs/data/blob/v2.18.0/tests/integration/store/query-test.js#L28-L49

**Comment by runspired** [comment] 2018-03-18 00:26
Closing as a duplicate of #2905 

That said, it is difficult for us to provide support for `meta` on the `RecordArray` returned by `findAll` for the following reasons:

- `findAll('foo')` returns the same `RecordArray` as `peekAll('foo')`. Having `meta` for an unknown request would be confusing for folks using `peekAll`.
- `findAll('foo')` may  or may not hit network, and may or may not do so as a background request, it is uncertain what `meta` would refer to in this scenario.
- `findAll('foo')` contains all available records from all requests ever made as well as anything created client side, not just from the single request it may also make itself. It is uncertain how any `meta` object from a single specific request would be applicable to this array.

The above said, we are committed to building better APIs with first-class json-api support in the near future.

**Closed by runspired** 2018-03-18 00:26 UTC
