### ISSUE TITLE
Allow belongsTo to be used in templates so requests are not made for simple id uses

### ISSUE THREAD

**Issue by adam-knights** [emberjs/data#4407] opened 2016-05-27 13:53 UTC
Imagine the scenario where you are displaying a hundred or so models, each of which have a belongsTo relationship. So we are displaying 100 people, each of whom have a single pet.

There is no way that I want to download all 100 pets at this stage, but I do want to link to a page for more info on the pet, with the id as the link text. So we might want to do:

```
{{#each people as |person id|}}
  {{#link-to 'pet' person.pet}}{{person.pet.id}}{{/link-to}}
{{/each}}
```

That triggers off 100 requests to the backend if the pets aren't already in the store.

Equally, a simpler example would be

```
{{#each people as |person id|}}
  <p>{{person.pet.id}}</p>
{{/each}}
```

Its clear Ember will have the id of the pet, so why make a request? Anyway - assuming it has to do this instead, it would be lovely to be able to do something like

```
{{#each people as |person id|}}
  {{person.belongsTo.pet.id}}
{{/each
```

I've written my own helper function, get-relationship, see below, is this something that could be added to Ember directly, but included in a model?

```
import Ember from 'ember';

// This function wraps the new Ember data belongsTo and hasMany id behavior so we can get to id's in templates, without triggering requests

// Inputs
// params[0] - the model to look at the relationship of
// params[1] - the relationship to look for

export function getRelationship(params) {
  if (params === undefined || params === null || params.length < 2) {
    return null;
  }

  let model = params[0];
  let relationshipName = params[1];

  if (model === undefined || model === null || relationshipName === undefined || relationshipName === null) {
    return null;
  }

  return model.belongsTo(relationshipName).id();
}

export default Ember.Helper.helper(getRelationship);
```

I'd be happy to dev this if it would be accepted. @pangratz any thoughts?

**Comment by wecc** [comment] 2016-10-29 20:24
ping @runspired on this

**Comment by Romanior** [comment] 2016-11-02 10:55
If you can modify API, solution would be to use [sparse-fieldsets](http://jsonapi.org/examples/#sparse-fieldsets) or [links](http://jsonapi.org/format/#document-links).

**Comment by mansona** [comment] 2017-09-13 09:29
@Romanior how would you recommend using sparse-fieldsets with ember-data? The only documentation I can find is [this issue](https://github.com/emberjs/data/issues/4332) which references [this RFC](https://github.com/emberjs/rfcs/pull/31) both of which are closed as "not planning to implement". 

Personally, I'm not too pushed about that feature of ember-data because I think there are bigger fish to fry right now. I'm just asking because the way you were suggesting it suggested that you had a way to use sparse-fieldsets with ember-data 🤔

**Comment by runspired** [comment] 2021-05-22 06:32
In the octane world this is become a duplicate of #7324. Closing in favor.

**Closed** 2021-05-22 06:32 UTC
Labels: references
