### ISSUE TITLE
Deleting a record causes Record Array to dissapear

### ISSUE THREAD

**Issue by amk221** [emberjs/data#8632] opened 2023-06-07 09:52 UTC
### Reproduction

Here's a repo where I call `findAll` to load 2 records. Then, I call `destroyRecord` on one of them:

https://github.com/amk221/-ember-data-destroy-record/commit/03be4d87f0a79bcc6ef32727f4d20753bc51a122

The entire list of records dissapears. The ED inspector still has a reference to the remaining undeleted record, so I don't know what's going on.

### Versions

```
example@0.0.0 example
├─┬ @ember/test-helpers@2.9.3
│ ├─┬ @embroider/util@1.11.1
│ │ └── ember-source@4.12.0 deduped
│ └── ember-source@4.12.0 deduped
├─┬ ember-cli-app-version@6.0.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-data@4.9.1
│ └─┬ @ember-data/model@4.9.1
│   └─┬ ember-cached-decorator-polyfill@1.0.1
│     └── ember-source@4.12.0 deduped
├─┬ ember-modifier@4.1.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-qunit@6.2.0
│ └── ember-source@4.12.0 deduped
├─┬ ember-resolver@10.1.0
│ └── ember-source@4.12.0 deduped
└── ember-source@4.12.0

example@0.0.0 example
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@4.12.1 deduped
└── ember-cli@4.12.1

example@0.0.0 example
└── (empty)
```

...appologies for the terrible issue title

#### 4.9

![1](https://github.com/emberjs/data/assets/382061/d815cdd8-eadf-4213-9767-9d9e811db012)

#### 4.12
![2](https://github.com/emberjs/data/assets/382061/8a0b6932-8e9d-489d-b176-64a67eac4062)

**Comment by Jopie01** [comment] 2023-06-07 20:38
Duplicate of #8622?

**Comment by runspired** [comment] 2023-06-08 01:48
yep! Sorry folks, getting the new release out has proven tricky.

**Closed by runspired** 2023-06-08 01:48 UTC
