### ISSUE TITLE
Error on first model test "undefined is not an object (evaluating 'store.createRecord')"

### ISSUE THREAD

**Issue by cesarizu** [emberjs/data#4071] opened 2016-01-13 07:07 UTC
When updating to `ember-data@2.3.1` I get the following error:

```
Died on test #1 	at testWrapper (http://localhost:7357/assets/test-support.js:6400:16)
	at test (http://localhost:7357/assets/test-support.js:6413:44)
	at http://localhost:7357/assets/tests.js:1095:24
	at exports (http://localhost:7357/assets/vendor.js:99:39)
	at build (http://localhost:7357/assets/vendor.js:149:17)
	at findModule (http://localhost:7357/assets/vendor.js:197:14)
	at requireModule (http://localhost:7357/assets/vendor.js:184:22)
	at require (http://localhost:7357/assets/test-loader.js:67:16)
	at loadModules (http://localhost:7357/assets/test-loader.js:58:25)
	at load (http://localhost:7357/assets/test-loader.js:89:35)
	at http://localhost:7357/assets/test-support.js:6232:20: undefined is not an object (evaluating 'store.createRecord')
```

This happens only for the first model tested, the rest of the models work fine. Reverting to `ember-cli-shims@0.0.6` and `ember-data@2.2.1` makes it work (and restoring `ember-data` in `bower.json`).

It seems that somehow the store is not created/injected on time for the first model test but I cannot really figure out where the problem is.

Can anybody help me with some directions where should I start looking?

**Comment by bryanhickerson** [comment] 2016-01-13 16:46
I also have this issue. I was using ember-data@2.3.0.

**Comment by fivetanley** [comment] 2016-01-13 16:48
Could you make an isolated test case by running `ember new`, and making an example test?

**Comment by bryanhickerson** [comment] 2016-01-13 18:08
Reproduced it in a basic project here: https://github.com/bryanhickerson/model-test-error

**Comment by pangratz** [comment] 2016-01-13 18:22
Seems related switchfly/ember-test-helpers#130

**Comment by pangratz** [comment] 2016-01-13 19:04
It seems that when no `import DS from "ember-data"` is present, `DS` is not available in the `globalContext` [here](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/build-registry.js#L101) and hence `ember-data` is not setup correctly for the tests. Somewhere in the first unit test `DS` is imported - likely because the model is needed in the test and it extends `DS.Model` - and then the second unit tests succeeds.

@cesarizu @bryanhickerson if you add a `import "ember-data";` inside your `app/tests/test-helper.js`, the tests should pass. This is a workaround and should eventually be fixed in `ember-test-helpers`...

**Comment by bryanhickerson** [comment] 2016-01-13 19:09
Adding `import "ember-data";` worked. Thanks.

**Comment by jsmestad** [comment] 2016-01-20 00:38
Hit this issue and can as well confirm this resolves the issue.

**Comment by bryanhickerson** [comment] 2016-01-20 17:00
This is resolved for me in Ember Data 2.3.2.

**Comment by bmac** [comment] 2016-01-21 16:18
I can still reproduce this issue in Ember Data 2.3.2. https://github.com/bmac/test-ember-data-2-3

https://github.com/switchfly/ember-test-helpers/pull/138 fixes the issue for good in `ember-test-helpers`. 

Until there is a new release of `ember-test-helpers` and `ember-qunit` the best workaround is to `import "ember-data";` inside `app/tests/test-helper.js`. 

As @pangratz said the problem is code assuming `DS` is loaded in the global context before anyone has imported `ember-data` (`ember-test-helpers` is not the only library to make this assumption). This is true when Ember Data is loaded from bower but false when Ember Data is loaded as an `ember-cli-addon`. I don't believe there is a change that can be made to Ember Data that will fix this issue. However, I would be happy to be proven wrong on that assumption.

**Comment by bryanhickerson** [comment] 2016-01-21 16:45
Apparently the reason it was no longer failing for me is that I forgot to remove ember-data from bower.json.

**Comment by bmac** [comment] 2016-01-24 22:38
This should be fixed by: https://github.com/switchfly/ember-test-helpers/releases/tag/v0.5.21

To install the new version of `ember-test-helpers` you should only need to run the following commands:

```
rm -rf node_modules
npm cache clean
npm install
```

**Closed by bmac** 2016-01-24 22:38 UTC
