### ISSUE TITLE
Broken link in JSON Api ReadMe

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#9202] opened 2024-01-16 06:56 UTC
The link in JSON Api ReadMe brings 404 not found

https://github.com/emberjs/data/blob/c4d76edbe9300e68ca8a6bf746aa5579a5040096/packages/json-api/README.md?plain=1#L98

**Comment by runspired** [comment] 2024-01-16 20:38
duplicate of https://github.com/emberjs/data/issues/9111

**Closed by runspired** 2024-01-16 20:38 UTC
