### ISSUE TITLE
[Documentation] Polymorphic relationships / associations

### ISSUE THREAD

**Issue by buschtoens** [emberjs/data#4538] opened 2016-09-20 07:11 UTC
[`DS.belongsTo`](http://emberjs.com/api/data/#method_belongsTo) and [`DS.hasMany`](http://emberjs.com/api/data/#method_hasMany) are missing documentation for polymorphic relationships (originally added in #750).

[According to the tests](https://github.com/emberjs/data/blob/581781c3385c9384c0f3589281ebf1efced770ea/tests/integration/adapter/json-api-adapter-test.js#L23), the `{ polymorphic: true }` option has to be passed in. Is this still up to date?

I think this is a killer feature that should be featured more prominently :smile:

**Comment by wecc** [comment] 2016-10-20 21:51
Nice catch @buschtoens, would you be willing to create a PR updating the docs?

**Comment by wecc** [comment] 2016-10-21 15:02
Closing as a dupe of #4375, feel free to tackle that one instead :)

**Closed by wecc** 2016-10-21 15:02 UTC
Labels: Documentation
