### ISSUE TITLE
model.rollbackAttributes with errors doesn't clear hasDirtyAttributes

### ISSUE THREAD

**Issue by smcclstocks** [emberjs/data#3499] opened 2015-07-06 02:04 UTC
Steps to reproduce:

1. dirty a model in a way that causes validation errors
2. save
3. rollback
4. model.hasDirtyAttributes == true

If I call model.rollbackAttributes() twice hasDirtyAttributes == false. Also, my models value do appear to be reset.. meaning the changes are reverted but hasDirtyAttributes reflects incorrectly.

DEBUG: -------------------------------
ember.debug.js:5361DEBUG: Ember                          : 1.13.2
ember.debug.js:5361DEBUG: Ember Data                     : 1.13.4
ember.debug.js:5361DEBUG: jQuery                         : 1.11.3
ember.debug.js:5361DEBUG: Ember Simple Auth              : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth Cookie Store : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth OAuth 2.0    : 0.8.0
ember.debug.js:5361DEBUG: -------------------------------

**Comment by wecc** [comment] 2015-07-07 22:50
Closing as a dupe of #3498, please feel free to reopen if I'm mistaken.

**Comment by smcclstocks** [comment] 2015-07-08 00:36
I'm not smart enough with ember data to know. If #3498 is resolved & model.hasDirtyAttributes is still true then I'll reopen. I guess I can't really know until that one is fixed.

**Comment by RobIsHere** [comment] 2015-07-08 02:27
I had some quality time with ember data internals today. Also new to the low level ember data stuff ;) 


I'm experiencing this issue here while not having problems with attribute errors like detailed in #3498. In the debugger i see they are cleared. But hasDirtyAttributes is not.


The state changes after saving an invalid value that is rejected by the api:
invalid
uncommitted (after first call to rollbackAttributes)
loaded.saved (after second call to rollbackAttributes)


I'm just figuring out how everything works. My opinion is: The bug is around line 345 of states.js.

    rolledBack: function (internalModel) {
      internalModel.clearErrorMessages();
      internalModel.triggerLater('ready');
    },

    becameValid: function (internalModel) {
      internalModel.transitionTo('uncommitted');
    },

rolledBack is called, errors are cleared and a call to becameValid is triggered by that.
This moves the model into uncommitted state. For becameValid alone this behavior makes sense, there could be edited values that are valid.

That's the reason why it stays dirty: uncommitted = dirty


After rollback keeping it dirty makes no sense.
Maybe changing rolledBack could fix it? Like:

    rolledBack: function (internalModel) {
      internalModel.clearErrorMessages();
      internalModel.transitionTo('loaded.saved');
      internalModel.triggerLater('ready');
    },

That is what the first plus second rollback does put in one place. Trigger the transition to loaded.saved.

**Comment by wecc** [comment] 2015-07-09 22:14
I was probably too quick to judge this as a dupe of #3498.

**Comment by tchak** [comment] 2015-07-12 22:45
Sounds like @RobIsHere is right, I can see what is happening here. I will try to work on a fix tomorrow morning.

**Closed** 2015-07-20 13:56 UTC
