### ISSUE TITLE
Deprecation warnings with Ember 1.12.0

### ISSUE THREAD

**Issue by SaladFork** [emberjs/data#3069] opened 2015-05-14 15:40 UTC
I've updated to `ember-data@1.0.0-beta.17` but am still seeing deprecation warnings:

- `DEPRECATION: lookupFactory was called on a Registry. The initializer API no longer receives a container, and you should use an instanceInitializer to look up objects from the container.` from: [ember-data/lib/initializers/store.js:21](https://github.com/emberjs/data/blob/174fc94488d7e66ebb8b61e3bef142c0d051edca/packages/ember-data/lib/initializers/store.js#L21)

- `DEPRECATION: lookup was called on a Registry. The initializer API no longer receives a container, and you should use an instanceInitializer to look up objects from the container.` from: [ember-data/lib/initializers/store.js:39](https://github.com/emberjs/data/blob/174fc94488d7e66ebb8b61e3bef142c0d051edca/packages/ember-data/lib/initializers/store.js#L39)

**Comment by bmac** [comment] 2015-05-15 00:03
Looks like this is a duplicate of https://github.com/emberjs/data/issues/3051

**Closed by bmac** 2015-05-15 00:03 UTC
Labels: Bug
