### ISSUE TITLE
Ember Data 3.5+ re-fetches relationship in tests

### ISSUE THREAD

**Issue by mydea** [emberjs/data#6007] opened 2019-04-10 13:52 UTC
After upgrading from Ember Data 3.1 to 3.9, we noticed that a lot of our tests started to fail.
It seems that if I create models with an ID locally (e.g. `store.createRecord('model', { id: '1' })` and assign this somewhere, ED always tries to fetch it from the API.

I tracked it down, and it seems that it used to work until Ember Data 3.4.1, and then stopped working in 3.5.

An example test, that worked before but failed then:

```js
let store = this.owner.lookup('service:store');

let profile = store.createRecord('profile', {
  referenceLot: null
});
let processing = store.createRecord('processing', {
  profile
});
let model = store.createRecord('lot', {
  id: 1,
  processing
});

assert.notOk(model.get('isReferenceLot'));
await profile.set('referenceLot', model);
assert.ok(model.get('isReferenceLot'));
```

where the `lot` model looks like this:

```js
isReferenceLot: computed('id', 'processing.profile.referenceLot.id', function() {
  let id = get(this, 'id');
  let referenceId = get(this, 'processing.profile.referenceLot.id');
  return (id && id === referenceId);
}),
```

The issue is that once we do `profile.set('referenceLot', model)`, it triggers a GET request to /lots/1`, which fails.

**Comment by runspired** [comment] 2019-04-10 19:29
Thank you for reporting, I believe this is a duplicate of #5814 and possibly a few others. Sadly I've not had time to dig into it a fix but I do understand why this regressed in 3.5 and how a better architecture going forward would prevent it. I'm hopeful I can resolve it during a cleanup pass through the relationship layer that is coming soon if someone hasn't resolved it before then.

**Comment by runspired** [comment] 2019-05-14 22:52
A fix for this in being developed, closing as a duplicate of #5814

**Closed by runspired** 2019-05-14 22:52 UTC

**Comment by Leooo** [comment] 2019-10-22 14:13
I have the same issue in Ember-data 3.5 and believe it is different from https://github.com/emberjs/data/issues/5814. Can't judge if the fix in https://github.com/emberjs/data/pull/6112/files would solve this issue, but it looks pretty different (we don't want to do an API call at all in [unit] tests when setting a belongsTo relationship).
