### ISSUE TITLE
DS.Errors has no any messages

### ISSUE THREAD

**Issue by EmilTemirov** [emberjs/data#4182] opened 2016-02-23 16:30 UTC
Hi, All! 
I have the following model:
```javascript
// models/asset.js
export default DS.Model.extend({
  name: DS.attr(),
  type: DS.attr()
});
```
And the following response as result of `save`:
```javascript
res.status(400).send({
  'errors': [
    {
      'detail': 'Name must consist of 3 or more characters',
      'source': {
        'pointer': 'data/attributes/name'
      }
    }
  ]
});
```
But it is does not work, I have empty:

- `model.get('errors').get('messages')`
- `model.get('errors').errorsFor('name')`

What am I doing wrong?

**Comment by EmilTemirov** [comment] 2016-02-23 16:32
BTW, I'm using 2.3.3 version.

**Comment by EmilTemirov** [comment] 2016-02-23 16:39
Ahh, I've found in sources that HTTP status code should be **422**! Why it's not described in docs....

**Comment by bmac** [comment] 2016-02-27 22:14
Hi @EmilTemirov. Where where you looking in the docs for this information?

**Comment by EmilTemirov** [comment] 2016-02-29 11:02
Hi, @bmac! I was hoping to find some description about this on http://emberjs.com/api/data/classes/DS.Errors.html page. There is an example of JSON response, but nothing about **422** status code -(

**Comment by wecc** [comment] 2016-10-21 21:12
Not sure what adapter you're using but 422 seems to be documented for the RESTAdapter at http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_success-and-failure. I realize this issue is quite old now and that information could have been added after this issue was reported.

**Comment by wecc** [comment] 2016-10-21 21:12
I'm closing this as it's not a bug.

**Closed by wecc** 2016-10-21 21:12 UTC
