### ISSUE TITLE
Async in prod and debug version does not perform the same

### ISSUE THREAD

**Issue by cbou** [emberjs/data#4428] opened 2016-06-13 12:03 UTC
Because of the use of `assert` in the debug version of EmberJS Data, when using relationship with `async: false` the records needs to be loaded before using the relationship.

In the prod version, the `assert` is not present which is allow to the relationship even if the related record is not loaded yet. It will be updated as soon as the record is loaded.

To me the `assert` should be changed into a `warn`.

https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/belongs-to.js#L143
https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/has-many.js#L207

**Comment by fivetanley** [comment] 2016-06-13 16:52
Hi Charles,

Is it just that it's confusing that it's an error in development but allowed in production? Maybe we should change it to always throw?

**Comment by cbou** [comment] 2016-06-13 19:05
No please don't do this!

It's actually quite useful because sometimes the related record is loaded after.

**Comment by pangratz** [comment] 2016-08-17 12:05
> It's actually quite useful because sometimes the related record is loaded after.

@cbou I would say if you explicitly mark a relationship as synchronous via `{ async: false }` but sometimes the record is loaded after, you should treat your relationship as asynchronous. Otherwise side effects cannot be ruled out and this might result in unexpected behavior.

Any reason you're not using asynchronous relationships here?

**Comment by cbou** [comment] 2016-08-17 12:18
Some models I used are loaded and updated outside of EmberJS. They are still defined in EmberJS and pushed to the store using `store.pushPayload`.

Basically all the models (the pure EmberJS and the mixed ones) are loaded at the start of the application but the mixed one are sometimes loaded after the pure EmberJS ones. Pure EmberJS models are related to mixed ones which leads to errors if the mixed ones are not loaded and `{ async: false }` is not defined.

**Comment by cbou** [comment] 2016-08-17 12:24
I used `{ async: false }` to prevent EmberJS loading some models.

The reason is that I have some models which are loaded and updated outside of EmberJS. I keep them sync using `store.pushPayload`. I still defined these mixed models inside EmberJS in order to use them there (read only) and they are linked to other models which are loaded and updated in EmberJS.

**Comment by pangratz** [comment] 2016-08-17 12:38
> I used `{ async: false }` to prevent EmberJS loading some models.

Relationships are only loaded if they are explicitly requested... Maybe there is some code in your application which triggers loading of relationships as a side effect.

Can you provide some sample code / ember-twiddle demonstrating your use case?

**Comment by cbou** [comment] 2016-08-17 12:43
I request them in the templates when calling `{{a.b.name}}` and if the relationship is not loaded, I don't want EmberJS to load it. I want to have an empty name first until it's pushed from the other part of the app.

**Comment by pangratz** [comment] 2016-08-17 15:00
Hmm, I don't know of any easy solution to that at the moment 😔  

References added in #3303 allow you to check the loading state of relationships without triggering a fetch, but they are currently not available in templates...

**Comment by cbou** [comment] 2016-08-17 15:04
For the moment it's fine as long as an error is not throw in production like @fivetanley suggested.

It would be better if `assert` could be changed in `warn` to me but it's a nice to have.

**Comment by runspired** [comment] 2018-04-06 13:12
Closing this as a duplicate of #5226

**Closed by runspired** 2018-04-06 13:12 UTC
Labels: Needs Team Discussion
