### ISSUE TITLE
2.14.x UnloadAll cause save fail even after reload / query

### ISSUE THREAD

**Issue by SelokYeung** [emberjs/data#5156] opened 2017-08-28 07:46 UTC
Hi all,

I find something strange when I try to cleanup data store.

Currently I’m trying to unload all record of specific model type from data store with UnloadAll. Everything work fine unless user try to edit the unloaded record again. Changes can be submitted to server, but when data store try to update model it throw following exception.

> Assertion Failed: You cannot set an index for an internalModel that is not in the InternalModelMap

This only happen when I call DS.Store.unloadAll.
I have tried with DS.Store.unloadRecord and DS.Model.unloadRecord.
Both of them don't have this issue. Also if I reload record with DS.Store.findRecord with { reload: true }, it also work fine.

Ember version: 2.14.1
Ember Data version: 2.14.10

**Comment by Sinled** [comment] 2017-12-14 12:04
I also have this problem. 
Any ideas how to solve it or bypass?

**Comment by lolmaus** [comment] 2017-12-14 12:22
@Sinled Downgrade Ember Data to 2.12.

**Comment by jamesdixon** [comment] 2017-12-16 21:42
@lolmaus seems like the only option at this point, but not a great option considering it's 5 releases behind... 👎

**Comment by runspired** [comment] 2018-03-18 02:02
@selokyeung is this still an issue on `master`, and if so, could you provide a reproduction?

**Comment by SelokYeung** [comment] 2018-03-23 03:20
@runspired I'm still not upgrade my project to 3.0 yet (still using 2.18)
May be I'll try it few days later

**Comment by runspired** [comment] 2018-04-06 18:15
Closing  sinve this has been resolved since at least 2.18.

**Closed by runspired** 2018-04-06 18:15 UTC

**Comment by AleksandrBorovkov** [comment] 2018-05-07 12:50
@lolmaus I use unloadAll for specific model. When I try edit unloaded record again, changes submitted to server, but I get error "Assertion Failed: You cannot set an index for an internalModel that is not in the InternalModelMap"

**Comment by hshendrix** [comment] 2018-05-09 10:40
I am also facing this issue. At first I used destroyRecord to delete a specific record to initialize it again later. This is reflected in the local storage (via local-storage-adapter) but not in Ember Store. Then I tried the unloadAll method but it shows the same behavior. The records are deleted in the localstorage but somehow the records are still cached in the Ember Store. The App crashes with "Assertion failed..." I have to restart or clean the whole App data to get it working again.

**Comment by jpirok** [comment] 2019-03-15 17:41
Having the same issue currently with ember-cli 2.18.2, ember-data 2.18.0. After saving an individual object, I reload the entire list of objects that it came from. If I attempt to edit the same document again, I receive the "Assertion failed" exception.

**Comment by gokulsupersaiyan** [comment] 2019-07-29 17:42
@jpirok - (https://github.com/gokulsupersaiyan/data/commit/3cab5e7b0cd3564f3cdcc8557ef2bd2a8129874d) change seems to fix this. But I am not sure why this line was removed in latest ember-data.

**Comment by jpirok** [comment] 2019-07-29 18:02
@gokulsupersaiyan Thanks for showing me that! I'll be interested to see if that is pulled in to the 2.18.x version. I can't upgrade to 3.x right now and this version is my only option.

**Comment by gokulsupersaiyan** [comment] 2019-07-29 18:16
@jpirok I am also using ember-data:v2.18.5 from this branch (https://github.com/gokulsupersaiyan/data/tree/v2.18.5-patch). I am just curious to know that is that removed intentionally or not. if it is not an intentional change, I will raise a PR against the latest version. FYI, The problem didn't happen for ember-data v2.12.x.

**Comment by aluink** [comment] 2019-09-25 19:41
fwiw, I just had this same issue with ember-data:v3.12.0 when calling `this.store.unloadAll('my-model')`.  My solution was to call what feels like a hack: `this.store.peekAll('my-model').map(x => x.unloadRecord())`
