### ISSUE TITLE
JSONAPISerializer: extractMeta is never called

### ISSUE THREAD

**Issue by urbany** [emberjs/data#4602] opened 2016-10-20 10:29 UTC
It is called here for the JSONSerializer:
https://github.com/emberjs/data/blob/v2.9.0/addon/serializers/json.js#L461

But the JSONAPISerializer doesn't use its parent _normalizeResponse (does not call _super) nor calls extractMeta anywhere.

Is this on purpose? I'm trying to parse all the meta info to camelize the hash keys and was using the extractMeta to do this.

Thanks in advance.

**Comment by pangratz** [comment] 2016-10-20 10:50
I am closing as this is a duplicate of #4161 and the other issue has more context. Thanks for opening this issue though, this is something which definitely should be fixed. Please chime in at the other discussion.

Thanks!

**Closed by pangratz** 2016-10-20 10:50 UTC
