### ISSUE TITLE
Getting error when API returning a null response

### ISSUE THREAD

**Issue by jpoiri** [emberjs/data#4207] opened 2016-03-04 15:41 UTC
I'm getting this error when saving the model and the API returns a code 201 with an empty response. If the API returns a blank object problems goes away.

I am using ember-data@2.3.0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at jQuery.parseJSON (http://localhost:4200/assets/vendor.js:7877:14)
    at ajaxConvert (http://localhost:4200/assets/vendor.js:8154:19)
    at done (http://localhost:4200/assets/vendor.js:8570:15)
    at XMLHttpRequest.<anonymous> (http://localhost:4200/assets/vendor.js:8960:9)

**Comment by bmac** [comment] 2016-03-05 20:33
I've hit this error on several projects. The error is originating from jQuery which attempts to `JSON.parse` the response text if the `Content-Type` header in the response suggests the payload is json.

**Comment by pangratz** [comment] 2016-03-30 17:33
Looks like this is the intended behavior by jQuery: https://jquery.com/upgrade-guide/1.9/#jquery-ajax-returning-a-json-result-of-an-empty-string.

**Comment by bmac** [comment] 2016-03-30 23:57
Closed via https://github.com/emberjs/data/pull/4290

**Closed by bmac** 2016-03-30 23:57 UTC
Labels: Bug

**Comment by enspandi** [comment] 2016-10-25 15:25
Just had the same issue, but with HTTP 205 Reset Content.

In my opinion **we always tell jQuery to expect a json payload using the `dataType` option**:
http://api.jquery.com/jquery.ajax/
`dataType: The type of data that you're expecting back from the server.`

RESTAdapter sets `dataType: 'json'`:
https://github.com/emberjs/data/blob/v2.9.0/addon/adapters/rest.js#L1048

Overriding `ajaxOptions` with the 'auto' dataType works for me:
`dataType: '*'`

Interestingly jQuery seems to have custom implementation for 204 No Content but not for 205 Reset Content which also must not have a payload per spec :(

Is there a reason for this? It seems to be there since first commit in 2012...
https://github.com/emberjs/data/blob/v2.9.0/addon/adapters/rest.js#L1048
