### ISSUE TITLE
hasMany Create - UnloadRecord keeps the old state

### ISSUE THREAD

**Issue by lsg-braymon** [emberjs/data#5850] opened 2019-02-11 23:14 UTC
### Reproduction

- [Twiddle](https://ember-twiddle.com/c0363fcbee3d705ddf24df9263b2f531?openFiles=templates.application.hbs%2C)

### Description

This is the model setup:
1. Group
    * Belongs to Group (self-referencing)
    * Has many Groups
    * Has many Items
1. Item
    * Belongs to Group

The scenario is that a template shows a tree display of `Group A` that three items: `Item 1`, `Item 2` and `Item 3`:
```
- Group A
    ⤷ Item 1  [Create Group] [Unload Item]
    ⤷ Item 2  [Create Group] [Unload Item]
    ⤷ Item 3  [Create Group] [Unload Item]
```
Items can be grouped together as a sub-group of `Group A`. Each item has two buttons: create a sub-group and unload record. Creating a sub-group works fine and it will look something like this (Assume that Item 1 was the item to be sub-grouped):
```
- Group A
    ⤷ Sub-Group B
        ⤷ Item 1  [Create Group] [Unload Item]
    ⤷ Item 2  [Create Group] [Unload Item]
    ⤷ Item 3  [Create Group] [Unload Item]
```
Unload an Item that is under `Group A`, say `Item 3` is unloaded. `Item 3` is unloaded correctly however `Item 1` is now displayed twice, under `Group A` and `Sub-Group B`.
```
- Group A
    ⤷ Sub-Group B
        ⤷ Item 1  [Create Group] [Unload Item]
    ⤷ Item 1  [Create Group] [Unload Item]
    ⤷ Item 2  [Create Group] [Unload Item]
```
What is expected is that `Group A` should just contain `Item 2`:
```
- Group A
    ⤷ Sub-Group B
        ⤷ Item 1  [Create Group] [Unload Item]
    ⤷ Item 2  [Create Group] [Unload Item]
```

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
ember-source@3.7.3
ember-cli@3.7.1 
ember-data@3.5.1 (this bug can be reproduced even in version 3.7.x)
```

**Comment by runspired** [comment] 2019-02-16 00:26
You've hit a lesser seen variant of a well known issue: we have a hard time tracking changes to relationships and knowing when/if they've been persisted. What happens here is that `item-1`'s move to the sub-group B is part of a dirty-state change to group A. When the other item is unloaded from group A, it triggers a call to `flushCanonical` assuming that we now need to update local state to account for new persisted information. `canonical` still includes `item-1`, unless the move to the sub-group was persisted and updated relationship information had been given to the store for the correct persisted state.

I'm going to close this once I figure out which of the many open issues around this bug should be the source-of-truth for the book-keeping for it.

These sorts of issues will be much easier to solve (either by us or by you) once the #5770 has landed.

**Comment by runspired** [comment] 2019-02-16 00:27
You may also be interested in reading this [thread](https://twitter.com/Runspired/status/1058536977597775872).

**Comment by cbou** [comment] 2019-07-16 06:47
Is there any timeframe for this bug?

It's reproducible since ember-data 3.0.1.

3.0.0 is working correctly.

**Comment by runspired** [comment] 2023-09-04 08:04
As of #8807 this bug is no longer an issue

**Closed by runspired** 2023-09-04 08:04 UTC
Labels: unload-apis
