### ISSUE TITLE
Setting belongsTo relation will not change hasDirtyAttributes

### ISSUE THREAD

**Issue by hamzahio** [emberjs/data#5138] opened 2017-08-18 20:09 UTC
Setting belongsTo relation will not change hasDirtyAttributes to true

if I have models/book.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  name            : DS.attr('string'),
  author          : DS.belongsTo('author')
});

```
and I have models/author.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  name            : DS.attr('string'),
  bio             : DS.attr('string'),
});

```

if I do this 
```
this.set("model.author",author);
this.get("model.hasDirtyAttributes") // return false;

```
the relationship changed but model not changing hasDirtyAttributes

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.15.0-beta.3
DEBUG: Ember Data        : 2.15.0-beta.4
DEBUG: jQuery            : 3.2.1
DEBUG: Ember Simple Auth : 1.4.0
DEBUG: -------------------------------
```

**Comment by dknutsen** [comment] 2017-08-22 14:35
This has actually been an issue for a long time. I just ran into it recently and there's a long string of issues which eventually lead to [this rfc](https://github.com/emberjs/rfcs/pull/21) and [a couple](https://github.com/emberjs/data/pull/4361) of [pull requests](https://github.com/emberjs/data/pull/3698) but unfortunately there doesn't seem to be much movement. 

If you need a solution immediately there are a [couple](https://github.com/meszike123/ember-managed-relationships) of [addons](https://github.com/danielspaniel/ember-data-change-tracker) you could try but barring that I guess it's just wait and see 🤷‍♂️

**Comment by Bartheleway** [comment] 2018-04-09 20:27
You could simply consider that your record is dirty when you enter your `edit` route and `reload` then record when you leave if you haven't hit the save button.

I also agree that this is kind of annoying but looking at the links @dknutsen posted, the general use case seems really complicate to handle.

**Comment by runspired** [comment] 2018-04-09 21:00
Closing as a duplicate of #2455 (which we also elected to close). As noted, relationship rollback is a non-trivial problem.

That said, @hjdivad and I have some thoughts on a potential path for at least providing a signal to the relationship state for when it has been saved, which is much better than we do today.

**Closed by runspired** 2018-04-09 21:00 UTC
