### ISSUE TITLE
Using filterBy on PromiseManyArray doesn’t work as expected with Glimmer

### ISSUE THREAD

**Issue by jgwhite** [emberjs/data#4046] opened 2016-01-05 15:59 UTC
Computed properties that filter a PromiseManyArray don’t re-render as expected when used in templates. See reproduction below:

https://ember-twiddle.com/7e5df2d56a3f78f18e25?numColumns=1&openFiles=application.controller.js%2C

Apologies for the lack of detail — still digging into exactly what’s going wrong here.

**Comment by HeroicEric** [comment] 2016-01-05 19:19
I think it has to do with your not updating the other side of the relationship.

If you check out https://ember-twiddle.com/bc20d9b69cf1229b0bc5?numColumns=3&openFiles=application.controller.js%2Capplication.template.hbs%2Capplication.route.js,
the rerender seems to work when the `favourites` change.

I agree though, that this behavior is confusing. Even more confusing that it seems to work on the initial render...

**Comment by sly7-7** [comment] 2016-01-06 10:43
@jgwhite Using the '.content' workaround make the thing working: https://ember-twiddle.com/c0338cd0424f658c60fa?numColumns=3&openFiles=application.controller.js%2Capplication.template.hbs%2Capplication.route.js

**Comment by jgwhite** [comment] 2016-01-06 10:51
@sly7-7 thanks, that’s a good tip. Still, it seems like this *shouldn’t* require any workarounds. `ManyArray` works  just fine.

**Comment by sly7-7** [comment] 2016-01-06 11:12
Hmm, alos see, https://ember-twiddle.com/7e5df2d56a3f78f18e25?openFiles=application.controller.js%2Capplication.route.js, using ember 2.0.2, it is working well...

**Comment by jgwhite** [comment] 2016-01-06 11:28
@sly7-7 hmm… perhaps a change in the contract for observing enumerables?

**Comment by sly7-7** [comment] 2016-01-06 12:50
Yeah, it seems like there is also some issues with ember itself (see the referenced issue), but clearly difficult to find out the root cause

**Comment by jgwhite** [comment] 2016-01-06 17:20
This appears to be a problem in `computed.filterBy`. Closing this issue in favour of https://github.com/emberjs/ember.js/issues/12475

**Comment by runspired** [comment] 2016-01-06 17:30
@jgwhite I believe you have closed this prematurely, I still believe this is an ED bug, https://github.com/emberjs/ember.js/issues/12475#issuecomment-169397040

**Comment by jgwhite** [comment] 2016-01-06 17:31
@runspired thanks for investigating further. Re-opening.

**Comment by fivetanley** [comment] 2016-01-06 17:41
I don't think `replace` in `ManyArray` is following the rules for Ember.Array. It's supposed to set length. https://github.com/emberjs/data/blob/cf889b35a1f31d42fd54598ca9d5bc7753644a52/addon/-private/system/many-array.js#L187

https://github.com/emberjs/ember.js/blob/8d62be51ce9602ce6f3aa05682a2847af8b5dc7a/packages/ember-runtime/lib/mixins/array.js#L95

**Comment by fivetanley** [comment] 2016-01-06 17:44
Something else to consider https://github.com/emberjs/ember.js/blob/9899dffe5af3d902a00f9676e7118697d6b1bc7c/packages/ember-runtime/lib/mixins/mutable_array.js#L56

**Comment by adam-knights** [comment] 2016-01-08 15:50
@fivetanley would setting length and calling that method be relatively straight forward single line things that ember data should be doing? Could these things be causing https://github.com/emberjs/ember.js/issues/12475 ?

**Comment by runspired** [comment] 2016-01-08 16:20
@adam-knights my opinion from the feedback/investigation that I've done is that emberjs/ember.js#12475 is mostly if not entirely related to ED code issues that either originated around the time of Ember 2.0 or were pre-existing issues surfaced by changes in Ember around then.

**Comment by Serabe** [comment] 2016-01-11 22:32
Investigating another issue in balinterdi/rarwe-code I see it happens with `computed.sort` as well.

[Twiddle](https://ember-twiddle.com/0d1906e0a753e0f88b4d)

**Comment by sly7-7** [comment] 2016-02-11 07:57
I'm closing, https://github.com/emberjs/ember.js/pull/12908 seems to fix all the things. I just tried the twiddles with ember & ember-data canary, they are working well.

@jgwhite Could you confirm please, and reopen if it does not fix your case ?

**Closed by sly7-7** 2016-02-11 07:57 UTC
