### ISSUE TITLE
ember-data 4.6 fails to boot in fastboot

### ISSUE THREAD

**Issue by ef4** [emberjs/data#8101] opened 2022-08-04 20:19 UTC
This use of `FastBoot.require`:

https://github.com/emberjs/data/blob/637a7d4ae202273bb4c5cfecdd5a6126a43543fa/packages/store/addon/-private/identifier-cache.ts#L34

is only legal if the app explicitly adds `"crypto"` to the fastboot whitelist, which is not the default. Out of the box, this will cause a crash at boot.

### Reproduction:

1. Generate a new app with ember-cli 4.6.0.
2. Install ember-data 4.6.1 and ember-cli-fastboot 3.3.2
3. `ember s`
4. Visit the homepage.

### Observed failure:

```
Error: Unable to require module 'crypto' because it was not in the whitelist.
    at Object.require (/Users/edward/hacking/ember-data-example/node_modules/fastboot/src/fastboot-schema.js:191:15)
    at Module.callback (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:1647:1)
    at Module.exports (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/pj/93dgp7m57k97tby2ss0qv9nm0000gn/T/broccoli-31264hB6VoOlolJp6/out-319-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
```

### Workaround

Apps can add the following to package.json:

```
  "fastbootDependencies": [
    "crypto"
  ]
```

**Comment by runspired** [comment] 2022-08-05 18:46
We have to revert this change anyway because the browser's uuid generation is currently gated behind secure contexts, though our decision to revert also appears to have helped motivate browser reps to revisit their decision to do so. See #8097 

However, we have historically always enforced that users add `crypto` to their fastboot dependencies for ember-data, see https://github.com/emberjs/data/blob/f4bfbaa148b67104d0022fd176faa0f4a612289a/packages/store/addon/-private/identifiers/utils/uuid-v4.ts#L16

```
            'Using createRecord in Fastboot requires you to add the "crypto" package to "fastbootDependencies" in your package.json'
```

Closing as this is probably something specific to embroider and this requirement has been in place for ~4 years.

**Closed by runspired** 2022-08-05 18:46 UTC

**Comment by ef4** [comment] 2022-08-05 18:54
> However, we have historically always enforced that users add crypto to their fastboot dependencies for ember-data

Ah, I did not know that. So what changed wasn't the requirement itself, it was the timing of when the requirement gets checked.

**Comment by runspired** [comment] 2022-08-05 19:07
@ef4 we wouldn't have done the require check in the past until a uuid was actually generated, with the lack of need of polyfill (in theory, obviously turns out to be problematic given secure context restriction) we moved to eagerly determining the crypto module. More than likely nothing in your fastboot setup was calling `createRecord` and so no uuid was ever being generated.

**Comment by mansona** [comment] 2022-08-14 14:08
Great that this has been fixed 🎉 

Is there a plan to backport it and release it as a patch release for  v4.6.x?

**Comment by ef4** [comment] 2022-08-14 15:00
Yeah, I think it's probable that existing apps never happen to call `createRecord` in fastboot and therefore didn't notice that they're technically supposed to be allowing the `crypto` module. 

In my case, I noticed this in a test that uses ember-data in a read-only capacity, which seems not unrealistic for some apps.

**Comment by runspired** [comment] 2022-08-14 23:01
@mansona the thing that has been fixed is randomUUID sometimes needing a polyfill. Crypto has always been required and should be added to the fastbootDependencies. While today we only use it for createRecord that's unlikely to stay the case for much longer, especially once we begin serializing the cache for rehydration.

**Comment by elwayman02** [comment] 2022-12-07 19:36
@runspired where is the Crypto requirement documented? I'd love to check out that reference and learn more about it.

**Comment by runspired** [comment] 2022-12-07 19:57
@runspired it was documented by the error itself which would tell you what was needed

We should probably add the fastboot note here where we document the polyfill though:

api docs: https://api.emberjs.com/ember-data/release/modules/ember-data-overview?show=inherited
readme: https://github.com/emberjs/data#randomuuid-polyfill

As @jenweber and I work to build out a new docs site I'll be sure to add an SSR guide

**Comment by elwayman02** [comment] 2022-12-07 20:28
FWIW, the error itself isn't really clear as to what's going on, why it's happening, or how to fix it. The error message doesn't even say it has anything to do with FastBoot - you have to dig into the stack trace to figure that out, and even then it's not clear that it's something you can fix as easily as adding to `fastbootDependencies`. The only reason I found this issue is because I dug into the stack trace to find out there was a FastBoot issue coming from Ember-Data, and then I had to search this specific library to find this issue in order to figure out how to fix it. There wasn't any information before that which would indicate what's going on to a user that isn't already intimately familiar with FastBoot.

**Comment by runspired** [comment] 2022-12-07 20:49
@elwayman02 historically we threw this error: https://github.com/emberjs/data/blob/3122d68f435295c110db31820a07179209472ded/packages/store/addon/-private/identifiers/utils/uuid-v4.ts#L11-L19

we could restore that, though to be honest `Fastboot.require` should be giving you a nice error for this, and if it isn't we should fix fastboot.

**Comment by runspired** [comment] 2022-12-07 21:34
@elwayman02 you should have gotten this (meaningful) error https://github.com/ember-fastboot/ember-cli-fastboot/blob/703e78832fbb8d4c9d9ace9d9aee6a4e7a72bed5/packages/fastboot/src/fastboot-schema.js#L197-L203

**Comment by elwayman02** [comment] 2022-12-07 22:27
Here's the error that shows up in the CI build output (thrown from `prember` in this case, I believe): 

```
3:17:14 PM: pre-render / failed with exception: Error: Unable to require module 'crypto' because it was not in the whitelist.
```

When trying to reproduce locally, it throws this error and stack trace:

```
Error: Unable to require module 'crypto' because it was not in the whitelist.
    at Object.require (/Users/jhawker/Projects/GitHub/ember-scroll-modifiers/node_modules/fastboot/src/fastboot-schema.js:191:15)
    at Module.callback (/var/folders/wr/v2dt2mt942z423476t52cgwh0011pt/T/broccoli-69899in97ZXae598/out-484-broccoli_merge_trees/assets/addon-tree-output/@ember-data/store/-private.js:124:1)
```

That's the only information it gives you to go off of. The text "because it was not in the whitelist" doesn't really have any meaning without context, which meant having to dig several layers further to actually understand what was going on.
