### ISSUE TITLE
json-api content-type setting doesn't seem to conform to the spec

### ISSUE THREAD

**Issue by bcardarella** [emberjs/data#4226] opened 2016-03-09 21:17 UTC
According to this: https://github.com/emberjs/data/commit/76cf421556c80cff61462c49cd70cc193bdca9c5#diff-8915e0cf485f8b8db729bc3d3d5b855bR27

it appears that the content-type in the header is only being set if there is a pre-existing content-type? According to the spec the content-type *must* be set on each request: http://jsonapi.org/format/#content-negotiation-clients but it seems that this is not the case for `GET` requests with this implementation.

I'm lacking some context on why it was implemented this way, is this a bug?

**Comment by bcardarella** [comment] 2016-03-09 21:31
This function is calling the `RESTAdapter`'s function which only sets the `contentType` if there is a data object and the request is not `GET`: https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L913

I suspect this might not conform to the spec:

> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.

**Comment by wecc** [comment] 2016-03-09 22:10
I'm think this is by design. The spec states that "all JSON API data in request documents" must use the correct Content-Type header value. GET requests has no data, therefor no Content-Type header is set.

**Comment by pangratz** [comment] 2016-04-09 19:11
@dgeb can I shamelessly ping you here and get your input on this topic?

**Comment by jamesdixon** [comment] 2016-04-17 04:02
I just ran into this as well and understand where @wecc is coming from with regards to GET requests having no data. However, GET requests can have query parameters that are part of the JSON API spec (`include`, `fields`, etc). In my application, we process those particular query parameters uniquely if the incoming request has a `content-type` of `application/vnd.api+json`. Given that the spec is a bit ambiguous in this regard, is there any harm in setting the default content type on all requests to the proper JSON API type?

**Comment by dgeb** [comment] 2016-05-04 17:36
@wecc's interpretation is correct here. The `Content-Type` header requirement only applies when data is sent in a request document. If there is no request document, say for GET or DELETE requests, then the header `Content-Type: application/vnd.api+json` does not need to be set.

However, the media type `application/vnd.api+json` MUST appear in the `Accept` header, indicating that the client will accept a response document of this type.

**Comment by wecc** [comment] 2016-10-21 21:01
I'm closing this issue since it's not a bug.

**Closed by wecc** 2016-10-21 21:01 UTC
