### ISSUE TITLE
Incorrect test for unit/store/createRecord w/ camel-case string

### ISSUE THREAD

**Issue by noazark** [emberjs/data#3969] opened 2015-12-04 21:45 UTC
I'll admit that I may be reading the intention of this test wrong, but it seems like there is a mismatch here:

https://github.com/emberjs/data/blob/master/tests/unit/store/create-record-test.js#L81

I believe this line should be:

```
record = store.createRecord('someThing', attributes);
```

Correct?

**Comment by pangratz** [comment] 2015-12-05 12:21
Good catch @noazark! But I think this test is obsolete in general since #3033. I think it would be save to remove it as a whole. Especially since test is a duplicate of the [test below](http://git.io/vR0hp).

**Closed** 2015-12-07 23:14 UTC
