### ISSUE TITLE
Make changedAttributes smarter to understand mutating attributes

### ISSUE THREAD

**Issue by tim-evans** [emberjs/data#2825] opened 2015-02-27 21:16 UTC
I'm medium about this, but it would prevent some users (myself included) from shooting themselves in the foot. I have a DS attribute that's an array that gets mutated by a token-field (a list of tags).

It would be nice for changedAttributes to play nice with this workflow. If not, could a note be made communicating to developers to use an immutable data approach?

**Comment by fivetanley** [comment] 2016-01-16 03:37
I am all about the immutable data approach. We should talk. :)

**Comment by tim-evans** [comment] 2016-01-16 04:33
Deal. I think the problem with this is whether to bake this into Ember so devs don't have to think about it and everything's immutable, or we ask devs to use something like https://github.com/swannodette/mori explicitly.

**Comment by wecc** [comment] 2016-10-22 16:04
@fivetanley @tim-evans did you talk about this? 🗣

**Comment by tim-evans** [comment] 2016-10-22 23:16
We didn't :/

**Comment by runspired** [comment] 2018-04-23 20:50
This is a duplicate of

- #1540 for `isDirty` calculations
- #3546 for general support

Closing in favor of those tickets.

**Closed by runspired** 2018-04-23 20:50 UTC
