### ISSUE TITLE
Polymorphic Pattern via (seemingly arbitrary) Mixin w/ JSONAPI 

### ISSUE THREAD

**Issue by hhff** [emberjs/data#3919] opened 2015-11-12 11:51 UTC
Hi All!

Apologies if this has been resolved, but seeing as I'm on Ember Data `1.13.9` I thought I'd report this.

I'm working on some basic polymorphic stuff with Active Model Serializers `0.10.0.rc2`, and its JSONAPI Adapter.

I'm used to the "Mixin" pattern for Polymorphism in Ember, **however** I've noticed that this works without any hitches:

```
// mixins/statisticable.js

import Ember from 'ember';
import DS from 'ember-data';

export default Ember.Mixin.create();
```

```
// models/recap.js

import DS from 'ember-data';

// ---> NOTE: Nothing is mixed in here!

export default DS.Model.extend({
  statistics: DS.hasMany('statistics')
});
```

```
// models/statistic.js

import DS from 'ember-data';

export default DS.Model({
  statisticable: DS.belongsTo('statisticable', { polymorphic: true })
});
```

In the case above, `recap.js` does not have `Statisticable` mixed in.  It simply requires that `mixin:statisticable` exists on the container, and doesn't check that it's mixed into the class Polymorphic class.

Without the mixin existing, ED complains that there's no model called `statisticable`.

So it seems like the requirement for there to be a `mixin:statisticable` is kinda arbitary?  Or am I missing something?

**Comment by rwjblue** [comment] 2015-11-12 18:11
You have to have either a model or a mixin when using polymorphic types.  [See here](https://github.com/emberjs/data/blob/309d481958cd66c9dae6f59fdec20768b3a9d14c/packages/ember-data/lib/system/store.js#L1510-L1517) for the current implementation.

**Comment by hhff** [comment] 2015-11-13 00:10
Yup - I understand (and quite like) the "official" pattern.  Just seems like a stumbling block that the `statisticable` model (inverse to the polymorphic declaration) doesn't actually need the Mixin applied to it - it simply needs to exist.

In the above case, does the "dummy mixin" actually do anything?  Again - I may be missing something.

**Comment by igorT** [comment] 2015-11-13 20:03
In this case the `statistics` relationship might not be wired up correctly, because you didn't declare it on the parent class but should otherwise work

**Comment by hhff** [comment] 2015-11-14 06:45
Thanks dudes!  `Recap#statistics` is declared in the `models/recap.js` so that relation should be fine.

Again - I'm more highlighting that it's a little confusing there's no check to ensure the Mixin is actually applied to the "polymorphic" Model (`Recap` in this case).  

Feels arbitrary that a Mixin even has to exist here.  Just wanted to let you know it may be confusing for beginners!

**Comment by wecc** [comment] 2016-10-21 23:41
I'm going to close this as it's working as intended by **not** applying the mixin – it just has to exist.

In #4375 we're tracking the improvement of docs around polymorphic relationships.

**Closed by wecc** 2016-10-21 23:41 UTC

**Comment by hhff** [comment] 2016-10-22 01:05
thanks @wecc !
