### ISSUE TITLE
Not able to see all properties in Response Header (RESTAdapter).

### ISSUE THREAD

**Issue by santanapaulo** [emberjs/data#5427] opened 2018-04-09 20:25 UTC
I'm currently working with this code below.

```javascript
import RESTAdapter from 'ember-data/adapters/rest';
import { computed } from '@ember/object';
import { inject as service } from '@ember/service';

export default RESTAdapter.extend({
  tokenService: service('token-service'),
  headers: computed('tokenService.token', function () {
    return { Authorization: `Bearer ${this.get('tokenService').getToken()}` };
  }),
  handleResponse(status, headers) {
    const { authorization } = headers;
    if (authorization && authorization !== this.get('tokenService').getToken()) {
      this.get('tokenService').setToken(authorization);
    }
  },
});
```

When I debugged that, to see what headers the handleResponse has, I only able to access two properties, but the Google Chrome Network brings a lot of other properties, and, one of those is a property that I really need to have access. 

Can anyone help me with this? I don't know why I can see just 2 properties on the headers property, once I have almost 10 on the Google Chrome Network. 

Is this a bug or something similar?

Important info: the ember version is `"ember-cli": "~2.18.2" and "ember-data": "~2.18.0"` .

**Comment by runspired** [comment] 2018-04-09 20:54
Seems likely to be a duplicate of #4342 

In 2.18:

- we parse the response headers https://github.com/emberjs/data/blob/v2.18.2/addon/adapters/rest.js#L1493
- using this method (which receives jquery parsed headers) https://github.com/emberjs/data/blob/v2.18.2/addon/-private/utils/parse-response-headers.js
- which enforces lower case (See #4342)

On master today, we currently pass headers through directly, although this seems like a mistake https://github.com/emberjs/data/commit/dd2662e11d4c80e835ca7b84e08ee7727563afeb#diff-72c4292e6eedd1425a5c51ef498585b7R1220

**Comment by santanapaulo** [comment] 2018-04-09 21:00
I think this is a Ember issue, because I tried to pass the header using Mirage, and it worked. But, again, when I use the API, I cannot see the headers I want. This occurs for the authorization property.

**Comment by runspired** [comment] 2018-04-09 21:04
See https://github.com/emberjs/data/issues/4952

**Comment by tchak** [comment] 2018-04-09 21:10
We should lower case all the headers + add Title case headers with deprecation.

**Comment by santanapaulo** [comment] 2018-04-09 21:12
@tchak , I think I understood. But in which method should I do this? I am currently using the handleResponse, and I think it should be done in the `generatedDetailedMessage`, but I'm not sure about it.

**Comment by runspired** [comment] 2018-04-16 18:48
closing as a duplicate of #4952. This is high on my list of annoying-things-to-resolve, I may be able to get a PR up today.

**Closed** 2018-04-16 18:50 UTC

**Comment by santanapaulo** [comment] 2018-04-16 21:16
Thank you @runspired. When you PR it, try to notify me. I want to make a party for that. 

This caused some troubles for me rsrsrsrsrs.
