### ISSUE TITLE
Two model instances with the same ID

### ISSUE THREAD

**Issue by almcc** [emberjs/data#2768] opened 2015-02-09 21:48 UTC
Hi,

I am just starting out with Ember and Ember data but I am repeatedly able to end up with two models in my model store with the same ID. Here is what I am doing:

I have a standard ember data setup with a rest adapter backed with django rest framework API which all works great. However when django changes a model (Create | Update | Delete) I send an event over amqp with the json serialisation of the model. I then have a bridge that turns all qpid events into socket.io events. In my ember app I listen for model change events and when I get them I push them to the store if they are a create or update, or unload them if they are a delete event.

Unfortunately all instances of the ember app get this event including the original requestor. As Django is very serial in its operations the socket.io event gets back to the originally requesting instance of the app before the HTTP request is finished (i'm guessing here, but it seems logical). Every time I end up the same model in the store twice.

When I introduce a 1 second delay in my amqp to socket.io bridge everything works fine, presumably because the push function call to the store updates the model it orginally recieved via the REST interface 0.9 of a second previsouly.

I'm using ember-data-1.0.0-beta.14.1 and happy to answer any more questions and help where I can.

Al

**Comment by bmac** [comment] 2015-02-09 22:41
I've seen this bug before too and worked around it by adding a delay in my `socket.io` event handler before pushing the new record. 

Unfortunately, I'm not really sure if there is a way for Ember Data to fix the duplicate record as there is no way for Ember Data to know that the new record pushed into the store is the same as the record currently being saved and once its added to the store Ember Data doesn't know if something else already has a reference to the pushed record so it can't simply remove that record once the saving record gets its id. I'd love to be proven wrong on this theory if anyone has any ideas.

The current behavior is definitely broken. Maybe we should add an assert to error if a newly saved record is going to duplicate an existing id?

**Comment by almcc** [comment] 2015-02-09 23:03
Yes, my only solution so far has been to introduce a delay on the socket.io event handler.  

I have been trying to find a way to query the store to see if it is currently saving anything of that model type and if so then wait until that has finished. No luck so far.

**Comment by bmac** [comment] 2015-02-09 23:17
One thing that might work (I haven't tested it) is trying to unload the relationship before Ember Data process the response from `createRecord` in the adapter. This would only work if you are not holding on to a reference to record created when you pushed the record in your socket.io hand;er.  


```js
App.ApplicationAdapter = DS.RESTAdapter.extend({
  createRecord: function(store, type, record) {
    this._super.apply(arguments).then(function(json) {
      var record = store.getById(type, json.id);
      if (record) {
        record.unload();
      }
      return json;
    });
  }
});
```

**Comment by sandstrom** [comment] 2015-03-25 09:05
Probably a duplicate of https://github.com/emberjs/data/issues/1829 (I'd say close this issue in favour of the existing one).

More details:
- https://github.com/emberjs/data/issues/1829#issuecomment-42551445
- https://github.com/json-api/json-api/issues/202

**Comment by wecc** [comment] 2015-06-02 20:20
Closing as a duplicate of #1829

**Closed by wecc** 2015-06-02 20:20 UTC
Labels: Bug
