### ISSUE TITLE
Ember model.changedAttributes for unsaved record is not giving the default value.

### ISSUE THREAD

**Issue by akila1996** [emberjs/data#4294] opened 2016-04-01 07:14 UTC
For an unsaved record with changed attributes , when used model.changedAttributes, the object returns the old value as undefined. Instead the old value should be the default value.

Hers is an example of the scenario.
https://ember-twiddle.com/?openFiles=controllers.application.js%2C

**Comment by pangratz** [comment] 2016-04-01 07:18
Oops, looks like you forgot to save the twiddle. Be sure to login into ember-twiddle and save via `File -> Save to GitHub Gist`

**Comment by akila1996** [comment] 2016-04-01 07:20
I am really sorry. 

https://ember-twiddle.com/3708dd8efb25d6513f2125ef8b040b48?openFiles=controllers.application.js%2C

**Comment by pangratz** [comment] 2016-04-01 07:27
@akila1996 don't worry and no need to apologize :wink: 

I will take a look later but on a first sight this looks like a bug. Thanks for reporting!

**Comment by pangratz** [comment] 2016-04-01 11:04
Look related to #2566

**Comment by xomaczar** [comment] 2016-04-13 03:40
model.changedAttributes() diffs the "server state" of the model with its "local state". You've created a brand new record that hasn't been saved yet, so as far as ED is concerned all previous attrs are undefined.

The following sample produces similar behavior (not using defaultValue, just instantiating a person model with some default values):
```js
//models/person.js
export default DS.Model.extend({
  name: DS.attr('string')
});

//anywhere where store is present
let person = this.store.createRecord('person', { name: 'Joe Doe' });
person.set('name', 'Larry Smith');

person.changedAttributes(); // [undefined, 'Larry Smith'] 
```

**Comment by pangratz** [comment] 2016-04-13 06:39
@xomaczar you are absolutely right! Thanks for reminding me how it works :smile: 

I've created #4324 to clarify this in the documentation.

@akila1996 I am going to close this issue as it is actually not a bug...

**Closed by pangratz** 2016-04-13 06:39 UTC

**Comment by williamweckl** [comment] 2016-08-19 00:19
Is any way to get the behavior @xomaczar was expecting?

**Comment by xomaczar** [comment] 2016-08-19 01:28
I wasn't expecting anything different from what ED currently is doing - I was just trying to explain how it works currently and why.
@williamwecki what are you looking for?

**Comment by williamweckl** [comment] 2016-08-19 01:55
@xomaczar I'm quite new to ember and I'm looking for some function that identifies if the model was indeed changed.

I'm using the solution from [this post](https://emberigniter.com/saving-only-dirty-attributes/) to identify and only send to server the changed fields. 

In my example:
```javascript
model.save().then(function() {
  model.set('name', null); //clear the form
});
```

After that, if the user fill again the form with the same info, `changedAttributes()` is empty.

My goal is just clear the data after the form is sent but allow the user to send it again with the same info if he wants, and `changedAttributes()` does not do what I need. :(

Is a little confusing, so please let me know if I wasn't clear enough. 

Thanks.

**Comment by xomaczar** [comment] 2016-08-19 02:30
@williamweckl changedAttributes() worked as expected. When you reset the name to null, right after you saved it, ED marks that model instance as dirty, if your user types the same value for the name - changedAttributes will not include that attr as part of changed attributes - because the canonical (a.k.a server state) of the model.name === local state of that model.name. I hope this makes sense.
As for your use case/feature, I need more info or better a twiddle.com with an example or an animated gif - it's hard to visualize why you are setting a model's name to null right after you pushed it to the server. Would that not confuse your users who just typed 'Bob' into name field and hit a 'save' button to see a blank name? Surely not. Most likely I am not understanding the user flow you are trying to implement. Are you on slack - maybe we can move this conversion over there?
