### ISSUE TITLE
deleteRecord() on Polymorphic model with isNew status does not delete such record properly

### ISSUE THREAD

**Issue by Sinled** [emberjs/data#4434] opened 2016-06-18 13:22 UTC
[here is example on twiddle](https://ember-twiddle.com/ab180cffeddeda454721f8a7d489ed96?openFiles=templates.application.hbs%2C)

newly created polymorphic record cannot be deleted, 
on calling `deleteRecord` it changes is status to `isNew: false` and sits in parent relation.
Also it is not possible to call `rallbackAttributes` on such record.

**Normal** records works as expected.

Tried on 2.6.0, latest beta and canary versions of Ember Data.

Am i missing something or is it a bug?

Edited: `unloadRecord` also isn't working on newly created polymorphic model;

**Comment by backspace** [comment] 2016-06-27 00:50
Hey, @Sinled, thanks for writing in about this.

I created a [Twiddle](https://ember-twiddle.com/975a2f32ad52779bb8c0dbe7995406ec?openFiles=tests.acceptance.polymorphic-model-test.js%2C) with an acceptance test that demonstrates this problem, using truly polymorphic models and a more real-world object model. It’s beyond me to actually try to fix this bug, but hopefully this makes it more clear for the Ember Data gods!

CC @mixonic

**Comment by pangratz** [comment] 2016-08-17 10:44
I tried to tackle this and I can't reproduce this is a local test. Can you folks take a look at [this test](https://github.com/pangratz/data/blob/fix-4434/tests/integration/polymorphic-has-many-test.js) and spot any differences to your use case? Currently the test is not failing and I don't spot any differences to the twiddle you posted @backspace 😔

**Comment by backspace** [comment] 2016-08-17 17:09
hmm, I can’t see differences either. I tried changing the Ember Data version in the twiddle in case it had maybe been fixed somehow, but it was still failing on `2.8.0-beta.1`. For whatever reason, `2.8.0-beta.2` wouldn’t work, but it doesn’t seem like that would have fixed it.

**Comment by wecc** [comment] 2016-10-21 13:34
Were we able to reproduce this issue?

**Comment by Sinled** [comment] 2017-02-24 16:47
Sorry for the late reply,

I Still have this issue with the latest ember data (2.11.0),

created a small example on [twiddle](https://ember-twiddle.com/c602826395610b6245cd4e9147380831?openFiles=templates.application.hbs%2C)

**Comment by runspired** [comment] 2018-08-28 16:49
@Sinled Unless I'm missing something, your twiddle does not reproduce the bug even in 2.11.0. Closing for now but happy to re-open if I've missed something.

**Closed by runspired** 2018-08-28 16:49 UTC
Labels: Needs Bug Verification, polymorphism
