### ISSUE TITLE
RESTSerializer.pushPayload does not allow sideloading of records

### ISSUE THREAD

**Issue by amk221** [emberjs/data#3090] opened 2015-05-22 15:44 UTC
Given a payload like:

```
{
     posts: [{}]
     _posts: [{}, {}]
}
```

I get this warning:
WARNING: Encountered "_posts" in payload, but no model was found for model name "-post" (resolved model name using blah@serializer:post:.typeForRoot("_posts"))

1.0.0-beta.18

**Comment by fivetanley** [comment] 2015-05-22 21:25
You should remove the underscore in the payload or override `modelNameFromPayloadKey` (we need to update the message it looks like).

Ember.String.pluralize('foo') == 'foos'.

**Comment by amk221** [comment] 2015-05-22 22:01
Ah thanks! I thought the underscore prefix was and ember data convention. Perhaps not :)

**Comment by amk221** [comment] 2015-05-26 15:54
Quote from this page:
https://github.com/emberjs/data/blob/master/CHANGELOG.md#ember-data-100-beta3-september-28-2013

"Support primary and sideloaded data of the same type to be returned from array lookups (via posts and _posts)."

Therefore, this looks like a regression?

**Comment by wecc** [comment] 2015-05-26 17:17
@amk221 You are correct. Sideloading secondary records of the same type as primary is supported in `RESTSerializer`s `extractArray` using `_type` as key.

However, I'm unable to reproduce the error, see http://emberjs.jsbin.com/riyevivoxi/1/edit

Would you be able to provide a JSBin demonstrating the error?

**Comment by amk221** [comment] 2015-05-27 08:26
Ah, you're [right](http://jsfiddle.net/amk221/1etc61h1/)

Put that exact same code in a fresh ember-cli project and it doesn't work

**Comment by amk221** [comment] 2015-09-22 12:39
I closed this a while ago, but realised it's still an issue.

In a jsbin/fiddle/twiddle:

    store.modelFactoryFor('post') // function .Post
    store.modelFactoryFor('_post') // function .Post

In an ember-cli app

    store.modelFactoryFor('post') // function my-app@model:post:
    store.modelFactoryFor('_post') // undefined

**Comment by wecc** [comment] 2015-09-22 12:43
This seem unrelated since the RESTSerializer [removes](https://github.com/emberjs/data/blob/v2.0.1/packages/ember-data/lib/serializers/rest-serializer.js#L227) the prefixing `_` when sideloading resources of the same type as the primary.

When does `store.modelFactoryFor('_post')` occur?

**Comment by amk221** [comment] 2015-09-22 12:50
for (var prop in payload) {  // prop = '_post'
          var modelName = this.modelNameFromPayloadKey(prop); // modelName = '-post'
          if (!store.modelFactoryFor(modelName)) {  // modelFactoryFor('-post')
            Ember.warn(...
    // ...

It's checking for the dash rather than an underscore?

**Comment by wecc** [comment] 2015-09-22 12:53
can you link to that code?

**Comment by amk221** [comment] 2015-09-22 12:55
Ah, sure: [rest-serializer.js](https://github.com/emberjs/data/blob/734527866beadeeeabd693f5a75009e1251e896a/packages/ember-data/lib/serializers/rest-serializer.js#L346)

**Comment by wecc** [comment] 2015-09-22 12:57
Ah, `pushPayload()`... hm, seems the behavior in `pushPayload()` and `normalizeResponse` is a bit different. I can see why you'd expect them both to accept the same payloads even though it doesn't really matter to have records of the same type in a separate key for `pushPayload()` since it doesn't return anything.

**Comment by amk221** [comment] 2015-09-22 12:59
It was the same reason I mentioned in Slack earlier that if you manually `pushPayload` it complains when `meta` is present (tries to load a model named `metum`)

**Comment by wecc** [comment] 2016-01-06 18:41
We discussed this issue at today's meeting and I'll have a look at this and see if/how we can implement this in a backwards compatible way. Should probably not be that hard.

> Essentially I was expecting pushPayload to be able to accept the exact same structure that would have been loaded had I used findAll.

:+1:

**Comment by wecc** [comment] 2016-10-22 14:20
@pangratz Would this be covered by https://github.com/emberjs/rfcs/pull/161?

**Comment by pangratz** [comment] 2016-10-23 09:43
That RFC doesn't explicitly handle the inconsistencies between `pushPayload` and `normalizeResponse` in the `rest` serializer and also doesn't explicitly state the behavioral differences between `normalizeResponse` and `pushPayload`.

So I tend to think that this is a bug in `rest` serializer, which could be fixed in the short term by adding logic for keys starting with `_` in `pushPayload`. In the long term we should evaluate merging the logic within `normalizeResponse` and `pushPayload` of the `rest` serializer, like we already do in the `json-api` serializer.

**Comment by runspired** [comment] 2018-11-16 22:02
@amk221 I would recommend against using `pushPayload` in general. If you have a moment to work on an RFC: https://github.com/emberjs/rfcs/issues/357

**Comment by runspired** [comment] 2018-11-16 22:03
Closing, as making changes to `pushPayload` is not something we desire to do, and because `pushPayload` requires too much "special sauce" and "magical format knowledge" as it is.

**Closed by runspired** 2018-11-16 22:03 UTC

**Comment by amk221** [comment] 2018-11-17 07:56
Oh dear. Does this mean I should be phasing this out of my app? If so, what
would I replace it with? Thanks
