### ISSUE TITLE
beforeModel - "Attempted to handle event `reloadRecord` on ... while in state root.loading. 

### ISSUE THREAD

**Issue by svox1** [emberjs/data#2989] opened 2015-04-11 00:17 UTC
Ember-cli 0.2.3
Ember 1.12.0-beta.1
Ember data 1.0.0-beta.15, 1.0.0-beta.16.1

```javascript
beforeModel: function(transition) {
    return this.store.fetchById('myModel', 1).then(
        (data) => {
            console.log('OK', data);
        },
        (error) => {
            console.log('Error', error);
        }
    );
},

model: function(params) {
    return this.store.fetchById('indexModel', 1);
}
````
On first transition into this route, everything works fine.

But if I change the transition to a other route and go back to this route, I always get the error:
**"Attempted to handle event `reloadRecord` on <project@model:my-model::ember436:1> while in state root.loading. Called with function resolvePromise(value){**

If I remove the model call within beforeModel, everything works.

I have try to get the current Object and check if its dirty:
```javascript
var model = this.store.getById('myModel', 1);
model.get('isValid') => true
model.get('isError') => false
```
but it was valid and has no errors.

But what did I do wrong? Or is it a bug?

**Comment by igorT** [comment] 2015-04-12 05:06
Hi, this shouldn't be happening, can you maybe post a jsbin reproducing the issue ping me on IRC, would be happy to take a look. Also, you probably want to be using find instead of fetch, unless you really want to fetch the record every time

**Comment by svox1** [comment] 2015-04-12 11:59
Strange think. I cant reproduce it right now. I have still a error on this behavior but with a different problem. 

You can reproduce it with same snippet code above. But on `myModel` you have to response with httpstatus 204 (no content). If I have this and come back to the route, I get every time **Assertion Failed: You made a request for a gameStatus with id 1, but the adapter's response did not have any data** but in Charles Web Proxy I didnt see any request to the backend.

If `myModel` has a result on the first request, I can change the transition and come back and have every time a request to myModel (with 204 status) is called.

So the problem seems to be if the first request thrown a 204.

>> Also, you probably want to be using find instead of fetch, unless you really want to fetch the record every time.
I really want to reload it on every request.

I edit the jsbin:
http://jsbin.com/pipixetoya/1/edit?html,js,output

On the first request we can see:
MOCK GET: /cars/1 Object {url: "/cars/1", type: "GET", isLocal: false, global: true, processData: true…}
Error Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
MOCK GET: /authors/1 Object {url: "/authors/1", type: "GET", isLocal: false, global: true, processData: true…}

Then click to Info and then index:
Error Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
runner-3.25.22.min.js:1 
MOCK GET: /authors/1 Object {url: "/authors/1", type: "GET", isLocal: false, global: true, processData: true…}

... we get an error before a request to the backend is called.

**Comment by jcope2013** [comment] 2015-04-12 18:30
the second issue sounds like https://github.com/emberjs/data/issues/2975, I was getting an error before the request to the backend is called also

**Comment by fivetanley** [comment] 2016-01-16 05:20
Since it seems like it is fixed and the other issue is closed, I'm inclined to close this issue. Please feel free to open a new issue if you think this is still a problem.

**Closed by fivetanley** 2016-01-16 05:20 UTC
