### ISSUE TITLE
Find with 302 redirect leaks record, Location header ignored

### ISSUE THREAD

**Issue by drauschenbach** [emberjs/data#4677] opened 2016-11-22 14:44 UTC
This common ember-simple-auth pattern leaks a record:

```
export default Ember.Route.extend(AuthenticatedRouteMixin, {
  model() {
    return this.get('store').find('user', 'me')
  }
}
```

Server responds with:

```
302 Found
Location: /v1/users/123
```

Ember Inspector then shows two models, one with id `me` and a 2nd with id `123`. I'm using JSONAPI and I think the adapter is ignoring Location headers in responses.

**Comment by wecc** [comment] 2016-11-22 14:48
By using `findRecord('user', 'me')` Ember Data is expecting the ID to be `me` and when `123` is returned it's considered another record. If the ID is unknown you should be able to use [`queryRecord()`](http://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord) instead.

**Comment by acorncom** [comment] 2017-08-10 11:06
Looks like this issue can be closed

**Comment by pangratz** [comment] 2017-10-06 21:46
Thanks @acorncom, closing. @drauschenbach feel free to reopen if you still run into an issue, but as @wecc pointed out, this is the expected behaviour.

**Closed by pangratz** 2017-10-06 21:46 UTC
Labels: Needs Bug Verification
