### ISSUE TITLE
Links related relationship on modelA nulls belongsTo on modelB

### ISSUE THREAD

**Issue by DingoEatingFuzz** [emberjs/data#5209] opened 2017-10-05 18:29 UTC
### Data Model

1. modelA has a `hasMany('modelB')`
2. modelB has a `belongsTo('modelA')`
3. modelB payload looks like this: `model_a_id: 'model-a-1'`
4. modelA payload does not include the set of modelB ids. Instead, it is related through a related link: `/api/model-a/:id` returns the model and `/api/model-a/:id/model-b` returns the set of related modelB.

### Steps to reproduce

1. Find a modelB
2. Do not find the modelB's modelA
3. Find modelB's modelA independently
4. Observe that `modelB.get('modelA')` is a fulfilled promise with `null` for content

### Expected result

modelB should maintain its relationship with modelA despite modelA being loaded with unknown IDs for its hasMany modelB.

### Actual result

The relationship is null and the original ID from the payload is now lost.

### Notes

This _only_ happens in this order. If modelB's modelA is already loaded, it seems to be fine.

**Comment by pangratz** [comment] 2017-10-05 20:27
Can you update [this ember-twiddle](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) so it demonstrates the issue you're having? That would help greatly track down the issue your having! Thanks!

**Comment by lolmaus** [comment] 2017-10-06 12:51
I've filed a very similar issue: #5211, it's either related or duplicated. I've provided a reproduction twiddle.

**Comment by williamhector** [comment] 2017-10-10 05:41
Here is a twiddle that I believe is the same issue as the OP:
https://ember-twiddle.com/2cf56ec2cd082d5c5a109e51993de730?openFiles=adapters.organisation.js%2C

The application route loads a given user, loads a given organisation, then loads the user's organisation (should be the same as the given org).
The organisation's users relationship (adminUsers) is never loaded, so while it might be related, I believe it's not a duplicate.

If you omit the "links" from the payload in `adapters/organisation.js`, the issue doesn't occur.
Or, if you call `user.get('organisation')` before `store.findRecord('organisation', id)` in `routes/application.js` then the issue doesn't occur.

**Comment by BryanCrotaz** [comment] 2017-11-08 16:40
I can confirm this behaviour in a real world app

**Comment by BryanCrotaz** [comment] 2017-11-11 13:54
I'm working on a PR

**Comment by BryanCrotaz** [comment] 2017-11-11 14:58
I have a failing test based on @williamhector 's twiddle...

**Comment by BryanCrotaz** [comment] 2017-11-12 02:08
Found the problem - the payload data is cached until you read the relationship. Because you've not defined the inverse on one side, the second one is stomping on it - we need to merge the pending data when defining the second end of the relationship.
Working on it

**Comment by BryanCrotaz** [comment] 2017-11-12 17:32
Fixed in #5257

**Comment by bmac** [comment] 2018-03-05 14:41
I believe this has been fixed by https://github.com/emberjs/data/pull/5230. Feel free to reopen if it is still an issue.

**Closed by bmac** 2018-03-05 14:41 UTC
