### ISSUE TITLE
beta.19 regression: fetchById not saving model to the store

### ISSUE THREAD

**Issue by cdoornink** [emberjs/data#3277] opened 2015-06-09 18:36 UTC
I have a partial model returned as part of a relationship. When I want to view that model I check to see if it’s data is fully loaded. If it is I return a .find in the route. If it is not, I return .fetchById so that it will request the full model from the server.

This used to replace the existing partial model that was there, but in beta.19 it does not replace it. This means that every time I go to view that full model it is requesting the model from the server and the instances of the model on the site are out of sync.

**Comment by igorT** [comment] 2015-06-09 20:39
Can you reproduce the issue in a test or jsbin please?

**Comment by cdoornink** [comment] 2015-06-09 20:50
The issue was using `store:main` instead of `store:application`. It was being injected into a service like this:

`app.inject('service:playback', 'store', 'store:main');`

Also was being called from the container as store:main in a few places. There weren't any deprecation warnings for any of the cases.

**Comment by cdoornink** [comment] 2015-06-09 21:25
@bmac I also had to move `app/store.js` to `app/application/store.js` after I made the `store:application` changes. Otherwise it could no longer find the method that I was defining when I reopened the DS.Store.

I'm assuming this related the other issue I reported here last week. #3239

**Comment by bmac** [comment] 2015-06-09 21:27
@cdoornink You are correct. Sorry this upgrade has been so painful. I'm working on a pr to give better warnings around this stuff which hopefully can be released as a beta-19.2. Thanks for reporting the issue!

**Comment by cdoornink** [comment] 2015-06-09 21:34
@bmac No problem, thank you!

**Comment by bmac** [comment] 2015-06-12 21:24
Closing as a duplicate of https://github.com/emberjs/data/issues/3239. For anyone else who comes across this issue. It has been fixed and included in `Ember Data beta-19.2`.

**Closed by bmac** 2015-06-12 21:24 UTC
