### ISSUE TITLE
belongsTo property has no id after GET request is rejected

### ISSUE THREAD

**Issue by nag5000** [emberjs/data#7632] opened 2021-07-09 12:57 UTC
### Description

```
// RESTAdapter is used
export default class MyModel extends Model {
  @belongsTo('foo', { async: true }) foo;
}

const myModel = loadMyModel(); // myModel is loaded, myModel.foo is not loaded.
myModel.belongsTo('foo').id() // 99
Ember.get(myModel, 'foo.id'); // logs 99 and initiates 'foo' loading
...
// Backend rejects the request `/api/foos/99` with 403.
...
Ember.get(myModel, 'foo.id'); // logs undefined <----------------- expected 99.
myModel.belongsTo('foo').id() // 99
```

I'm not sure if it's a bug, but at least it's very strange.

### Versions

ember-data 3.24.0

**Comment by snewcomer** [comment] 2021-09-19 03:58
@nag5000 Is this something you would be interested in pushing a PR with a test indicating your issue?  That way we can prioritize a fix.

**Comment by nag5000** [comment] 2021-09-19 10:35
@snewcomer Yup, just added.

**Comment by snewcomer** [comment] 2021-10-20 02:44
@nag5000 Thank you for the test.  So this isn't expected from the point of view of a the ember primitives - ObjectProxy and PromiseProxyMixin.  However, in the comments in the code below...

> when a load fails, in this case we need to make sure that we aren't proxying to destroyed content

https://github.com/emberjs/data/blob/9889ebbd4eec162dba17bb00126ee71e49d04bce/packages/store/addon/-private/system/model/internal-model.ts#L1396-L1407

This is unavoidable.  Unless you are able to convert to non async relationships. Seems this issues occurs if we were to revert null'ing out the `content` of the proxy after an error.

https://github.com/emberjs/data/issues/5814

**Comment by runspired** [comment] 2021-12-15 09:22
I'm not sure this should be closed, so I'm reopening it. While the current behavior is indeed intended, it's open for discussion whether there isn't a better way to handle this case (where we know the id, but for unknown reasons the API request is failing). Potentially we can enter a recoverable error state here.

**Comment by runspired** [comment] 2023-09-10 09:23
closing as a duplicate of #5229

**Closed by runspired** 2023-09-10 09:23 UTC
Labels: Needs Team Discussion
