### ISSUE TITLE
Record not found handling for belongsTo relationships

### ISSUE THREAD

**Issue by jaaksarv** [emberjs/data#1810] opened 2014-03-15 20:25 UTC
Ember-Data doesn't seem to have any proper error handling mechanism for cases where record is not found. This creates problems for me for belongsTo relationships where a record is deleted, but relationship foreign keys referencing to that record are not updated (or not updated yet). In this case Ember-Data creates an empty record with only ID set. Because of this empty records began to show up in application and there are lot of hard to debug bugs. 

I initially created StackOverflow question for this, but for me this seems to be a bug (or at least a feature request). Longer description can be found there.
http://stackoverflow.com/questions/22411391/how-to-handle-not-found-errors-for-belongsto-relationship-in-ember-data

Also created JSBin for this:
http://emberjs.jsbin.com/guxedihi/2/

Any hints how to solve this temporarily until better solution comes up are welcome.

**Comment by wecc** [comment] 2015-09-16 18:05
I tried to replicate your issue in a new JSBin with Ember and Ember Data 1.13. Looks like ED will correctly update both sides of the record if you server responds with a 404. See http://emberjs.jsbin.com/kiriyaleju/edit?html,js,output

**Comment by wecc** [comment] 2015-10-12 19:14
Closing. Feel free to open if issue is still reproducible.

**Closed by wecc** 2015-10-12 19:14 UTC
Labels: Review for 1.0

**Comment by JohnQuaresma** [comment] 2015-10-12 23:45
I'm still having this problem, and I'm on Ember Data 1.13.8 - I have a top level application adapter, which handles an error response when the server returns 404.  I've seen no magical updates to either model when the server returns a 404 for belongsTo.  All I get are errors.

**Comment by bmac** [comment] 2015-10-13 10:14
@JohnQuaresma Would you mind reproducing your issue in a jsbin?

**Comment by olivierchatry** [comment] 2017-09-18 12:09
I understand the need of repro case, but here it is actually quite easy to understand, and it is also very annoying. 

Basically if you let say you have something like this : 
```

**Comment by olivierchatry** [comment] 2017-09-18 12:17
I understand the need of repro case, but here it is actually quite easy to understand, and it is also very annoying.

Basically if you let say you have something like this :
```
// project.js
export default DS.Model.extend({
	entries : DS.hasMany("entry")
))

// entry.js
export default DS.Model.extend({
	project : DS.belongsTo("project")
))
```

Says you create a project :
```
// whatever place
const project = this.store.createRecord("project")
const created = []

for (let i = 0; i < 10; ++i) {
	created.push(
		this.store.createRecord({
			project
		})
	)
}

project.get("entries").pushObjects(created)

RSVP.all(created.invoke("save")).then(
	() => project.save()
)
```

If for any reason, and since there is no transaction support, one of the entry fails to actually save, then your project is screwed because findRecord will fails next time you load the data. You will end up with an error and the user will have no way to see it data.

Note that for me it never happen during a save, but during a deletion, where user delete an entry, but for some reason it does not get save to the db, and so I have to cleanup the Db. 

I endedup doing something I really dislike :
```
