### ISSUE TITLE
Returning DS.InvalidError from DS.ActiveModelAdapter#handleResponse doesn't work

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/data#3524] opened 2015-07-09 20:45 UTC
I'm on Ember 1.13.2, Ember-Data 1.13.4. [JSBin](http://emberjs.jsbin.com/tumijo/2/edit)

The [`RESTAdapter#handleResponse` docs](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_handleResponse) state,

> Returning a DS.InvalidError from this method will cause the record to transition into the invalid state and make the errors object available on the record.

That does not seem to be true.

I have an `adapter:application` that looks like
```js
import DS from "ember-data";

export default DS.ActiveModelAdapter.extend({
  handleResponse(status, headers, payload) {
    if (status >= 400 && status < 500 && payload.msg) {
      return new DS.InvalidError([
        { detail: payload.msg }
      ]);
    }

    return this._super(status, headers, payload);
  }
});
```
In the following code
```js
someModel.save()
  .catch((error) => {
    console.log('msg', Ember.get(error, 'errors.0.detail'));
    console.log('isSaving', someModel.get('isSaving'));
    console.log('isValid', someModel.get('isValid'));
    console.log('model.errors.length', someModel.get('errors.length'));
});
```
The `msg` prints correctly, but the model is still saving, is still valid, and has 0 errors.

**Comment by jamesarosen** [comment] 2015-07-09 20:46
Since the API in question only returns
```json
{ "msg": "I'm sorry, Dave, I can't do that." }
```
I don't have any more information to feed into the error objects. It's possible that is the source of the problem.

**Comment by tchak** [comment] 2015-07-12 10:04
@jamesarosen yes the problem is absence of `source`... I agree this is not optimal. How you were dealing with this before 1.13? Problem should have been the same, unless you were adding errors to some arbitrary attribute (like `base`).

**Comment by tchak** [comment] 2015-07-12 11:28
@jamesarosen to be clear, I agree this is a bug. I am just trying to understand how and if behavior have changed.

**Comment by jaswilli** [comment] 2015-07-12 13:23
I'm seeing this regression using the RESTAdapter/Serializers as well.  My API is returning status 422 with an errors payload that looks like `{ errors: [Object, Object] }`.  `handleResponse` is correctly returning an `InvalidError` but like @jamesarosen, my model stays in state `isSaving` and `isValid`.

Pre-1.13, the behavior would have been `isSaving` back to false, `isError` true.

**Comment by jamesarosen** [comment] 2015-07-12 14:35
In the betas, the promise would reject with the XHR response, so I had direct access to the body.

**Comment by tchak** [comment] 2015-07-12 22:39
I see what is happening here. The full story:
In the early versions on ember data we introduced errors handling based on rails convention, 422 status code with the response `{ errors: { name: 'error message'} }`. Later on we split rails specific behavior in `ActiveModelAdapter/ActiveModelSerializer`. Default behavior for plain `RESTAdapter` was newer specified. I suspect we still had some part of rails behavior baked in. Along the route we introduced what some would call a bug and some would call a resilient behavior. If no `errors` hash was present on the root level of the response we used root level hash as errors hash. This explains @jamesarosen example. `{msg: 'error message'}` was interpreted and exposed on the model as `errors.msg` -> 'error message'.

New `RESTAdapter` uses JSON-API semantics, but still have a legacy handler to parse rails like invalid errors.

In the end it all boils down to the fact that if JSON-API error have no `source` attribute we fail to add invalid errors. I suspect this is something that was true before 1.13 changes. If `DS.InvalidError` payload had nothing that could be mapped to attribute:error pair it was always resulting in the broken behavior described in this issue.

I see two solutions here:
- use a default source.
- assert for invalid errors without source attribute

**Comment by jamesarosen** [comment] 2015-07-12 22:54
JSON:API says that source is optional, which suggests there is some semantic meaning of a source-less error. This I vote against requiring it. And I'm for any default implementation that lets me understand there was no source -- for example, to show source-less errors at the top of a form, but others inline.

**Comment by jamesarosen** [comment] 2015-07-12 22:55
Though I guess the "source-less" marker could be up to my app -- which suggests that requiring a source could work, though it's not exactly per spec.

**Comment by tchak** [comment] 2015-07-12 23:01
@jamesarosen when I am saying default "source" I only mean that we need a "name" to put the message in the `model.errors` object. I also probably prefer this than forcing on source from the api.

**Comment by jamesarosen** [comment] 2015-07-12 23:10
> I only mean that we need a "name" to put the message in the model.errors

```js
// lib/adapters/errors.js
new DS.InvalidError([
  {
    detail: 'Must be unique',
    source: { pointer: 'data/attributes/title' }
  }
]);

// lib/system/model/errors.js
{
  "errors": {
    "username": ["This username is already taken!"],
    "email": ["Doesn't look like a valid email."]
  }
}
```

So you just mean `model.errors` might look something like
```js
{
  "__NO_SOURCE__": [ "Something went wrong." ]
}
```

**Comment by tchak** [comment] 2015-07-12 23:28
yes

**Comment by tchak** [comment] 2015-07-18 18:29
I am thinking adding `baseErrorKey` property on serializer and use it in `extractErrors` when building hash of errors in case `source.pointer` is not defined. If anyone have a better suggestion for the property name I am all ears. The default would be `base`. Again I am open to suggestions.

@igorT @fivetanley any objections?

**Comment by tchak** [comment] 2015-10-15 13:26
should be fixed by #3859

**Comment by tchak** [comment] 2015-10-15 21:34
So, #3859 is half fixing it. I mean, at least the record is going in to invalid state. Still no handling for pointer-less errors. Will comme in a future PR.

**Comment by fivetanley** [comment] 2016-01-16 06:12
closed by https://github.com/emberjs/data/pull/3859 i think, if it's still an issue it'll need to be opened on the ActiveModelAdapter repo. https://github.com/ember-data/active-model-adapter

**Closed by fivetanley** 2016-01-16 06:12 UTC
