### ISSUE TITLE
Model property stays dirty

### ISSUE THREAD

**Issue by wouterbin** [emberjs/data#7751] opened 2021-11-10 15:19 UTC
### Reproduction

Please see [this](https://ember-twiddle.com/c8c111b6cb93ef77e5090eddd89fdebe) twiddle for reproducing this issue.

### Description

I am struggling with some strange, for me unexpected behavior. I have a `UserModel` with a property `name` which is not defined. When it is bound to an input and it changes it never gets rid of `hasDirtyAttributes` true state.

Steps to reproduce:
- Enter a character in the input box
- You will notice the "Model has changed"
- Hit backspace to erase the entered character

Now the `model.hasDirtyAttributes` property keeps true while I would expect it to be false. I realized that could be because the value was `undefined` and it became `''`. So I added `defaultValue: ''` to the name `attr` in the `UserModel`. But that did not fix it.

In the twiddle i added a computed property which logs to the console. The strange thing I noticed there is that the first item in the array returned by `changedAttributes` is always `undefined`.

Is this a bug or a feature? And if its a feature how can I get rid of the dirty state?

### Versions

(output twiddle console)
Ember      : 3.18.1
Ember Data : 3.18.0 
jQuery     : 3.5.1

**Comment by btecu** [comment] 2021-11-15 03:47
@wouterbin you are on the right track, you just have a typo, `defaultvalue` -> `defaultValue`.

**Comment by wouterbin** [comment] 2021-11-15 13:52
Thank you for your reply @btecu. Yes, that's a silly mistake I made :blush: . But changing it to `defaultValue` does not change the unexpected behavior unfortunately.

Probably it is just the lack of understanding from my side. But IMO is seems pretty straight forward what I try to accomplish :sweat_smile:

**Comment by runspired** [comment] 2021-12-13 21:42
changing it from `undefined` to `''` even when `''` is the defaultValue does constitute a change since the dirty checking is a simple referential check. You'd want to set it back to undefined to have it be clean, or have the API/serializer set it to be an empty string in the first place.

**Comment by runspired** [comment] 2022-02-11 04:44
closing as duplicate of #1540

**Closed by runspired** 2022-02-11 04:44 UTC
