### ISSUE TITLE
3.5 Regression with Subclassed Models and hasMany 

### ISSUE THREAD

**Issue by thec0keman** [emberjs/data#6039] opened 2019-04-18 20:42 UTC
In the following situation:
- a model (`Session`) subclasses another model (`User`)
- `User` has a `hasMany` that is side-loaded: 
```
locations: hasMany('location', { async: false })
```
- there is an inverse `belongsTo` for `User`
```
user: belongsTo('user')
```
- the JSON from the server includes a foreign key for the superclass (e.g. `user_id`)

Fetching a `Session` works great.  However, when you save a `Session`, even if the server returns an identical payload to the fetch, the `hasMany` association is cleared out.

For example:
```
const session = await this.store.findRecord('session', 1);

session.get('locations.length');
// => 3

// (Assuming server sends back same data)
await session.save();  

session.get('locations.length');
// => 0
```

This works on Ember Data 3.4, breaks on 3.5, and confirmed also not working on 3.7, 3.8, and 3.9.

(We are also using active-model-adapter, but this does not seem to be related)

[Reproduction](https://github.com/thec0keman/ember-data-relationship-bug)

**Comment by runspired** [comment] 2019-04-20 01:28
@thec0keman the reproduction seems to be missing the payloads involved in the network requests.

**Comment by thec0keman** [comment] 2019-04-20 03:50
We'll give that a shot, thanks!

I think our surprise was more because we thought that the `location_ids` on the session / user would determine the relationship.  Our short-term solution was to move the shared code into a mixin, since that was the reason for the subclassing.

This also revealed we had code that looked up a `user` from a `location` (hasMany -> super class), but that code also was being used for a `session` (subclass) as well.  I would not have expected that to work on any version!

**Comment by runspired** [comment] 2019-04-23 17:42
@thec0keman did using `inverse: null` resolve things?

**Comment by runspired** [comment] 2019-11-26 22:40
Closing as this was a regression in unintended usage with a resolution

**Closed by runspired** 2019-11-26 22:40 UTC
