### ISSUE TITLE
ds-references relationshipReference.load() not retrieving data

### ISSUE THREAD

**Issue by funktr0n** [emberjs/data#4359] opened 2016-04-27 22:14 UTC
So I'm trying to use the new "references API" as outlined [here](http://emberjs.com/blog/2016/03/13/ember-data-2-4-released.html#toc_code-ds-references-code) (my understanding is that this is enabled in Ember Data 2.5.2), but when I attempt to run through the given example, relationshipReference.load() doesn't retrieve any of the unloaded (not cached) data.  Upon inspection with Chrome's Developer Tools, the call to load() doesn't even make a network call.

Example:

```
var profileId = 1;
var peekProfile = this.store.peekRecord('profile', profileId);

console.log(peekProfile);  // returns record
console.log(peekProfile.hasMany('projects').value()); // returns null

peekProfile.hasMany('projects').load().then(function() {
  console.log(peekProfile.hasMany('projects').value()); //still returns null, no network call made
});
```

Any ideas?

**Comment by pangratz** [comment] 2016-04-27 22:42
Looking at the code you provided, this should work. Can you provide a failing ember twiddle, demonstrating the issue? This would greatly help identifying this issue. You can use [this](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) as a starting point.

**Comment by pangratz** [comment] 2016-04-27 22:44
Also, what are the values of `peekProfile.hasMany('projects').ids()` and `peekProfile.hasMany('projects').remoteType()`?

**Comment by pangratz** [comment] 2016-04-28 19:32
I can reproduce the issue you're having when the hasMany relationship has no data (no ids and no links), see [this twiddle](https://ember-twiddle.com/11d10e21272caa0927cdd24487813e56?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cmodels.person.js).

@funktr0n can you take a look and check if this is the issue you're running into?

**Comment by funktr0n** [comment] 2016-04-28 21:11
@pangratz 

Yes, after a lot of testing this afternoon, it does seem that this is the cause of the issue.  When the returned record doesn't have relationship data included, the load function returns successfully but without actually attempting to make a call.

Are you planning on altering the behavior at all?  I'm currently not returning records with that basic relationship information included.

**Comment by kernel-io** [comment] 2016-05-01 14:38
@pangratz I am running into the same issue as well, I do not load the id's on every record as that would require an extra bunch of db calls, which are not needed, is it not possible to have an option that just reads the _id from the model?

i.e: I have a rostering application which will have thousands of related items, I do not see the logic in loading all the shifts per shift time, when I already have the relationship data on the shift object itself (shift_time_id)...

**Comment by pangratz** [comment] 2016-05-03 14:56
> @funktr0n wrote
>> I'm currently not returning records with that basic relationship information included.

How would you then want to get the records? What API call would you expected to see when you call `load()`? Could a link help in your situation?

> @kernel-io 
>> I do not load the id's on every record as that would require an extra bunch of db calls, which are not needed, is it not possible to have an option that just reads the _id from the model? ... I do not see the logic in loading all the shifts per shift time, when I already have the relationship data on the shift object itself (shift_time_id)

Can you provide some more code? I am afraid I am not fully following.

**Comment by fivetanley** [comment] 2016-05-09 14:17
@pangratz https://ember-twiddle.com/36b1361b68c2d31f2c2415a7452ecaf2?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cmodels.person.js

You were creating a new reference every time. I think the issue is that when I have a reference, and I call `load` on that reference, it should update. My updated twiddle reproduces the issue.

**Comment by pangratz** [comment] 2016-05-09 14:25
> You were creating a new reference every time.

It's always the same reference returned

> I think the issue is that when I have a reference, and I call load on that reference, it should update

As far as I can tell the issue here is that the relationship is neither defined as a link nor has it `ids`, so `reference.value()` doesn't know what to do and hence the value is `null` before and afterwards. What am I missing?

**Comment by fivetanley** [comment] 2016-05-09 14:43
Ah, I didn't notice the missing IDs. This works after I update pretender for that case: https://ember-twiddle.com/36b1361b68c2d31f2c2415a7452ecaf2?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cmodels.person.js

**Comment by pangratz** [comment] 2016-05-09 14:54
Currently I don't see this as a bug for the references, since there is not clear what `load()` should do. @fivetanley in case you agree, feel free to remove the `bug` label...

Where this case somehow leads to is something like #2168, where a hook has been proposed for such a case where a relationship is not yet defined.

**Comment by wecc** [comment] 2016-10-21 15:24
I'm closing this as I believe this is the expected behavior. If we have no `data` and no `links.related` for a relationship there's not really anything we can do to fetch the relationship.

**Closed by wecc** 2016-10-21 15:24 UTC
Labels: references
