### ISSUE TITLE
2.11 regression? Destroyed object reappears in hasMany collection after adding a new one

### ISSUE THREAD

**Issue by samcic** [emberjs/data#4770] opened 2017-01-25 12:35 UTC
It seems there might be a regression from 2.10 to 2.11. I did notice what seems to be a similar issue that's already been reported (https://github.com/emberjs/data/issues/4759), but I'm not sure it's exactly the same, so if it's ok here's a new one.

Twiddle:

https://ember-twiddle.com/13f0a4a3f9af52135283b2d057614510

Steps to reproduce:
* Make sure you have Ember-Data 'release' dependency selected (2.11).
* Open your browser console to watch the mockjax requests.
* Click on the 'Test persist' button. You'll see two children at the end: one with id 1 and another with id 2.
* Switch to Ember-Data version 2.10
* Click on the 'Test persist' button again. You'll see one child at the end, with id 2.

I also included a 'Test local' button which shows that the behavior is correct in 2.11 if no back-end calls are done.

Explanation:
* The testPersist action creates a parent object, adds a child to it (id 1), then deletes that child (id 1), then creates another child (id 2). I would expect that, at the end, the parent's collection only contains the child with id 2. In version 2.11 of Ember data it seems that both children are there at the end after the second is added. 

We noticed this when running our acceptance tests after upgrading our Ember stack to 2.11. This changed behavior results in rendering issues in our app (related to the fact that one of the objects is destroyed but is still being enumerated in the collection, i.e. the child with id 1 above).

**Comment by danielspaniel** [comment] 2017-01-25 13:23
I could only get this by using polymorphic models, but 
I have an even simpler test/example to show this bug in action:
 
https://ember-twiddle.com/26204b7fa7fc185dde464418cd33df95?openFiles=controllers.application.js%2C

**Comment by kbullaughey** [comment] 2017-01-28 16:04
It seems the deleted record in your twiddle is combing back into the many array [here](https://github.com/emberjs/data/blob/e5dac10e43f420bd3cd44e25f48b0295b93589fe/addon/-private/system/many-array.js#L162). 

It seems InternalModels that are in state `root.deleted.saved` are still in the `canonicalState` array. This any new records are added, and the array set as the value on the `currentState` property. This has the effect of bringing them back from the dead. What I don't know is whether it is a mistake that they're in the `canonicalState` array to begin with (i.e., should they have been removed upon delete?) or should they just be skipped when copying to `canonicalState`.

**Comment by danielspaniel** [comment] 2017-01-28 17:00
@kbullaughey , good find .  I also am not so familiar with internals either, that is why I am alittle bit hesitant to dig in and fix it since someone else who just worked on it might know exactly why this is happening and fix it in 2 mins. I guess that should not stop me but .. it does right now

**Comment by kbullaughey** [comment] 2017-01-29 00:14
I was not able to reproduce the problem as observed in my particular use case when using 2.13.0-canary (current master). I was able to cause the problem with 2.12.0-beta.1 (the most recent previous tag). Unfortunately loads of stuff has changed in InternalModel and other places, so it's not clear what may have fixed it. And when I switch your twiddle to Ember Data canary, it works as expected.

**Comment by runspired** [comment] 2017-02-01 06:18
Why this surfaced and why it's fixed on canary is basically "we had a bug we didn't know about that was covered up by other bad things we did, we removed those other bad things and slated this other good thing to land, the other good thing also addressed the root cause of the bug".

We can't easily backport the feature PR to 2.13 that addresses this, so I'm working on a fix I can backport for 2.11 and 2.12

**Comment by kbullaughey** [comment] 2017-02-01 14:31
Ah, great. Thanks for the explanation.

**Comment by runspired** [comment] 2017-02-03 20:50
Fixed by #4791 and #4792 with a failing test committed by #4790

**Comment by bmac** [comment] 2017-02-03 21:44
This is fixed by https://github.com/emberjs/data/pull/4791 and the fix was published in the Ember Data 2.11.1 release.

**Closed by bmac** 2017-02-03 21:44 UTC
