### ISSUE TITLE
Rendering async hasMany relationships

### ISSUE THREAD

**Issue by vluoto** [emberjs/data#2692] opened 2015-01-12 10:49 UTC
I've encountered a rather confusing error after upgrading ember-data to 1.0.0-beta.14 from 1.0.0-beta.12. From what I understand, the problem seems to have something to do with rendering async relationships. Unfortunately however, I wasn't able to reproduce the problem in [JS Bin](http://jsbin.com/qagurukazu/1/), but feel free to take a look at it anyway. I'm using Ember CLI 0.1.6 with Ember 1.9.1.

In my case I have projects that can have many repositories and the relationship in question is defined like so:
```
import DS from 'ember-data';

export default DS.Model.extend({
    repositories: DS.hasMany('repository', { async: true })
});
```

and my template uses the relationship like so:

```
<ul>
  {{#each repository in controller.repositories}}
    <li>
      {{#link-to 'company.project.repository' repository.id}}{{repository.id}}{{/link-to}}
    </li>
  {{/each}}
</ul>
```

This used to work just fine with 1.0.0-beta.12, but now it gives the following error:

```
TypeError: Cannot read property 'destroy' of undefined
    at ContainerView.extend.arrayWillChange (http://localhost:4200/assets/vendor.js:54059:20)
    at applyStr (http://localhost:4200/assets/vendor.js:33224:29)
    at sendEvent (http://localhost:4200/assets/vendor.js:27660:13)
    at __exports__.default.Mixin.create.arrayContentWillChange (http://localhost:4200/assets/vendor.js:43988:9)
    at EmberObject.extend.arrangedContentArrayWillChange (http://localhost:4200/assets/vendor.js:47855:14)
    at applyStr (http://localhost:4200/assets/vendor.js:33224:29)
    at sendEvent (http://localhost:4200/assets/vendor.js:27660:13)
    at __exports__.default.Mixin.create.arrayContentWillChange (http://localhost:4200/assets/vendor.js:43988:9)
    at Ember.Object.extend.flushCanonical (http://localhost:4200/assets/vendor.js:72292:14)
    at ember$data$lib$system$relationships$state$has_many$$ManyRelationship.flushCanonical (http://localhost:4200/assets/vendor.js:73997:22)
```

I'm having a hard time figuring out where it all could go wrong, so if anyone happens to know what has changed between beta 12 and beta 14 regarding this, I'd very much like to know. Alternatively, if someone knows where to start debugging the problem from, that'd be great as well.

Thanks.

**Comment by wecc** [comment] 2015-01-12 10:55
This looks like a duplicate of #2662

**Comment by vluoto** [comment] 2015-01-12 10:58
You're right, somehow managed to miss it.

**Comment by bmac** [comment] 2015-01-29 05:10
Closing this issue since its a duplicate. It should be fixed when https://github.com/emberjs/data/pull/2698 gets merged.

**Closed by bmac** 2015-01-29 05:10 UTC
