### ISSUE TITLE
Duplicate records when saving new embedded records

### ISSUE THREAD

**Issue by jakesjews** [emberjs/data#2850] opened 2015-03-10 15:01 UTC
When we save a new record with a new embedded record field in a hasMany relationship duplicate records are being created after the server responds with an embedded record with a non-null id.  So after the save, we have one version of the record with a null id, and another with the id from the server (they aren't being merged correctly).

This is issue is not present in beta 12.

A JS Bin replicating the issue can be found [here](http://jsbin.com/vejuha/2/edit)

**Comment by jnfisher** [comment] 2015-03-10 15:02
+1 I'm seeing the same problem since beta 14.

**Comment by yokree** [comment] 2015-03-11 21:06
+1

**Comment by jeanettehead** [comment] 2015-03-16 20:58
+1

**Comment by 20v100** [comment] 2015-03-16 21:13
+1

**Comment by wcurtis** [comment] 2015-03-24 20:24
+1 Issue still exists with beta 16

**Comment by sandstrom** [comment] 2015-03-25 09:04
Probably a duplicate of https://github.com/emberjs/data/issues/1829 (I'd say close this issue in favour of the existing one).

More details:
- https://github.com/emberjs/data/issues/1829#issuecomment-42551445
- https://github.com/json-api/json-api/issues/202

**Comment by edson-** [comment] 2015-03-27 19:24
From above: "This is issue is not present in beta 12."

I'm seeing this in beta 12 also.

**Comment by DanLeininger** [comment] 2015-03-31 16:19
+1

**Comment by ericop** [comment] 2015-04-15 21:04
+1

**Comment by abulrim** [comment] 2015-04-20 09:20
You can use this temporary solution:
```javascript
this.get('model').save().then(function(levelOne) {
  levelOne.get('levelTwo').filterBy('isNew').invoke('unloadRecord');
});
```

**Comment by Gowiem** [comment] 2015-04-27 14:43
+1 Just updated from beta-12 to beta-16.1 in an effort to get my Rails asset pipeline code on the same version of some new EmberCLI code and ran into this.

**Comment by WooDzu** [comment] 2015-05-09 15:27
@abulrim your workaround did the trick for me. Thanks!

**Comment by tamarasaurus** [comment] 2015-05-15 01:36
+1

**Comment by sdahlbac** [comment] 2015-06-01 11:05
+1 (the workaround by @abulrim works though)

**Comment by wecc** [comment] 2015-06-02 20:40
Closing as a duplicate of #1829. Please reopen if not.

**Closed by wecc** 2015-06-02 20:40 UTC
Labels: Bug
