### ISSUE TITLE
headers are case insensitive yet ember-data looks for case sensitive headers

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/data#4342] opened 2016-04-19 22:06 UTC
[ RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616.html) states that 

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

Yet ember data looks for headers using case sensitive lookups. 

https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1138

```
generatedDetailedMessage: function(status, headers, payload, requestData) {
    var shortenedPayload;
    var payloadContentType = headers["Content-Type"] || "Empty Content-Type";
```

**Comment by runspired** [comment] 2018-04-16 18:51
Closing as a duplicate of #4952 which has better detail.

**Closed by runspired** 2018-04-16 18:51 UTC
Labels: Bug
