### ISSUE TITLE
N createRecords in the same runloop will discard belongsTo references for N-1 first createRecords.

### ISSUE THREAD

**Issue by SeyZ** [emberjs/data#2742] opened 2015-01-30 12:12 UTC
Here's the demo of the bug:
http://jsbin.com/nevuca/1/edit

Check the payload of the XHRs.

The 3 first payload are: `{"foo":{"bar":null}}`
Only the last one is good: `{"foo":{"bar":"1"}}`

**Comment by bmac** [comment] 2015-02-01 01:34
@SeyZ The problem is Ember Data assumes the `bar` relationship on the `Foo` model is the inverse relationship of the `foo` on the `Bar` model. Ember Data is attempting to keep these 2 relationships in sycn. And unsetting the earlier `bar` relationships when a new relationship `bar` relationship is created to the original `Bar` model. The best way to fix this is to tell Ember Data not to attempt to find an inverse relationship for `foo`.

```js
App.Bar = DS.Model.extend({
  foo: DS.belongsTo('foo', {inverse: null})
});
```

**Comment by bmac** [comment] 2015-02-09 02:06
Closing as I believe this will be solved by the `inverse: null` let me know if the problem is somewhere else.

**Closed by bmac** 2015-02-09 02:06 UTC
