### ISSUE TITLE
Coalesced requests repeat ID's

### ISSUE THREAD

**Issue by orf** [emberjs/data#4367] opened 2016-05-04 08:59 UTC
Hey,
I've noticed that in some cases coalesced requests repeat the ID's being fetched, i.e issuing two requests for a model with the ID 1 will result in `/api/models?ids[]=1&ids[]=1` being fetched.

This normally wouldn't be an issue, but if you are fetching something with a long ID that is duplicated many times then the request URI can get very long which can cause some web servers to reject the request, and as far as I can tell duplicating the ID's is not needed. The ID should be unique so it should only send a value once per coalesced request. Is this possible to only send _unique_ coalesced ID's per request?

Edit: I'm using the [ember-django-adapter](https://github.com/dustinfarris/ember-django-adapter/) but I believe this is handled by ember-data?

**Comment by nadavshatz** [comment] 2016-05-12 22:38
👍 
Took me a really long while to realize what was happening.

**Comment by pangratz** [comment] 2016-05-13 07:40
> This normally wouldn't be an issue, but if you are fetching something with a long ID that is duplicated many times then the request URI can get very long which can cause some web servers to reject the request

This should be handled by the logic within `adapter.groupRecordsForHasMany()`, which checks if the resulting URL would be too long and if so, creates a separate request: https://git.io/vrYz5. Just for clarification: did you just mention this as a theoretical consequence of having duplicate, long ids or did you run into this issue. I am asking because this should be handled and if not, then there is a bug there too.

**Comment by orf** [comment] 2016-05-13 07:47
I actually ran into this issue. Everything was working fine until an
important user went to view a specific page, which issued a request 4 bytes
too long for our UWSGI server.
On 13 May 2016 08:41, "Clemens Müller" <notifications@github.com> wrote:

This normally wouldn't be an issue, but if you are fetching something with
a long ID that is duplicated many times then the request URI can get very
long which can cause some web servers to reject the request

This should be handled by the logic within adapter.groupRecordsForHasMany(),
which checks if the resulting URL would be too long and if so, creates a
separate request: https://git.io/vrYz5. Just for clarification: did you
just mention this as a theoretical consequence of having duplicate, long
ids or did you run into this issue. I am asking because this should be
handled and if not, then there is a bug there too.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/emberjs/data/issues/4367#issuecomment-218973175>

**Comment by pangratz** [comment] 2016-05-13 07:59
Hmm, ok 😔  . You can set the [`maxURLLength` property](https://git.io/vrYao) on the adapter which should help you there...

**Comment by fivetanley** [comment] 2016-05-25 18:49
@pangratz in PouchDB they use a `maxURLLength` equivalent to split into multiple requests. Is that what we do here?

**Comment by pangratz** [comment] 2016-05-25 21:07
@fivetanley yep

**Comment by wecc** [comment] 2016-10-21 15:13
I wonder how we can end up with the same ID twice in the same request?

@orf do you think you would be able to reproduce the issue of getting the same ID more than once?

**Comment by pangratz** [comment] 2016-10-21 15:34
@wecc I tracked the root cause of this issue down in https://github.com/emberjs/data/pull/4368#issuecomment-219300514

**Comment by runspired** [comment] 2021-05-26 05:57
Possibly addressed in full by #4596 but regardless we should probably use a Set for the fetches to avoid over fetching, similar to the attempt in #4368 to unique the requests array.

Considerations need to be made where any options exist, if the same request exists with multiple options hashes we probably should collapse any that don't have options then either issue multiple findRecord requests skipping findMany per options hash or some such. The correct behavior is a bit unclear.

**Comment by runspired** [comment] 2022-08-12 19:19
Resolved by #8113. We only repeat ID's when options/include are different from a matching ID in the same request.

**Closed by runspired** 2022-08-12 19:19 UTC
Labels: Bug, Good for New Contributors, coalescing
