### ISSUE TITLE
Associated record deletion

### ISSUE THREAD

**Issue by Asherlc** [emberjs/data#4382] opened 2016-05-13 23:41 UTC
In Rails, and I presume other frameworks, it's not uncommon for records to automatically destroy some or all of their associated records when they themselves are destroyed. So, a deletion of one nominal record may delete many other records as well.

Currently, it appears Ember Data has no way to receive this information in response to a DELETE, so orphaned records may be left on the client side that have been destroyed on the server side.

**Comment by pangratz** [comment] 2016-05-15 19:00
Related to #1945

**Comment by wecc** [comment] 2016-10-21 15:00
Closing as a dupe of #1945

**Closed by wecc** 2016-10-21 15:00 UTC
