### ISSUE TITLE
Sideloaded data not completed by the time promise resolves unless reload: true is used

### ISSUE THREAD

**Issue by ginty** [emberjs/data#5977] opened 2019-04-07 20:46 UTC
### Description

I am sideloading hasMany data in a route model hook like this:

~~~js
model() {
  return this.get('store').findRecord('user', user_id, {
    // The model I want to return is one of the user's addresses
    include: 'addresses'
  }).then((user) => {
    // Now I want to run some logic to pick the specific address to be the target model
    return user.get('addresses').findBy('some_attr', some_val);
  });
}
~~~

The problem is that `user.get('addresses')` is firing off an API call even though the addresses have been included in the user find.
Trying to peek them from the store doesn't work either because it seems that by the time the `findRecord` promise has resolved, the work is still to be done to load the sideloaded items.

I am using a rails backend with the `JSONAPI::Resources` gem and my frontend adapter is the `DS.JSONAPIAdapter` - i.e. I'm pretty sure that my API is supplying the sideloaded models in the correct format.
And in fact, if I try in the console once the view has finished rendering I find that I can access the user's address models without an API request firing, so the sideloading did work properly in the end.

I have found a workaround whereby adding `reload: true` to the upfront `findRecord` seems to make the side-loading complete by the time the promise resolves:

~~~js
return this.get('store').findRecord('user', user_id, {
    // Adding this doesn't affect the original API call at all
    reload: true,
    include: 'addresses'
}).then((user) => {
  // But it does mean that the addresses are now available here
  return user.get('addresses').findBy('some_attr', some_val);
});
~~~

I see that there is a similar issue where other's are reporting similar problems on recent Ember data versions here: https://github.com/emberjs/data/issues/4099

### Versions

```cli
frontend
└── ember-source@3.7.3

frontend
└── ember-cli@3.7.1

frontend
└── ember-data@3.7.0
```

**Comment by runspired** [comment] 2019-04-08 20:40
The issue you linked seems unrelated to yours.

What does the normalized payload from the first request look like, and how is this relationship defined on the various models?

**Comment by bartocc** [comment] 2019-04-16 13:21
@runspired I've setup a demo repo to showcase this bug. The setup is just a little bit different in that it loops on the `user.addresses` in the `templates/index.hbs` instead of @ginty 's `model` hook

https://github.com/bartocc/record-data-bug

Everything works fine under ember-data 3.4 but fails with ember-data >= 3.5 until 3.9 as of today.

Here is the browser's log output when accessing `http://localhost:4200`

```
index.js:146 DEBUG: -------------------------------
index.js:146 DEBUG: Ember      : 3.5.1
index.js:146 DEBUG: Ember Data : 3.5.2
index.js:146 DEBUG: jQuery     : 3.3.1
index.js:146 DEBUG: -------------------------------
jquery.js:3600 [Violation] 'setTimeout' handler took 64ms
server.js:28 Mirage: [200] GET /users?include=addresses
pretender.js:419 [Violation] 'setTimeout' handler took 50ms
server.js:28 Mirage: [200] GET /addresses/1/user
server.js:28 Mirage: [200] GET /addresses/2/user
```

and here is the Mirage's response payload

```json
{
  "request": null,
  "response": {
    "data": [
      {
        "type": "users",
        "id": "1",
        "attributes": {},
        "relationships": {
          "addresses": {
            "data": [
              {
                "type": "addresses",
                "id": "1"
              },
              {
                "type": "addresses",
                "id": "2"
              }
            ]
          }
        }
      }
    ],
    "included": [
      {
        "type": "addresses",
        "id": "1",
        "attributes": {},
        "relationships": {
          "user": {
            "links": {
              "related": "/addresses/1/user"
            }
          }
        }
      },
      {
        "type": "addresses",
        "id": "2",
        "attributes": {},
        "relationships": {
          "user": {
            "links": {
              "related": "/addresses/2/user"
            }
          }
        }
      }
    ]
  },
  "raw": {
    "_eventListeners": {
      "loadend": [
        null
      ],
      "abort": [
        null
      ],
      "load": [
        null
      ],
      "progress": [
        null
      ],
      "loadstart": [
        null
      ]
    },
    "readyState": 4,
    "requestHeaders": {
      "Accept": "application/vnd.api+json",
      "X-Requested-With": "XMLHttpRequest"
    },
    "requestBody": null,
    "status": 200,
    "statusText": "OK",
    "upload": {
      "_eventListeners": {
        "loadend": [
          null
        ],
        "abort": [
          null
        ],
        "load": [
          null
        ],
        "progress": [
          null
        ],
        "loadstart": [
          null
        ]
      }
    },
    "method": "GET",
    "url": "/users?include=addresses",
    "async": true,
    "responseText": "{\"data\":[{\"type\":\"users\",\"id\":\"1\",\"attributes\":{},\"relationships\":{\"addresses\":{\"data\":[{\"type\":\"addresses\",\"id\":\"1\"},{\"type\":\"addresses\",\"id\":\"2\"}]}}}],\"included\":[{\"type\":\"addresses\",\"id\":\"1\",\"attributes\":{},\"relationships\":{\"user\":{\"links\":{\"related\":\"/addresses/1/user\"}}}},{\"type\":\"addresses\",\"id\":\"2\",\"attributes\":{},\"relationships\":{\"user\":{\"links\":{\"related\":\"/addresses/2/user\"}}}}]}",
    "responseXML": null,
    "sendFlag": true,
    "onload": null,
    "ontimeout": null,
    "onerror": null,
    "onreadystatechange": null,
    "errorFlag": false,
    "params": {},
    "queryParams": {
      "include": "addresses"
    },
    "_includesGraph": {
      "data": {
        "user:1": {
          "relationships": {
            "addresses": [
              "address:1",
              "address:2"
            ]
          }
        }
      },
      "included": {
        "addresses": {
          "address:1": {},
          "address:2": {}
        }
      }
    },
    "responseHeaders": {
      "Content-Type": "application/json"
    },
    "onabort": null
  }
}
```

If you comment the `links` method in `mirage/serializers/address.js`, the bug goes away.

**Comment by runspired** [comment] 2019-04-16 18:21
@bartocc I believe the issue here (at least in part) is that the payload is invalid from a json-api perspective. The included addresses should have

```js
relationships: {
  user: {
    data: {
      type: 'address',
      id: '1'
    }
  }
}
```

**Comment by bartocc** [comment] 2019-04-16 20:13
@runspired 

didn't you mean this instead?

```json
relationships: {
  user: {
    data: {
      type: 'user',
      id: '1'
    }
  }
}
```

**Comment by bartocc** [comment] 2019-04-16 20:42
Ok, I've updated `mirage/serializers/address.js` with `alwaysIncludeLinkageData: true` and the response payload is now

```json
{
  "data": [
    {
      "type": "users",
      "id": "1",
      "attributes": {},
      "relationships": {
        "addresses": {
          "data": [
            {
              "type": "addresses",
              "id": "1"
            },
            {
              "type": "addresses",
              "id": "2"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "type": "addresses",
      "id": "1",
      "attributes": {},
      "relationships": {
        "user": {
          "links": {
            "related": "/addresses/1/user"
          },
          "data": {
            "type": "users",
            "id": "1"
          }
        }
      }
    },
    {
      "type": "addresses",
      "id": "2",
      "attributes": {},
      "relationships": {
        "user": {
          "links": {
            "related": "/addresses/2/user"
          },
          "data": {
            "type": "users",
            "id": "1"
          }
        }
      }
    }
  ]
}
```

and the bug is gone.

I still need to understand how ember-data handles the json-api responses in different scenarios though.

Can you please correct/confirm the following statements?

Let's assume the DB contains 1 user and 2 addresses

- ember app with ember-data 3.4 / API without linkage data

```javascript
this.store.query('user', { include: 'addresses' })
// add the user and the addresses to the store
// user.addresses is set in the store
// address.user is also set in the store and would NOT yield an API call
```

- ember app with ember-data 3.5 / API without linkage data

```javascript
this.store.query('user', { include: 'addresses' })
// add the user and the addresses to the store
// user.addresses is set in the store
// address.user is NOT set in the store and WOULD yield an API call
```

- ember app with ember-data 3.5 / API with linkage data

```javascript
this.store.query('user', { include: 'addresses' })
// add the user and the addresses to the store
// user.addresses is set in the store
// address.user is also set in the store and would NOT yield an API call
```

I think what's bothering me the most is that when I use the `include` directive in an ember-data `store.findXXX` query, I expect the included resources to be linked with the primary resource.

But it turns out that this is only true if the linkage data was returned from the API.

**Comment by runspired** [comment] 2019-07-12 23:32
Closing as this was an issue with the the payload not having been normalized correctly.

> I think what's bothering me the most is that when I use the include directive in an ember-data store.findXXX query, I expect the included resources to be linked with the primary resource.
> But it turns out that this is only true if the linkage data was returned from the API.

`include` is a query param for what to "include" in the response in the `included` resources array. It could include directly or indirectly related resources, and the linkage is still required. We'd have no way of making the association correctly without such linkage.

**Closed by runspired** 2019-07-12 23:32 UTC

**Comment by bartocc** [comment] 2019-07-18 07:27
Thx for clarifying @runspired 👍

**Comment by aalimovs** [comment] 2019-12-02 11:07
@runspired I want to revive this bug, I believe the issue is still there.

I'm using `findRecord` with `include`, and the included data is present in the response.

```
model() {
  return this.store.findRecord('automation', this.modelFor('automations.show').id, {
      include: 'automationSetting',
      // reload: true,
  }).then(automation => {
      console.log(automation.get('automationSetting.id'));
  });
}
```

```
{
  "data": {
    "type": "automations",
    "id": "1",
    "attributes": {
      "active": true,
      ...
    },
    "relationships": {
      "automationSetting": {
        "data": {
          "type": "automation-settings",
          "id": "1"
        }
      }
    }
  },
  "included": [{
    "type": "automation-settings",
    "id": "1",
    "attributes": {
      "createdAt": "2019-06-02T18:04:45.859Z",
      ...
    }
  }]
}
```

In both scenarios with the same response, without `reload`, `automation.get('automationSetting.id')` is undefined. With `reload`, it is defined.

**Comment by runspired** [comment] 2019-12-02 11:12
@aalimovs is that the post-normalization payload?

**Comment by aalimovs** [comment] 2019-12-02 11:41
sorted with @runspired in Discord chat.

The issue was that a level up in the route, I was requesting the model without any includes. 

In the child route where I `include: automationSetting` in `model()`, `findRecord` would return the model from the store (`findRecord` always checks the store first before doing any network requests).

So regardless what I try to `include` this child route, without `reload` it would return it from the store. Hence in this case, I have to either always `reload` in this child route, or just `peekRecord()` and `await automation.get('automationSetting');`.
