### ISSUE TITLE
EmbeddedRecordsMixin + RESTSerializer fails to extract relationships properly

### ISSUE THREAD

**Issue by k-fish** [emberjs/data#4575] opened 2016-10-14 19:50 UTC
Versions I've checked where this occurs: **2.6.2, 2.7**
Does not occur on **1.13.11**

If you have a simple (non JSON-API) payload

``` js
{
  "posts": [{
    "id": 1
    "author": {
      "id": 2,
      "name": "foobar"
    }
  }]
}
```

and you are using a `RESTSerializer` that uses `EmbeddedRecordsMixin`

``` js
app/serializers/post.js

import DS from 'ember-data';

const { RESTSerializer, EmbeddedRecordsMixin } = DS;
export default RESTSerializer.extend(
EmbeddedRecordsMixin, 
{
  attrs: {
    'author': { serialize: 'records', deserialize: 'records' }
  }
});
```

``` js
app/models/post.js

import DS from 'ember-data';

const { belongsTo, Model } = DS;

export default Model.extend({
  author: belongsTo('author')
});
```

When `embedded-records-mixin` calls `normalize` (https://github.com/emberjs/data/blob/master/addon/serializers/embedded-records-mixin.js#L128), it ends up calling https://github.com/emberjs/data/blob/master/addon/serializers/json.js#L541 with the REST payload.

Since this example is belongsTo, `extractRelationships` will call https://github.com/emberjs/data/blob/master/addon/serializers/json.js#L687

which passes a `relationshipHash` which still is in rest format:

``` js
{
  "id": 2,
  "name": "foobar"
}
```

Which means trying to retrieve a type by using `relationshipHash.type` in https://github.com/emberjs/data/blob/master/addon/serializers/json.js#L611 won't work.

`modelClass` gets passed to `extractRelationships` so it's not too hard to work around this currently by overriding it.

I believe this might be the same issue as https://github.com/emberjs/data/issues/3786. I'm not sure whether this behaviour is intended, or I'm missing something obvious.

Help/Suggestions would be appreciated, thanks 👍

**Comment by k-fish** [comment] 2016-10-18 18:44
This appears to specifically be caused by `json-api` being the default serializer. So without a serializer, `author` is expected to be in json-api format. I'm not sure if this is expected behaviour. Should embedded records be extracted as the parent serializers format by default? Otherwise rest payloads can have embedded json-api.

**Comment by wecc** [comment] 2016-10-20 19:50
@k-fish JSONAPISerializer is the default serializer and it doesn't support `EmbeddedRecordsMixin`. One important thing to note is that if you have a `post` serializer with embedded `author`, the `post` serializer will delegate the normalization of `author` to the `author` serializer, if that makes sense? So, if the `author` serializer is a JSONAPISerializer this won't work.

**Comment by k-fish** [comment] 2016-10-22 18:11
@wecc Ya that is exactly what I stumbled upon when looking into it further. I'm now just mentioning that since serializers that are not specified are generated and use `json-api` by default, some rest serializers that use embedded records and worked fine in `1.13` will break in `2.x` versions. I've found this out myself while recently upgrading Ember Data.

**Comment by wecc** [comment] 2016-10-22 20:40
@k-fish you should be able to set your `application` adapter/serializer to `RESTAdapter`/`RESTSerializer` (if that's what you want to use) and any un-specified serializers should use the `application` one.

If you can replicate "some rest serializers that use embedded records and worked fine in 1.13 will break in 2.x versions" using JSBin or Ember Twiddle I would be happy to take a look?

**Comment by k-fish** [comment] 2016-10-24 13:04
@wecc Thanks for taking the time to respond and look into it.

Ember Data 1.13: https://ember-twiddle.com/3812c90228b16779d3ce54c6e6f8b109?openFiles=twiddle.json%2C
Ember Data 2.9: https://ember-twiddle.com/adad923c7c47ff35eb73737fd2f40e97?openFiles=twiddle.json%2C

**Comment by wecc** [comment] 2016-10-24 13:33
@k-fish In the Twiddle you have only defined your `post` serializer and it extends from `RESTSerializer`. This is fine by itself but since you also have an embedded `author` model Ember Data looks up the `author` serializer when it wants to normalize the `author` part of your payload. This will give you the default serializer (the `JSONAPISerializer`).

You can solve this in two ways:

1. Define an `application` serializer and extend `RESTSerializer` – this will become the default serializer for all of your models (if no type specific one is available). **Recommended**
2. Define your `author` serializer and make it also extend from `RESTSerializer`.

It's a good idea to define the `application` serializer/adapter and put all shared customizations inside plus having your type specific ones extend from it.

If you have any other questions on customizing adapters/serializers feel free to reach out in the [Ember Community Slack](https://embercommunity.slack.com/) or the [forums](http://discuss.emberjs.com/).

I'm closing this issue since it's not a bug within Ember Data. This was an intentional breaking change introduced in Ember Data 2.0.

**Comment by k-fish** [comment] 2016-10-24 13:41
@wecc Thanks for the response.

Those will be great tips for people who run into this breaking change.

If this is intended and accepted behaviour, I'm fine with closing it.

**Comment by wecc** [comment] 2016-10-24 13:49
@k-fish The [Ember Data 1.13 release post](http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html) described these changes in detail.

Ember Data 1.13 also included this deprecation warning:

> You are currently using the default DS.RESTAdapter adapter. For Ember 2.0 the default adapter will be DS.JSONAPIAdapter. If you would like to continue using DS.RESTAdapter please create an application adapter that extends DS.RESTAdapter.

**Comment by k-fish** [comment] 2016-10-24 14:06
Yup, I understand that REST is no longer the default, but I don't think the fact that embedded records use the default isn't straightforward.

**Comment by wecc** [comment] 2016-10-24 14:12
@k-fish I looked at the documentation and the guides and I agree. I couldn't find any documentation mentioning the that the embedded records themselves uses their "own" serializer.

**Comment by k-fish** [comment] 2016-12-17 19:51
@wecc  Sorry, I must have missed the edit. I'll put up a PR for documentation shortly. 👍

**Comment by pangratz** [comment] 2017-10-07 17:17
Closing as #4719 addresses this. Thanks @k-fish!

**Closed by pangratz** 2017-10-07 17:17 UTC
Labels: Documentation
