### ISSUE TITLE
JSONAPISerializer primaryKey attribute

### ISSUE THREAD

**Issue by camarrone** [emberjs/data#5272] opened 2017-12-06 16:21 UTC
Hello,

I'm working with MongoDB and need to change the `primaryKey` attribute to "_id". I have this application serializer:

```
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
        primaryKey: '_id'
});

```

When I go to any route that retrieve records from the server, I'm getting the following error:

```
TypeError: Cannot read property 'replace' of undefined
    at Cache.func (ember.debug.js:41491)
    at Cache.get (ember.debug.js:24925)
    at decamelize (ember.debug.js:41534)
    at Cache.func (ember.debug.js:41439)
    at Cache.get (ember.debug.js:24925)
    at Object.dasherize (ember.debug.js:41538)
    at normalizeModelName (-private.js:1280)
    at Class.modelNameFromPayloadKey (json-api.js:324)
    at Class._extractType (json-api.js:320)
    at Class.normalize (json-api.js:340)
```

Versions that I'm using are: `"ember-cli": "~2.14.1"` and `"ember-data": "~2.14.3"`

Have anyone faced any issue like this?

Thanks very much for the help.

**Comment by pangratz** [comment] 2017-12-06 16:31
Seems to work as expected with 2.16, see [this ember-twiddle](https://ember-twiddle.com/a3260f2d7a5a8ac4ca378e6fb99f9c70?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Cserializers.application.js%2Ctemplates.application.hbs).

According to the stack trace the problem is somewhere with your model names, but without a payload this is hard to say.

I am closing as this seems to b working. Please reopen if this is still a bug, ideally with an ember-twiddle reproducing the issue you're having.

Thanks!

**Closed by pangratz** 2017-12-06 16:31 UTC

**Comment by zion03** [comment] 2018-12-17 22:11
Same problem when I'm trying to `normalize` raw data, but this raw data works fine with `pushPayload`

```
DEBUG: -------------------------------
DEBUG: Ember           : 3.0.0
DEBUG: Ember Data      : 3.6.0
DEBUG: jQuery          : 3.3.1
DEBUG: Ember Bootstrap : 1.2.1
DEBUG: -------------------------------

```
```
string.js:63 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Cache.func (string.js:63)
    at Cache.get (ember-metal.js:2611)
    at decamelize (string.js:100)
    at Cache.func (string.js:11)
    at Cache.get (ember-metal.js:2611)
    at Object.dasherize (string.js:104)
    at normalizeModelName (-private.js:560)
    at Class.modelNameFromPayloadKey (json-api.js:352)
    at Class._extractType (json-api.js:338)
    at Class.normalize (json-api.js:379)
```
