### ISSUE TITLE
Check if async relation is null without fetching relation

### ISSUE THREAD

**Issue by lrdevries** [emberjs/data#2286] opened 2014-09-17 15:19 UTC
Hello,

I've got a page where i want to show all elements without an relation. To determine this i have the following code:

    lonelyModels: function(){
        var array = this.get("allModels");
        var self = this;
        return array.filter(function(item,index,enuma){
            return !item.get("relationToB");
        });
    }.property("allModels.@each.relationToB"),
    allModels: function(){
      return this.store.find("modelA");
    }.property();

But now it also makes requests to the server for the model behind relationToB. But i only need the object without an relation set, so i also do not need the async relations. When you've got 1000 records in the database, its a real bummer for efficiency.  How can i get all modelA objects without a relation to modelB, without loading the relations that does exists. (and if one in the list gets a relation it should also be removed from the list)

**Comment by igorT** [comment] 2015-05-25 00:38
Yes, this is a real use case that we want to support, https://github.com/emberjs/rfcs/pull/57 is aiming to address it. Closing this as a duplicate of https://github.com/emberjs/data/issues/2271

**Closed by igorT** 2015-05-25 00:38 UTC
