### ISSUE TITLE
Need a way for store.save() that only post to side , but only saves to client side store when asked.

### ISSUE THREAD

**Issue by v3ss0n** [emberjs/data#4419] opened 2016-06-04 14:56 UTC
On real-time shared data like chat room message queue, ember data's functions createRecord , deleteRecord ,. updateRecord , and then .save() is quite useless, because it stores , regardless of server's response, or in real-time systems cases , regardless of  server side state. 

in realtime message queus , the service loop that waiting for data pushes data to ember store , and should not be done by createRecord/updateRecord. 
there seems no way to bypass updating client-side store , and only have to resort to using manual ajax call which defeats the purpose of using store's CRUD functions.

**Comment by wecc** [comment] 2016-10-21 14:01
Closing this as a duplicate of #1829

**Closed by wecc** 2016-10-21 14:01 UTC
