### ISSUE TITLE
rest-serializer.extractSingle bug

### ISSUE THREAD

**Issue by wenjiezhang2013** [emberjs/data#3683] opened 2015-08-20 21:26 UTC
I am trying to use ember data version 1.13.

I defined a model in app/models/job.js

import DS from 'ember-data';

export default DS.Model.extend({
  	status: DS.attr("string"),
  	result: DS.attr("string")
});

and Trying to find it from the controller:

actions: {
        search: function() {
        	let data = this.store.find("job", '9e5ce869-89b3-4bfc-a70f-034593c21eae');
            return data;
        }
    }

I got the HTTP response with:
{
  "status": "OK",
  "result": {
    "b": 2,
    "a": 2,
    "see": 1,
    "c": 1
  }
}

How ever I got the warning saying: 

WARNING: Encountered "status" in payload, but no model was found for model name "status" (resolved model name using next-gen-analytics@serializer:job:.modelNameFromPayloadKey("status"))
ember.debug.js:5358 WARNING: Encountered "result" in payload, but no model was found for model name "result" (resolved model name using next-gen-analytics@serializer:job:.modelNameFromPayloadKey("result"))

and the warnings break the CODE.

TypeError: Cannot read property '_internalModel' of undefined
    at finders.js:50
    at Object.Backburner.run (ember.debug.js:224)
    at ember$data$lib$system$store$$Service.extend._adapterRun (store.js:2043)
    at finders.js:45
    at tryCatch (ember.debug.js:56151)
    at invokeCallback (ember.debug.js:56166)
    at publish (ember.debug.js:56134)
    at ember.debug.js:32577
    at Queue.invoke (ember.debug.js:910)
    at Object.Queue.flush (ember.debug.js:974)onerrorDefault @ ember.debug.js:32616exports.default.trigger @ ember.debug.js:56792Promise._onerror @ ember.debug.js:57758publishRejection @ ember.debug.js:56065(anonymous function) @ ember.debug.js:32577Queue.invoke @ ember.debug.js:910Queue.flush @ ember.debug.js:974DeferredActionQueues.flush @ ember.debug.js:770Backburner.end @ ember.debug.js:160Backburner.run @ ember.debug.js:228run @ ember.debug.js:20238ember$data$lib$system$adapter$$default.extend.ajax.Ember.RSVP.Promise.hash.success @ rest-adapter.js:831jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260done @ jquery.js:9314jQuery.ajaxTransport.send.callback @ jquery.js:9718

**Comment by wenjiezhang2013** [comment] 2015-08-20 21:27
I am a newbie, please confirm that if this is not a bug.

**Comment by wecc** [comment] 2015-08-20 21:35
Confirm, this is not a bug.

The RESTSerializer expects a certain format of the payload returned from your server. If you do `this.store.find('job', '9e5ce869-89b3-4bfc-a70f-034593c21eae');` your payload would have to look something like:

```json
{
  "job": {
    "id": "9e5ce869-89b3-4bfc-a70f-034593c21eae",
    "hello": "world",
    "foo": "bar",
   }
}
```

**Comment by wenjiezhang2013** [comment] 2015-08-20 21:45
I can understand that if I am using "findAll()", that I should expect getting 
{
  "jobs": [{
    "id": "9e5ce869-89b3-4bfc-a70f-034593c21eae",
    "hello": "world",
    "foo": "bar",
   },
   {
    "id": "xyz"
    "hello": "world",
    "foo": "bar",
   }...]
}

But since I am using "find()", but it does not just expect 
{
"id": "9e5ce869-89b3-4bfc-a70f-034593c21eae"
"status": "OK",
"result":  "XYZ"
}

**Comment by wenjiezhang2013** [comment] 2015-08-20 21:46
@wecc Thanks for your answer, one more question, is there any way that I can still use ember data while I get response without an ID? Because I do not have the access to change the server side code.

**Comment by wecc** [comment] 2015-08-20 21:51
The RESTSerializer requires all records to be under a root key with the name of that type. You can use JSONSerializer if you want to use a "flat" structure. Have a look at the different serializers in the docs: http://emberjs.com/api/data/

Ember Data identifies all records using type + ID, so IDs are required.

Feel free to ask additional questions in the Ember Community Slack and the [Discussion Forum](http://discuss.emberjs.com/), we want to keep issues to bugs only. Closing this.

**Closed by wecc** 2015-08-20 21:51 UTC
