### ISSUE TITLE
REST Adapter generatedDetailedMessage does not not ignore http header casing

### ISSUE THREAD

**Issue by felixbuenemann** [emberjs/data#5084] opened 2017-07-23 16:42 UTC
There's a bug in `RESTAdapter.generatedDetailedMessage`:

See https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1190

The code does not ignore header case, so for example with HTTP/2 servers which always downcase headers, the content type is stored in `headers['content-type']` not `headers['Contenty-Type']`.

Which leads to the following error message:

```
"Ember Data Request GET <url> returned a 404
Payload (Empty Content-Type)
[object Object]"
```

The similar code in `ember-ajax` does not have this issue and also prints the stringified JSON response instead of '[object Object]':

https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-request.js#L633

**Comment by pangratz** [comment] 2017-10-05 20:58
Good catch! Wanna submit a PR which adds the same functionality for case insensitive header names as in `ember-ajax`?

**Comment by runspired** [comment] 2018-04-19 19:48
Closing in favor of the root cause in #4952

**Closed by runspired** 2018-04-19 19:48 UTC
