### ISSUE TITLE
"Cannot read property 'destroy' of undefined" when hasMany used with each in view

### ISSUE THREAD

**Issue by landgray** [emberjs/data#2769] opened 2015-02-10 04:02 UTC
Using beta build of ember-data, ember 1.9.1

Minimal reproduction: http://jsbin.com/sarikinani/1/edit?html,js,console

```javascript
$.mockjax({
  type: 'GET',
  url: '/foos/1',
  status: '200',
  dataType: 'json',
  responseText: {
    foo: {
      id: '1',
      links: {
        bars: '/bars'
      }
    }
  }
});

$.mockjax({
  type: 'GET',
  url: '/bars',
  status: '200',
  dataType: 'json',
  responseText: {
    'bars': [
      {
        id: '1'
      }, {
        id: '2'
      }
    ]
  }
});

window.App = Ember.Application.create({
  rootElement: 'body'
});

App.ApplicationRoute = Ember.Route.extend({
  model: function() {
    return this.store.find('foo', 1);
  }
});

App.Foo = DS.Model.extend({
  bars: DS.hasMany('bar', {
    async: true
  })
});

App.Bar = DS.Model.extend();
```

```handlebars
{{#each bar in bars}}
  bar
{{/each}}
```

**Comment by sly7-7** [comment] 2015-02-10 08:39
Hi, thanks for the report. I think it's a duplicate of https://github.com/emberjs/data/issues/2662, so I'm closing this.

**Closed by sly7-7** 2015-02-10 08:39 UTC
