### ISSUE TITLE
keyForRelationship not called by EmbeddedRecordsMixin

### ISSUE THREAD

**Issue by mlb5000** [emberjs/data#5227] opened 2017-10-12 14:25 UTC
The `keyForRelationship` method does not appear to be called for models unless it is on the serializer for that specific model. Basically, if you put `keyForRelationship` on your `application` serializer it won't have any effect.

```js
// serializers/application.js
import DS from 'ember-data';

export default DS.JSONSerializer.extend({
  keyForRelationship(key, relationship, method) {
    // this does not get called
    if (relationship === 'belongsTo') {
      return Ember.String.underscore(key)+'Id';
    }
   }
});
```

```js
// serializers/group-member.js
import DS from 'ember-data';

export default DS.JSONSerializer.extend({
  keyForRelationship(key, relationship, method) {
    // this does
    if (relationship === 'belongsTo') {
      return Ember.String.underscore(key)+'Id';
    }
   }
});
```

Ember Data 2.14.10

**Comment by bmac** [comment] 2017-10-13 21:28
Hi @mlb5000. I wasn't able to reproduce this issue. You can checkout my attempt here: https://ember-twiddle.com/087ca532641106a0897c14672fa94527?openFiles=serializers.application.js%2C 

Is there any chance you already have a model specific serializer that doesn't extend the application serializer?

**Comment by pangratz** [comment] 2017-10-14 16:58
@mlb5000 according to the sample you posted it seems there is a missing call to `this._super(...arguments)` within your `group-member.js` serializer.

I am closing as this is not reproducable. Feel free to reopen if you still run into this issue, ideally with an updated ember twiddle @bmac posted. Thanks!

**Comment by mlb5000** [comment] 2017-10-14 17:05
@bmac @pangratz I believe I isolated the issue to records pulled in using `EmbeddedRecordMixin`. When retrieved directly from the server the application serializer is called as expected, but does not appear to be called when records enter the store from embedded retrieval.

**Comment by pangratz** [comment] 2017-10-14 17:29
Can you provide a failing ember twiddle? That would help greatly in tracking down this issue?

**Comment by runspired** [comment] 2021-05-22 09:25
Closing as stale since the issue was never verified.

**Closed by runspired** 2021-05-22 09:25 UTC
Labels: Needs Bug Verification
