### ISSUE TITLE
objectAt in hasMany relation after record removal still returns record

### ISSUE THREAD

**Issue by denisovlev** [emberjs/data#2968] opened 2015-04-01 13:39 UTC
objectAt: function(index) {
      if (this.currentState[index]) {
        return this.currentState[index];
      } else {
        return this.canonicalState[index];
      }
    },

This code in ManyArray returns record even after it was deleted from relation. Documentation for array says following: 
> If the given index is negative or is greater or equal than the array length, returns undefined.

Does current behavior means that we shouldn't use objectAt at hasMany relations?

**Comment by ghedamat** [comment] 2015-04-02 20:24
:+1: pretty sure I've just hit the same bug
will try to reproduce on a jsBin asap

**Comment by ghedamat** [comment] 2015-04-03 19:41
Ok

I think I've isolated a possible way of reproduce

click on the jsbins and try to hit the remove button, the list should shorten.

if one simply uses the hasMany relationship it works
http://emberjs.jsbin.com/lejepa/5/edit?html,js,output

but if `.objectsAt` is appended then it's broken and removed elements are still returned:
http://emberjs.jsbin.com/lejepa/4/edit?html,js,output

as @denisovlev was mentioning I'd love to know whether this is actually a supported use case for the DS.ManyArray

thanks!

**Comment by trianglegrrl** [comment] 2015-04-22 18:20
:+1: This seems to be the cause of one of the long-standing bugs in one of our apps. We're on beta 15.

**Comment by igorT** [comment] 2015-05-08 22:15
I screwed up and thought this was the same bug as a more complex relationship bug I got stuck tackling. Apologies for that, I should've realized that this code was wrong.

This was a premature optimization because we didn't want to copy over canonical array to the current array every time, but rather access it lazily. However that proved hard, so for the initial implementation I ended up copying. However this was not removed and snuck through code review. :(
Is fixed by #3054

**Comment by igorT** [comment] 2015-05-08 22:16
@trianglegrrl @lukegalea told me you had no bugs, feel free to ping me if things come up

**Closed** 2015-05-08 22:23 UTC

**Comment by ghedamat** [comment] 2015-05-08 22:27
@igorT thanks!

**Comment by trianglegrrl** [comment] 2015-05-09 14:09
@igorT  thanks for looking at it! 

Luke probably just forgot about this bug. :) I'll test it this weekend.
