### ISSUE TITLE
Assertion Failed: Cannot call get with 'isNew' on an undefined object.

### ISSUE THREAD

**Issue by sergiferran** [emberjs/data#2950] opened 2015-03-27 04:53 UTC
Hi.

I'm using next versions:
Ember      : 1.11.0-beta.5
Ember Data : 1.0.0-beta.16
jQuery     : 2.0.0

I have a model named 'mapping' with 2 relationships belongsTo:
  segment: DS.belongsTo('segmentlist-mapping'),
  organization: DS.belongsTo('organization'),

When I do a store.find('mapping', params) everything works as expected, but if i do a store.unloadAll('mapping') and then i do again a store.find('mapping', params) it raises one error

"Error: Assertion Failed: Cannot call get with 'isNew' on an undefined object.↵    at new Error (native)↵    at Error.EmberError (http://localhost:8000/vendor/ember/ember.debug.js:11961:21)↵    at Object.Ember.default.assert (http://localhost:8000/vendor/ember/ember.debug.js:5141:13)↵    at get (http://localhost:8000/vendor/ember/ember.debug.js:15541:22)↵    at null.<anonymous> (http://localhost:8000/vendor/ember-data/ember-data.js:7666:14)↵    at Descriptor.ComputedPropertyPrototype.get (http://localhost:8000/vendor/ember/ember.debug.js:10304:26)↵    at Object.get (http://localhost:8000/vendor/ember/ember.debug.js:15562:19)↵    at exports.default.mixin.Mixin.create.get (http://localhost:8000/vendor/ember/ember.debug.js:30122:27)↵    at ember$data$lib$system$relationships$state$relationship$$Relationship.flushCanonical (http://localhost:8000/vendor/ember-data/ember-data.js:6651:36)↵    at Queue.invoke (http://localhost:8000/vendor/ember/ember.debug.js:871:18)"

**Comment by igorT** [comment] 2015-03-28 00:04
Hi, 
Could you  please provide a failing JSBin showing this error. You can find a template JSBin at http://emberjs.jsbin.com/lavacavige/edit?html,js,output

**Comment by sergiferran** [comment] 2015-03-30 07:20
Hi,

Here you are: http://emberjs.jsbin.com/mupoturope/2/edit


Thank you

**Comment by sergiferran** [comment] 2015-03-30 10:09
hi, try this better, is the correct versions:

http://emberjs.jsbin.com/kinevarovo/1/edit?html,js,output

Thank you

**Comment by RuslanZavacky** [comment] 2015-03-31 21:52
I am experiencing the same problem :disappointed:

**Comment by sergiferran** [comment] 2015-04-01 01:21
Ruslan, i was starting to experince that with 1.11 as well.

**Comment by RuslanZavacky** [comment] 2015-04-01 16:02
@sergiferran have you found any workaround, how to clean-up records, before pushing new ones?:) Seems like unloadAll on records with relationship breaks things, but where is exact problem I was not able to found :)

**Comment by RuslanZavacky** [comment] 2015-04-06 09:18
@sergiferran seems like if you unload mapping, you have also unload all other relationships, related to mapping. In my case it helped.

**Comment by sergiferran** [comment] 2015-04-07 04:01
@RuslanZavacky  yes, i realized that as well, but in my real code, i can not unload other dependencies. We must to wait what Ember-data guys tell us.

**Comment by sergiferran** [comment] 2015-04-07 04:10
@igorT do you know what is the problem?

Thanks in advance

**Comment by marcemira** [comment] 2015-04-22 14:09
Any news about this issue?

**Comment by raytiley** [comment] 2015-05-01 16:28
Running into this as well. Will try to push a failing test case later today. Looking at the code it doesn't seem like Model.unloadRecord() does any cleanup on relationships, and the store's unloadAll just calls the models unloadRecord and then calls destroy on the record.

@igorT if you give me a rough idea on what to do for a fix I'm willing to have a crack at it. This is a blocking bug in our app that is kinda hard to work around.

**Comment by givanse** [comment] 2015-05-02 14:54
Looks like the same problem described here: https://github.com/emberjs/data/issues/2982

I tried to set up a test case, but I couldn't do it without a running app. In that issue you'll see that I prepared a branch where I am reproducing the problem with a minimal set of data and also my current workaround.

**Comment by igorT** [comment] 2015-05-02 18:57
I bet this has something to do with Ember CP change that now houses CPs in the props directly

**Comment by raytiley** [comment] 2015-05-02 19:28
Just had a screen sharing session with @igorT to show him this problem in my app. In my case the error happens because ember data is eagerly `flushCanonical` on all types of relationships, including base relationships (where only one side has the relationship). According to Igor this might be fixed in the references (https://github.com/emberjs/data/tree/references) branch. I'm going to pull that down later and try it out.

The other solution would be to only test for the type of relationship when scheduling the flush and only do that for `hasMany` and `belongsTo` relationships. This would fix my issue, but might not fix it for people that do have relationships on both sides.

**Comment by matixmatix** [comment] 2015-05-05 13:08
@igorT @raytiley have you perhaps figured something out? I have quite a few relationships between my models and `unloadAll` for some models causes the mentioned issue.

**Comment by raytiley** [comment] 2015-05-05 13:40
@matixmatix I just pulled an built the references branch I linked to above. This resolves the issue in my use case.

**Comment by jgwhite** [comment] 2015-05-19 09:59
Not a super helpful comment, but: The references branch fixed this issue for us too.

**Comment by matixmatix** [comment] 2015-05-20 13:31
While this branch fixes mentioned issue, it breaks on multiple other places:

```
TypeError: content.objectAt(...).getRecord is not a function
    at Ember.ArrayProxy.extend.objectAtContent (ember-data.js:5042)
    at EmberObject.default.extend.objectAt (ember.debug.js:31510)
    at EmberObject.default.extend.objectAtContent (ember.debug.js:31361)
    at EmberObject.default.extend.objectAt (ember.debug.js:31510)
    at exports.default.mixin.Mixin.create.arrayContentDidChange (ember.debug.js:28204)
    at EmberObject.default.extend.arrangedContentArrayDidChange (ember.debug.js:31631)
    at Object.applyStr (ember.debug.js:18059)
    at Object.sendEvent (ember.debug.js:12373)
    at exports.default.mixin.Mixin.create.arrayContentDidChange (ember.debug.js:28193)
    at EmberObject.default.extend.arrangedContentArrayDidChange
```

Example of a call that causes this error: `this.get('teams.content').toArray()`. Even after I commented out this call, references branch still causes issues but I was not able to track down from which points in my app they came up, so I guess it's an internal error.

**Comment by igorT** [comment] 2015-05-31 00:23
Sorry for the late respone, @matixmatix why do you do `this.get('teams.content').toArray()` instead of just `this.get('teams').toArray()`?

**Comment by igorT** [comment] 2015-06-02 04:31
Fixed by #3094

**Comment by igorT** [comment] 2015-06-02 04:31
Please reopen if you still have issues on master

**Comment by igorT** [comment] 2015-06-02 04:31
@raytiley can you please file the other issue we found separetely

**Closed** 2015-06-02 04:31 UTC

**Comment by raytiley** [comment] 2015-06-02 12:51
@igorT are you talking about the issue on the references branch?
