### ISSUE TITLE
Support for natural key's

### ISSUE THREAD

**Issue by erichonkanen** [emberjs/data#5237] opened 2017-10-22 10:14 UTC
Hello,

We've run into an issue with a model that uses a natural key for the `id`.

The issue can be summed up as:

```If a record is created, then deleted, then a new record created with same natural key as previously deleted record, we get error.```

```Assertion Failed: 'natural-key-model' was saved to the server, but the response returned the new id 'foo|bar', which has already been used with another record.``` (ember-data 2.17.0-beta.1)

It seems like the ember-data store is retaining a reference to the supposedly deleted record which prevents a new one from being created.

It is explained more [here](https://discuss.emberjs.com/t/reusing-ids-for-soft-deleted-records/13715/3)

Does ember-data support natural key's or is it something ever talked about? Or, am I off and the issue from above link is unrelated to natural key?

Thanks

**Comment by bmac** [comment] 2017-10-22 15:33
Hi @erichonkanen. This seems like a bug and it is something Ember Data should support.

**Comment by erichonkanen** [comment] 2017-10-22 22:31
@bmac thanks for the input, I'm not entirely familiar with the intimate details of ember-data but do you think a work-around is possible? also where in the code would a new feature for this target? I'd be interested to get more familiar and possibly contribute

**Comment by urbany** [comment] 2017-10-23 18:21
This looks like a duplicate of the `unloadRecord` open issues.
@erichonkanen Here is a work around for now: https://github.com/emberjs/data/issues/4972#issuecomment-336662752

**Comment by erichonkanen** [comment] 2017-10-23 19:04
@urbany ok I'll take a look thanks... to be honest it's frustrating because I have two separate issues going on with ember-data and it has complicated things:

1) We cannot move beyond `2.12.x` due to [an issue with computed properties on related fields.](https://github.com/emberjs/data/issues/4974)

2) Because we are stuck at `2.12.x`, we can't properly address this issue around natural/recurring id as the codebase between edge and 2.12.x has changed and produces different errors... sigh

Nevertheless I'll take a look! thanks

**Comment by erichonkanen** [comment] 2017-10-27 20:05
was able to upgrade to ember-data `2.17.x` so will continue to look at this issue now that using latest

**Comment by erichonkanen** [comment] 2017-11-12 05:16
@hjdivad @workmanw I just reverted our app to `ember-data 2.12.1` after spending many hours trying to work around this issue and when I revert back to `2.12.1` our app works with no errors! not sure what happened after 2.12+ but clearly some breaking changes that propagated forward... the issue happens when we remove a record that belongs to a `model.hasMany` and uses a composite id (natural key), and then we try to create a new record using the same composite id... so for now we have to go back to 2.12 until things stabilize :D

**Comment by erichonkanen** [comment] 2017-12-17 18:29
@hjdivad have you had a chance to visit this issue? we're getting closer to launching our application (1-2months) and right now this is a major blocker for us. One of our core features does not work past ember-data 2.12.X due to this bug. We are pinned to 2.12.X because that is the last version before the bug appears (works completely fine), but being that far back has other issues with other libraries. Please let me know your thoughts, thanks.

**Comment by erichonkanen** [comment] 2017-12-25 19:55
@bmac @hjdivad checking in if there has been any discussion on this issue? still outstanding as of `2.18.0-beta.1`
``````
"Assertion Failed: 'friendship' was saved to the server, but the response returned the new id 'burrito|taco', which has already been used with another record.'"```

**Comment by erichonkanen** [comment] 2017-12-25 20:05
related: https://github.com/emberjs/data/issues/4972

**Comment by erichonkanen** [comment] 2017-12-25 20:14
related: https://github.com/emberjs/data/issues/5006

**Comment by runspired** [comment] 2018-03-18 01:55
Closing this in favor of #1829

**Closed by runspired** 2018-03-18 01:55 UTC

**Comment by burritoIand** [comment] 2021-07-15 21:58
Running into this again in 2021 w/ember-data 3.20.5. It seems like using composite natural keys causes problems, particularly when creating/deleting/recreating a record with the same key (id) via websocket updates.

When a record is deleted via "record.destroyRecord()", and then later created again via "store.pushPayload(**recordData)", a new attempt to delete via "record.destroyRecord()" will throw with `Error: Attempted to handle event deleteRecord on <record:test1::test2> while in state root.deleted.saved. `
