### ISSUE TITLE
Ember Data creates duplicate records

### ISSUE THREAD

**Issue by ptmoy2** [emberjs/data#1829] opened 2014-03-22 15:20 UTC
Using Ember 1.4, EmberData beta 7 with default REST adapter.  I don't have a JSBIN because problem only shows when there's a success reply from the server.  Here's the scenario:
1. create 2 routes, and transition to the 1st route.
2. create a record: `amd = store.createRecord ('myModel', myRecord);`
3. save the newly created record: `md.save();`
   note - server must return a success for problem to show.  My server returned {status, 204}
4. now transition to route 2 via link-to or something else, then hit the browser's back key to go
   back to route 1.
5. when the 'back' button is pressed, Ember makes a GET request to the server.
   (why does Ember send a GET message when it already has it in the identity map?)
   Server replies with one instance of the saved record.  Ember displays two instances of
   the saved record.  Ember inspector also shows two instances.
6. Now if the browser refresh button is pressed, Ember sends a GET to the server.  Server replies
   with 1 record, and everything looks right again.

**Comment by grayt0r** [comment] 2015-01-09 17:09
I've run into the same problem with a `belongsTo` relationship and am struggling to find a workaround. I was hoping to be able to just remove the original record (i.e. the one without the id) but it appears to still have a link to the parent record (stored in `_implicitRelationships`) which causes the link between the duplicated record (i.e. the one with the id) and the parent record to be removed when the original record is deleted.

Simple(ish) example here: http://emberjs.jsbin.com/fevepogili/1/edit?html,js,output

Steps to recreate:
- Save a new task with a description and category
- Delete the first category in the list (which shouldn't be linked to anything anymore)
- The task in the list is no longer linked to a category

Am I missing something?

**Comment by jdjkelly** [comment] 2015-04-09 22:50
I am strongly in favour of @sandstrom 's suggested approach. Given that JSON API has de-milestoned "sideposting" from 1.0, we're going to be out of luck for a while.

**Comment by bmac** [comment] 2015-06-02 17:42
This issue is rather tricky because Ember Data doesn't have enough context to know if the relationship returned from the server is the same one that already exists on the record or if the existing relationship is a new client side record that the server doesn't know about yet. 

@igorT maybe the solution is to add a new method to the store that adapters can call to mark a record in the created state as saved.

**Comment by sandstrom** [comment] 2015-06-02 21:18
@bmac Yes, you are absolutely right, that's the meat of it. But I think using a transient id, mirrored back by the server, should be pretty straightforward way of solving this.

```
{
  "type": "articles",
  "id": "1",
  "attributes": {
    "title": "Rails is Omakase"
  },
  "meta": {
    "transientId": "c1001"
  }
}
```
*(example of what a payload could look like)*

**Comment by steffenbrem** [comment] 2015-06-22 14:56
I think it is not necessary to pass a client id or transient id to the server. You could also fix this by just replacing all the local records of the relationship with the ones returned from the server. What would be wrong with that approach?

**Comment by sandstrom** [comment] 2015-06-22 16:49
@steffenbrem It works if the server always include all of them. It would work for our use-case, but for larger collections the server may not return all associated records (e.g. a blog post with a thousand associated comments).

**Comment by jerel** [comment] 2015-07-08 18:08
I have also gotten duplicates in Ember Data with a far simpler use case than most of the examples here. Consider this:

``` js
this.socket.on('message', function(data) {
  store.push(store.normalize('message', data));
});
```
When multiple instances of a message (with the ID set on the server) stream in `store.push()` doesn't update the existing record but instead creates duplicates (all with the same ID). I'm not 100% certain that it's the same issue as this one but I figured I'd start here. Ember v1.13.3 and Data v1.13.4.

Working around it like this provides the behavior that the documentation states `store.push()` should have but it's obviously not ideal for many use cases.
``` js
this.socket.on('message', function(data) {
  store.peekAll('message').forEach(message => {
    if (message.id === data.id.toString()) {
      store.unloadRecord(message);
    }
  });
  store.push(store.normalize('message', data));
});
```

**Comment by sandstrom** [comment] 2015-07-09 07:46
@jerel This issue occurs when (1) an existing record without an id exist in the store, (2) this record is saved via a parent-child relationship (embedded) and (3) when returned from the server, with an id, this child document will get duplicated.

Perhaps using `hasRecordForId` before pushing will be helpful for you.

**Comment by florent-blanvillain** [comment] 2015-07-15 09:49
As a workaround, I just filter out the hasmany embedded records without ids after saving the parent model like this :

    // utils/workaround1829.js
    export default {
      filterHasmanyDuplicates: function (model, hasmanyName) {
        var recordList = model.get(hasmanyName), i, iterator;
        iterator = function (record) {
          if (record && !record.get('id')) {
            recordList.removeObject(record);
          }
        };
        for (i = 0; i < recordList.get('length'); i++) {
          recordList.forEach(eachFunc);
        }
      }
    };

Usage :

    // in some controller or route
    import workaround1829 from '../utils/workaround1829';
    ......
      actions: {
        save: function () {
            var model = this.get('model');
            model.save().then(function() (
                workaround1829.filterHasmanyDuplicates(model, 'children');
     .....

I don't know, maybe it can help someone as a simple quick & dirty workaround ?

**Comment by steffenbrem** [comment] 2015-08-24 16:09
Currently I have a workaround that requires no code in your controllers, routes (or whatever place you put your saving stuff).

Basically you need a mixin that you use on the parent model that contains the dependent child records:
```
import Ember from 'ember';

export default Ember.Mixin.create({
    save: function() {
        var promise = this._super(...arguments);
        promise.then(() => {
            this.eachRelationship((name, descriptor) => {
                if (descriptor.kind === 'hasMany') {
                    this.get(name).forEach((object) => {
                        if (object.get('isNew')) {
                            object.deleteRecord();
                        }
                    });
                }
            });
        });
        return promise;
    }
});
```

Then you can use this mixin in your models, like this:
```
import DS from 'ember-data';

export default DS.Model.extend(DependentRelationships, {
    tags: DS.hasMany('tag', { async: false })
});
```

Then when you save the above model, it will take care of the hasMany relationship if it got some new ones embedded. I hope this might be useful for someone, for me it is working well.

```
this.get('model').save(); // thats all you need to use now, you got some better client code now
```

**Comment by sandstrom** [comment] 2015-08-24 17:07
@steffenbrem Nice piece, thanks for sharing!

**Comment by steffenbrem** [comment] 2015-08-24 19:18
@sandstrom And for everyone else used the previous snippet I posted. I updated it, it contained a little bug. Now it stores all the records pre-save in a temporary array and after the save is completed THEN it will delete the records.

**Comment by antigremlin** [comment] 2015-09-03 11:22
@sandstrom I've run into this problem yesterday (although on an older version of ember-data). I came up with a manual solution which works the same way as your mixin. But the problem is the temporary records stay in the store after deletion. You can check with the ember developer tools.

The solution is to call `store.unloadRecord(record)` after deletion in the `then(...)` block. The temporary records are gone now.

**Comment by k-fish** [comment] 2015-09-09 22:43
I think the simplest way to fix this is to call `unloadRecord` on records that are `isNew` after receiving the response while saving the parent model with which they have a `hasMany` relationship. In theory, everything in the `hasMany` should have been persisted along with it's parent. When this isn't the case, you'd need a flag to disable this behaviour on the model for backends that don't include the `hasMany` records in the response or when the `hasMany` relationships don't get sent to the server.

**Comment by steffenbrem** [comment] 2015-09-09 22:45
@k-fish :+1:  that is exactly how I implemented it myself too, see the code above.

**Comment by k-fish** [comment] 2015-09-09 22:49
@steffenbrem haha whoops, I'm comment-reading-fatigued apparently. I think this should probably just be enabled by default (although it might break things now), then you can turn it off on a per-property basis on the parent.

**Comment by k-fish** [comment] 2015-09-09 22:51
@steffenbrem instead of loading the records into a temporary array, you can actually just index backwards to delete them `(i=length; i>=0; i--)` and do it in situ.

**Comment by steffenbrem** [comment] 2015-09-09 22:54
@k-fish Not sure how you would do that, if it improves the code I would like to know how you would implement it? Not familiar with that algorithm.

**Comment by k-fish** [comment] 2015-09-09 23:04
Usually you can't delete from an array because it causes concurrent modification problems (problems with the where the index points after you remove something), same with inserting. When you are just deleting however, you can start at the end of the array and remove objects.

```
save: function() {
 return this._super(...arguments).then(() => {
   this.eachRelationship((name, descriptor) => {
     if (descriptor.kind === 'hasMany') {
       for(idx=this.get(name).get('length') - 1; idx>=0; idx--) {
         const object=this.get(name)[idx]; 
         if (object.get('isNew')) {
           object.deleteRecord();
         }
       });
     }
   });
 });
}
```
**Warning; this is just an example, I haven't tested this**

**Comment by amk221** [comment] 2015-09-29 11:18
As @grayt0r mentions, the fixes mentioned here are not sufficient. They also need to clear up the private property `_implicitRelationships` for them to actually work.

Here is a [passing test](http://ember-twiddle.com/7691aa55c2229df0dc7c?numColumns=1) with the fix. Comment out the lines 35-36 and the tests will fail.

**Comment by jcbvm** [comment] 2016-02-05 19:30
What's the status of this issue? The bug is becoming really annoying.

**Comment by klclee** [comment] 2016-02-11 14:24
@steffenbrem thanks mate.. :+1:  the mixin works like a charm

**Comment by steffenbrem** [comment] 2016-02-11 14:25
@klclee Np :+1: Still working great for my project

**Comment by olivierchatry** [comment] 2016-02-11 14:26
I had a similar issue, not sure if it is related, but I got a pull request for it :
https://github.com/emberjs/data/pull/4154

**Comment by jcbvm** [comment] 2016-03-16 13:12
Looks like in 2.4.x we have to find another workaround

**Comment by pangratz** [comment] 2016-03-16 13:14
@jcbvm can you try `canary`? It seems that PR #4154 is not included in `2.4.x` and also not in `2.5.0-beta.1`, but maybe this fixes the issue you're having...

**Comment by jcbvm** [comment] 2016-03-16 13:42
@pangratz nope, issue still exists on canary

**Comment by pangratz** [comment] 2016-03-16 13:43
@jcbvm :cry:, thanks for checking though

**Comment by steffenbrem** [comment] 2016-03-16 14:11
Note that PR #4154 expects you to provide a client side generated id. If you look at the test, https://github.com/emberjs/data/pull/4154/files#diff-f5099af3b5cad3fc343f3f4b73eb3c97R449, you can see that.

This issue is more about what to do with embedded records that had **NO** client side generated id. I am currently not aware of any work for that in core ember data, for now I think the only solution is the code snippet I posted (https://github.com/emberjs/data/issues/1829#issuecomment-134270337).

**Comment by jcbvm** [comment] 2016-03-16 14:20
Just be careful for nested embedded relationships where save is not called on the model which has the embedded relationships, but a parent one. We have to do the workaround recursively.

**Comment by sandstrom** [comment] 2016-05-24 06:09
This article outlines the current state of saving embedded records with the JSON-API adapter:
http://emberigniter.com/saving-models-relationships-json-api/

It favors transient id to correlate records, [which I agree with](https://github.com/emberjs/data/issues/1829#issuecomment-108101811).

Just thought I'd mention the article since it's related to this issue.

**Comment by Baukereg** [comment] 2016-07-04 12:48
@steffenbrem 

Thank you for the workaround! My problem with saving embedded records extends to include not just hasMany relations but belongsTo relations as well. So I modified your workaround to handle that as well. But way more complicated because this.get() on a belongsTo relation returns a promise (unlike forEach on a hasMany relation). I added comments to make sense of it all.

```
save: function() {
  let hasManyRecords = [], belongsToRecords = {};
  
  this.eachRelationship((name, descriptor) => {
    if (descriptor.kind === 'hasMany') {
      this.get(name).forEach((record) => {
        if (record.get('isNew')) {
          hasManyRecords.push(record);
        }
      });
    }
    
    if (descriptor.kind === 'belongsTo' && this.get(name).get('isNew')) {
      belongsToRecords[name] = this.get(name);
    }
  });
  
  let promise = this._super(...arguments);
  promise.then(() => {
    
    hasManyRecords.forEach((record) => {
      record.deleteRecord();
    });
    
    // Since this.get() on a belongsTo relation returns a promise,
    // use a hash promise.
    Ember.RSVP.hash(belongsToRecords).then((hash) => {
      Object.keys(hash).forEach((name) => {
        this.get(name).then((newRecord) => {
          
          // Duplicate data from the new record.
          const recordId = newRecord.get('id');
          let pushData = {};
          pushData[name] = [ newRecord.toJSON({ includeId:true }) ];
          
          // Reset the belongsTo relation on the model.
          this.set(name, null);
          
          // Delete any of the existing records.
          hash[name].deleteRecord();
          newRecord.deleteRecord();
          
          Ember.run.scheduleOnce('sync', this, () => {
            // Push data to store.
            this.store.pushPayload(pushData);
            const finalRecord = this.store.peekRecord(name, recordId);
            
            // Since records created with pushPayload are considered dirty,
            // let's rollbackAttributes. All data on record will persist.
            finalRecord.rollbackAttributes();
            
            // Set the belongsTo relation.
            this.set(name, finalRecord);
          });
        });
      });
    });
  });
  
  return promise;
}
```

Still not the perfect solution, so be cautious when using it.

**Comment by wecc** [comment] 2016-10-21 14:05
Related: https://github.com/emberjs/rfcs/pull/173

**Comment by kog13** [comment] 2016-12-01 19:01
I know there is a proposal for a fix for this at the moment just wanted to share. Was able to sort of 'sidestep' the issue by clearing out the relationships within the model serializer function and then rely on the returned post data from the server to repopulate it. Obviously less than ideal since if the server fails to return the relationships your up a creek.

**Comment by toovy** [comment] 2017-02-20 14:38
I can confirm this issue in 2.11.1.

in my case I'm saving a book with 2 pages (2 pages in store). After this saving I transition to a new route that shows the pages. A GET request is triggered and suddenly 4 pages are in the store (including 2 duplicates). The pages from the server have the exact same dataset. So the question is why ember-data does not detect that they are duplicates (using the ID would be enough to detect the duplicates).

**Comment by runspired** [comment] 2017-02-22 08:02
It does, it's likely when you saved you didn't add the IDs the server gave to these records to the records you were saving.

**Comment by toovy** [comment] 2017-02-22 08:06
@runspired There is a GET and a POST, both return the same json object, both with the same ID. Or did I misunderstand you?

**Comment by runspired** [comment] 2017-02-22 15:32
@toovy you did. From what you've said, it seems unlikely that this timing bug (where a new record is received by a GET request or socket update before the response for it's save request has been received) is your bug. If you'd like, ping me in the #ember-data channel on the ember slack and I can spend a little bit of time helping you figure out what's disconnected.

**Comment by toovy** [comment] 2017-02-22 15:42
@runspired I've checked the network and you are right, it is an timing issue. In my case a computed recomputes and thus sends the GET directly when saving. In some cases the GET returns before the POST - timing issue. I could resolve it, but nevertheless I would expect ember-data to detect this - I might be wrong. Thanks for your help.

**Comment by MajorTal** [comment] 2017-02-23 09:11
Why can't Ember data prevent this from happening? It is super annoying.

Thanks,

Tal Weiss
+972-54-7476276
Skype: major.tal
Twitter: @majortal

**Comment by abobwhite** [comment] 2017-03-06 18:04
I just ran across this - how has this not been prioritized in 3 years? I will try out @steffenbrem 's workaround, though! Thanks for those who have provided clean global solutions like this.

**Comment by runspired** [comment] 2017-03-06 19:16
> how has this not been prioritized in 3 years

@abobwhite because it's a super edge-y case that only affect folks with a race condition particular to their Application's API structure, the only general solution to which is to implement a client-id that the server would need to know about and reflect, which is something fairly trivial to do in user-space already.

**Comment by abobwhite** [comment] 2017-03-06 19:23
Thanks @runspired. I don't see this as an edge case. I have a model `content` which defines `hasMany` to `tag-groups` which I've defined with the `EmbeddedRecordsMixin` as `embedded: 'always'`....these `tag-group`s don't make sense outside of being inside another model and while I could write a separate API to save/update/delete them by themselves, it seems silly. So the API I consume expects those operations to be done when saving/updating `content` but relies on the `id` of `tag-group` to know what has changed when updating. 

I'm confused how this has to do with an app-specific race condition....?

I have a model, `content`. I have a new `tag-group` called `tagGroup`. I add it via `content.get('tagGroups').addObject(tagGroup)`....then I call `content.save()`. Pretty straightforward. Am I misunderstanding something?

**Comment by steffenbrem** [comment] 2017-03-07 11:16
@abobwhite The main issue is that the local objects you have can't be mapped to the server response (since you don't have ids on your local objects). This makes it very hard to make sure the proper local objects get merged with the new ones coming from the server. Instead ember data is just creating new local objects, were this whole issue is about. Now the best solution I came up with was simply removing the local objects when new ones came in, simply replacing the your old objects. Since the old records gets destroyed, this isn't a good solution to put into Ember Data directly either, it can have nasty side effects. 

If you can implement client sided ids like @runspired mentioned, I would go that route, much cleaner! Otherwise you have to remove the old local records and make peace with the fact the whole instance gets replaced.

**Comment by abobwhite** [comment] 2017-03-07 12:38
Thanks @steffenbrem . I will make peace with your solution for now. Thanks for sharing it :)

**Comment by akaravashkin** [comment] 2017-04-07 09:12
Thanks @abobwhite! This solution works prefect for me:

` _saveSuccess(savedRecord) {
    get(savedRecord, 'hasManyRecords').forEach(record => {
      if (get(record, 'hasDirtyAttributes')) {
        record.deleteRecord();
      }
    });`

**Comment by jamesarosen** [comment] 2017-07-06 21:23
On ember-data@2.12.2, I have found that the `parent.get('children')` array is actually correct, but that there are orphaned `child` objects in the ember-data `store`. Those `child` objects have a `parent` reference that is to a PromiseProxy whose `content` is the `parent`. So the following would work for me:

```js
// models/parent.js

save() {
  return this._super().then(() => {
    this.get('store')
    .peekAll('child')
    .filterBy('isNew')
    .filter((child) => child.get('parent.content') === this)
    .invoke('unloadRecord');
  });
}
```

**Comment by abarax** [comment] 2017-09-28 00:03
Is there any update on this? This bug has existing for 3 years.

**Comment by sandstrom** [comment] 2017-09-28 08:04
@abarax There are [discussions in the json-api group](https://github.com/json-api/json-api/issues/1207) which would help here (if/when they land). But it would also be possible to make changes to Ember Data without waiting for JSON api to iron things out (for example via the meta fields).

If you have time for a PR I'm happy to discuss what a likely solution could look like.

**Comment by runspired** [comment] 2017-09-29 04:30
I think the thing is that this issue is extremely hard to solve generally as it requires a server side contract, and it's trivial to make your server side contract work correctly in Ember data today if you have one.

**Comment by jamesarosen** [comment] 2017-09-29 18:29
> it's trivial to make your server side contract work correctly in Ember data today if you have one

It is? Do you mean client-generated GUIDs?

**Comment by sandstrom** [comment] 2017-09-30 11:29
@jamesarosen I think he's saying (1) it's hard to solve without a client/server contract (e.g. updated json-api spec) and (2) if you have a client/server contract in place, the adjustments needed to ember data is fairly trivial.

*(please correct me if my interpretation of what you ment is incorrect runspired)*

**Comment by localpcguy** [comment] 2018-04-03 16:58
I've come to this bug a couple times now in the last few months via searches, and unfortunately often can't do anything about the way the API works. So I end up needing to do workarounds to make Ember Data "happy" - and workarounds often are buggy or rely on private APIs unfortunately. 

Saying "just fix your server API and then it's trivial" isn't always a viable answer - some (many?) don't control both sides, I don't think that can be assumed from people working with Ember Data. 

Ember Data seems great as long as everything is as expected, and I do appreciate all the hard work.

**Comment by sandstrom** [comment] 2018-04-04 09:05
@localpcguy This PR would add the necessary changes needed in JSON-API (the wire format the Ember Data is usually using) that will enable fixing this Ember Data issue (duplicate records).

https://github.com/json-api/json-api/pull/1244

Feel free to write your support in that PR, or ask if there are any obstacles left before it could be moved into the spec 😄 (I've done that myself, I think it would be great if that PR would be merged)

**Comment by Nnaha** [comment] 2018-06-19 20:19
I WAS HEARTBROKEN AND { DR_MACK@ YAHOO. COM } BROUGHT MY LOVER BACK AFTER 3 DAYS, ( UNBELIEVABLE ) …

**Closed** 2019-07-26 22:59 UTC
