### ISSUE TITLE
snapshot.attr('meta') returns deprecations

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#2973] opened 2015-04-03 14:02 UTC
Here's my code:

```js
import DS from 'ember-data';

var ApplicationSerializer = DS.RESTSerializer.extend({
  serializeIntoHash: function(hash, type, snapshot, options) {
    // not sure if super is needed anymore..
    this._super(hash, type, snapshot, options);
    hash.meta = snapshot.attr('meta');
  }
});

export default ApplicationSerializer;
```

I'm using ember 1.11 and ed beta.16.1

The deprecations I get are:

```no-highlight
DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.
        at Ember.defineProperty.get [as constructor] (http://localhost:3000/assets/vendor.js:67872:21)
        at CallSiteToString (native)
        at Error.EmberError (http://localhost:3000/assets/vendor.js:22571:34)
        at ember$data$lib$system$snapshot$$Snapshot.attr (http://localhost:3000/assets/vendor.js:67956:15)
        at serializeIntoHash (http://localhost:3000/assets/nycbb.js:17906:28)
        at ember$data$lib$system$adapter$$Adapter.extend.createRecord (http://localhost:3000/assets/vendor.js:61845:20)
        at ember$data$lib$system$store$$_commit (http://localhost:3000/assets/vendor.js:71681:39)
        at null.<anonymous> (http://localhost:3000/assets/vendor.js:70937:28)
        at Array.forEach (native)

DEPRECATION: Using DS.Snapshot.get() is deprecated. Use .attr(), .belongsTo() or .hasMany() instead.
        at ember$data$lib$system$snapshot$$Snapshot.get (http://localhost:3000/assets/vendor.js:68148:15)
        at eval (eval at evaluate (unknown source), <anonymous>:1:6)
        at Object.InjectedScript._evaluateOn (<anonymous>:847:55)
        at Object.InjectedScript._evaluateAndWrap (<anonymous>:780:34)
        at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:906:21)
        at ember$data$lib$system$snapshot$$Snapshot.attr (http://localhost:3000/assets/vendor.js:67956:15)
        at serializeIntoHash (http://localhost:3000/assets/nycbb.js:17906:28)
        at ember$data$lib$system$adapter$$Adapter.extend.createRecord (http://localhost:3000/assets/vendor.js:61845:20)
        at ember$data$lib$system$store$$_commit (http://localhost:3000/assets/vendor.js:71681:39)
```

**Comment by bmac** [comment] 2015-04-03 14:05
Thanks @knownasilya. @wecc do you have time to look into this?

**Comment by knownasilya** [comment] 2015-04-03 14:20
Seems like `attr` is not the right way to get the `meta` object anymore..

**Comment by knownasilya** [comment] 2015-04-03 17:55
If I do `snapshot.record.get('meta')` I get the following error:

```no-highlight
TypeError: Cannot read property '_attributes' of undefined
    at ember$data$lib$system$model$attributes$$hasValue (http://localhost:3000/assets/vendor.js:69650:27)
    at http://localhost:3000/assets/vendor.js:69698:20
    at jQuery.param.add (http://localhost:3000/assets/vendor.js:9705:41)
    at buildParams (http://localhost:3000/assets/vendor.js:9694:3)
    at buildParams (http://localhost:3000/assets/vendor.js:9689:4)
    at Function.jQuery.param (http://localhost:3000/assets/vendor.js:9725:4)
    at Function.jQuery.extend.ajax (http://localhost:3000/assets/vendor.js:9296:20)
    at http://localhost:3000/assets/nycbb.js:26791:26
    at initializePromise (http://localhost:3000/assets/vendor.js:57494:9)
    at new Promise (http://localhost:3000/assets/vendor.js:59122:9)
```

**Comment by wecc** [comment] 2015-04-03 18:13
Is `meta` defined as an attribute on the model? If not, it's not going to be available using `snapshot.attr()`.

**Comment by knownasilya** [comment] 2015-04-03 18:14
@wecc this is the `meta` object that is in the root of the server's response json object, the one that ED previously allowed to fetch via `record.get('meta')`.

**Comment by wecc** [comment] 2015-04-03 18:28
I'm confused :confused: If you return a `meta` object in the root of your server's JSON response it will be set using `store.setMetadataFor()`, which is per type. At what version was that data available using `record.get('meta')`?

**Comment by knownasilya** [comment] 2015-04-03 18:31
beta.15

**Comment by wecc** [comment] 2015-04-03 18:40
I'm unable to reproduce that using beta 15, see: http://emberjs.jsbin.com/selitalafi/1/edit

From what I know there is not really any concept of per-record metadata in ED?

**Comment by knownasilya** [comment] 2015-04-03 18:46
It wasn't per record, but you can get it off the record.

**Comment by igorT** [comment] 2015-04-12 06:23
I am not sure we should encourage getting the meta from the record, meta for a specific record doesn't make too much sense IMHO. But maybe its ok? If it is we should explicitly support it and also expose it via the snapshot. @knownasilya whats your use case for per record meta?

**Comment by igorT** [comment] 2015-04-12 06:52
Not sure whats up with the record.get('meta') erroring out, seems unrelated?

**Comment by elidupuis** [comment] 2015-08-06 12:44
Any further thoughts on per record meta data? JSONAPI supports it, that's the only reason we started looking into it.

Our use case is similar to the top level meta data example of `total` number of records in a paginated payload; we have `count` attributes for `hasMany` relationships. After looking at JSONAPI we felt those made more sense under `meta` instead of as direct attributes on the model.

For example, on a `blogPost` record, you might have `commentCount` and `relatedPostCount`. Those represent the number of related `comment ` and `blogPost` models from `hasMany` relationships.

**Comment by wecc** [comment] 2015-09-16 22:38
Closing this as meta per record has never been a thing previously but we'll implement additional meta support as per the JSON API specification. It's being tracked in #2905

**Closed by wecc** 2015-09-16 22:38 UTC
