### ISSUE TITLE
MU blueprints writing to classic location

### ISSUE THREAD

**Issue by evoactivity** [emberjs/data#5772] opened 2018-12-04 15:24 UTC
### Reproduction

https://github.com/evoactivity/mu-ed-blueprint-problem

### Description

Using module unification it looks like the ember-data generators should be working. I've tested an adapter, serializer, model and transform. Model seemed to be the only one that actually worked as expected, adapters, serializers and transforms all had similar output as below.

```cli
installing serializer
  create app/serializers/application.js
installing serializer-test
  create src/data/models/application/serializer-test.js
````

I've seen tests that should fail in this scenario and people reporting they worked correctly so I'm not 100% sure this directly relates to the blueprints, so if someone can check out my repo above and see if they get the same issue running `ember g adapter something` that would be really helpful.

### Versions

```cli
ember-source@3.6.0-canary
ember-cli@3.6.0-beta.1
ember-data@3.6.0-beta.1
```

**Comment by dcyriller** [comment] 2018-12-04 17:43
I can reproduce the issue with the following versions:
```
ember-source@3.5.1
ember-cli@3.5.1
ember-data@master
```

**Comment by dcyriller** [comment] 2018-12-04 23:09
Digging a bit into it, I found out two issues.

First, it seems that the blueprint test generation (`adapter-test.js` file) is broken from version 3.2.x (to 3.6.x). It is resolved by https://github.com/emberjs/data/commit/f9876d600d9ca1ff9dc9a57283cfee890fb95bd8. But this is not released yet (incl. in 3.6.0-beta.1). Using `github:emberjs/data#master`, the issue is fixed though.

Second, it looks like we have a conflict between `ember-data` and `ember-decorators` blueprints. Indeed, if you remove the decorators from your project, the blueprints will properly be generated. This is not resolved yet. Not sure about that, but the needed PR would be on these files: https://github.com/ember-decorators/ember-decorators/tree/74e34fa5792bfc9cc16d55bf8134884cfffc5dda/packages/-ember-decorators/blueprints

**Comment by evoactivity** [comment] 2018-12-05 10:04
Thanks for digging into this. Just found this is being tracked in ember-decorators https://github.com/ember-decorators/ember-decorators/issues/299

**Comment by runspired** [comment] 2019-05-14 22:58
I believe we can close this now as the fix on our side was released.

**Closed by runspired** 2019-05-14 22:58 UTC
