### ISSUE TITLE
PROPOSAL - Waiting to unlock 2.14.x we could fix the "prod build" stuff bug in a new 2.13.3 (keeping the really good stability of 2.13.2).

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/data#5158] opened 2017-08-28 21:27 UTC
PROPOSAL - Waiting to unlock _2.14.x_ could we fix the "prod build" stuff bug in a new 2.13.3 (keeping the really good stability of 2.13.2)?

We are using `ember-data 2.13.2` with satisfaction (the main problem in `2.14.10`, current latest, is [this serious bug](https://github.com/emberjs/data/issues/5143) which slow down all the SPA app).

We can stay on `2.13.2`, but we have this problem in "**prod**" with **Safari**:

```
[Error] SyntaxError: Cannot declare a let variable twice: 't'.
	(Anonymous function) (vendor-04123e2af41e8ca695e8f6380cd9d4d6.js:3930)
[Error] ReferenceError: Can't find variable: define
	Global code (myapp-ca22c509dc86e516cff8fbd9ef761236.js:2)
```

If we use (even only) 2.14.0 the problem disappear.

Can we fix this (I think it can be a quick fix of dependencies? Or am I wrong?) in a new `2.13.3`?

Maybe something related to **ember-data dependencies** like `ember-cli-babel`?

@stefanpenner, @mmun I rely on you.

**Comment by BryanCrotaz** [comment] 2017-11-19 23:49
Try PR #5257 and see if that fixes your links problems

**Comment by runspired** [comment] 2018-03-18 01:34
It is unclear what bug is being reported here, it seems either your app is not transpiling correctly or an invalid declaration is present or both. Closing this since there's not enough information to reproduce nor a clear idea of what we would be reproducing.

**Closed by runspired** 2018-03-18 01:34 UTC
