### ISSUE TITLE
TypeError: Ember.A(...).mapBy is not a function

### ISSUE THREAD

**Issue by billpull** [emberjs/data#3466] opened 2015-06-29 19:56 UTC
Getting this error after loading a payload via `store.query()`

`TypeError: Ember.A(...).mapBy is not a function
    at ember$data$lib$system$record$arrays$record$array$$default.extend.loadRecords (adapter-populated-record-array.js:54)`

Ember: 1.13.2
Ember-Data: 1.13.4

**Comment by wecc** [comment] 2015-06-29 23:02
Hey @billpull! What does your payload look like and what serializer are you using? Would you be able to put together a JSBin demonstrating this issue? Makes it much easier to debug.

**Comment by liamcoau** [comment] 2015-07-03 16:19
@wecc I'm getting this as well. It's a blocking issue and I can't load any routes. 
![screenshot from 2015-07-03 13 16 32](https://cloud.githubusercontent.com/assets/1975820/8502403/dad94028-2185-11e5-8e0a-78ead0062cec.png)
```
import Ember from "ember";
import DS from "ember-data";

export default DS.RESTSerializer.extend({
	isNewSerializerAPI: true,

	normalizeResponse: function (store, type, payload, id, requestType) {
		//console.log('normalizeResponse', arguments);
		
		for (var key in payload.data.links) {
			if (typeof payload.data.links[key] == "object")
				payload.data.links[key] = payload.data.links[key].related;
		}

		// Example type: Skilltapper@model:user:
		// Goal is to just get "user"
		var model = type.toString();
		var new_payload = new Object();

		Ember.assert("First part of type is not 'skilltapper@model:' in <" + model + ">", model.slice(0,18) == "skilltapper@model:");
		Ember.assert("Last char of type is not ':' in <" + model + ">", model.slice(model.length-1) == ":");
		
		model = model.slice(18, model.length - 1);
		new_payload[model] = payload.data;

		return this._super(store, type, new_payload, id, requestType);
	},

	normalize: function (typeClass, hash, prop) {
		console.log("normalize");
		console.log(hash);
		return this._super(typeClass, hash, prop);
	},

	normalizeHash: {
		links: function (hash) {
			console.log("Got the links hash");
			return hash;
		}
	}
});
```
here's the serializer I have, also, Ember @1.13.0 and Ember-Data @1.13.4 and ember-cli @0.2.7

**Comment by liamcoau** [comment] 2015-07-03 17:21
Perhaps the issue is that records should be an array but here it is a class?
![screenshot from 2015-07-03 14 20 52](https://cloud.githubusercontent.com/assets/1975820/8503017/cb3f5cf2-218e-11e5-93c5-220d4eba69ed.png)

**Comment by liamcoau** [comment] 2015-07-03 18:52
@billpull and @wecc Issue resolved by using queryRecord instead of query. It was not very clear that I should have used queryRecord instead, it just said find was deprecated and I should switch to query.

**Comment by jorgelainfiesta** [comment] 2015-07-04 18:57
@liamcoau I was also getting this error when using `query`, but when I tried `queryRecord` I get an error saying 
```
Uncaught Error: Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord`
```
I am using the default `RESTAdapter` with no custom serializer or anything fancy. Did you have to implemente `queryRecord` by yourself?

**Comment by liamcoau** [comment] 2015-07-04 19:27
Yes, I implemented queryRecord on my adapter. I also implemented urlForQueryRecord.

**Comment by jorgelainfiesta** [comment] 2015-07-04 19:53
@liamcoau thanks, I'll do that then. I thought it was a default method in RESTAdapter.

**Comment by billpull** [comment] 2015-07-05 16:41
@liamcoau can you link me to an example of your adapter implementation

**Comment by liamcoau** [comment] 2015-07-05 17:42
Here's the full adapter:
http://pastebin.com/1EJRygXF

Here's an example of how it's called:
```
var user = _this.store.queryRecord("user", {
  "id": _this.session.content.auth_id,
  "include": "skills,job_title"
});
```
I had to do some "munging" with the id, since I needed to pass that along but the third parameter is a snapshot (not actually sure how that's supposed to be used?)...
Anyways it produces a url such as:
http://example.com/user/2lkj3l5l2jkl25j5?access_token=dkasjf43j3224256swrte&include=skills,job_title

**Comment by liamcoau** [comment] 2015-07-05 18:08
@billpull also you should avoid this.session.content.etc if you can in favour of session.get("etc")

**Comment by wecc** [comment] 2015-07-07 22:59
`queryRecord` should have been implemented in `RESTAdapter`, sorry about that. It's tracked in #3514

We should probably assert an array in `query` or `AdapterPopulatedRecordArray.loadRecords`.

@liamcoau would you like to provide a PR adding an assert?

**Comment by liamcoau** [comment] 2015-07-08 04:48
Sure!

**Comment by IsaiahJTurner** [comment] 2015-09-30 21:35
Is there a solution to this?

**Comment by bmac** [comment] 2015-10-13 14:48
@IsaiahJTurner what version of Ember Data are you using? I believe this bug was fixed in  ember-data 1.13.7.

**Comment by btecu** [comment] 2015-10-15 17:13
I'm getting this error as well when I use `query` but `findAll` doesn't trigger the error.
Ember Data 2.x.

**Comment by bmac** [comment] 2015-10-15 17:18
@btecu do you mind sharing a stack trace for this error?

**Comment by btecu** [comment] 2015-10-15 17:25
```
Error while processing route: photos Ember.A(...).mapBy is not a function TypeError: Ember.A(...).mapBy is not a function
    at ember$data$lib$system$record$arrays$record$array$$default.extend.loadRecords (http://dev/assets/vendor.js:58891:47)
    at http://dev/assets/vendor.js:58509:21
    at tryCatch (http://dev/assets/vendor.js:51508:14)
    at invokeCallback (http://dev/assets/vendor.js:51523:15)
    at publish (http://dev/assets/vendor.js:51491:9)
    at http://dev/assets/vendor.js:30141:7
    at Queue.invoke (http://dev/assets/vendor.js:1224:16)
    at Object.Queue.flush (http://dev/assets/vendor.js:1288:11)
    at Object.DeferredActionQueues.flush (http://dev/assets/vendor.js:1089:17)
    at Object.Backburner.end (http://dev/assets/vendor.js:378:25)

TypeError: Ember.A(...).mapBy is not a function
    at ember$data$lib$system$record$arrays$record$array$$default.extend.loadRecords (adapter-populated-record-array.js:56)
    at finders.js:160
    at tryCatch (ember.debug.js:51306)
    at invokeCallback (ember.debug.js:51321)
    at publish (ember.debug.js:51289)
    at ember.debug.js:29939
    at Queue.invoke (ember.debug.js:1022)
    at Object.Queue.flush (ember.debug.js:1086)
    at Object.DeferredActionQueues.flush (ember.debug.js:887)
    at Object.Backburner.end (ember.debug.js:176)
```

**Comment by btecu** [comment] 2015-10-15 17:29
@bmac If the stack trace is not enough, I could probably create a repository with this issue.

**Closed** 2015-10-16 12:04 UTC
