### ISSUE TITLE
Relationship data lost when a record is unloaded

### ISSUE THREAD

**Issue by aquamme** [emberjs/data#3020] opened 2015-04-22 17:47 UTC
Assume that 'Car' hasMany 'Part', and 'Part' hasMany 'Car'. If a part is unloaded, then loaded again into the store, the information about its relationship to car is lost. I would expect a record's relationship data to survive as long as one of the records in the relationship still exists in the store (at least in the case where the relationship is declared on both models). [Here is a jsbin illustrating the issue](http://emberjs.jsbin.com/xugomukezi/1/edit). I can PR a failing test if this is behavior that should be changed.

**Comment by bmac** [comment] 2015-05-06 21:20
@igorT will your work on the https://github.com/emberjs/data/tree/references have any impact on this issue?

**Comment by aquamme** [comment] 2015-06-23 14:42
Looks like this issue will be covered by #3296

**Comment by workmanw** [comment] 2015-10-23 13:03
I too have been experiencing this issue. Actually, it often results in a crash when the 'part' is later reloaded into the store. The stack looks like:

```
    at new Error (native)
    at Error.EmberError (https://localhost:4200/assets/vendor.js:26216:21)
    at Object._emberMetalCore.default.assert (https://localhost:4200/assets/vendor.js:14935:13)
    at Object.set (https://localhost:4200/assets/vendor.js:30394:32)
    at exports.default._emberMetalMixin.Mixin.create.set (https://localhost:4200/assets/vendor.js:46190:31)
    at Ember.Object.extend.flushCanonical (https://localhost:4200/assets/vendor.js:79683:14)
    at ember$data$lib$system$relationships$state$has$many$$ManyRelationship.flushCanonical (https://localhost:4200/assets/vendor.js:80009:22)
    at Queue.invoke (https://localhost:4200/assets/vendor.js:10439:16)
    at Object.Queue.flush (https://localhost:4200/assets/vendor.js:10503:11)
    at Object.DeferredActionQueues.flush (https://localhost:4200/assets/vendor.js:10304:17)
```

In my case, we unload some data as the user is exiting routes. If they return to the same route, as the data is being pushed back into the store, `flushCanonical` ends up called on an unloaded record.

Did you ever find a workaround, other than not unloading?

**Comment by wecc** [comment] 2016-10-22 15:51
I'm still able to reproduce this using Ember `release` and Ember Data `canary`, see https://ember-twiddle.com/1960841c246dad18f83389a0b1e5de18

This should most likely be fixed by #4593

**Comment by hjdivad** [comment] 2016-10-22 17:18
@wecc #4593 should fix this issue although it doesn't completely fix the state of relationships on unload.

But for `unload` followed by `pushPayload` it does.  see [this test](https://github.com/hjdivad/data/blob/better-unload/tests/integration/records/unload-test.js#L233-L289)

**Comment by runspired** [comment] 2018-04-18 03:38
If this is still a problem we should open a new issue. The recent `links` refactor give me much more confidence that we don't lose information on unload; however, if there is still a case where we do it will be relatively simple to resolve at this point with the new flags that are in place for tracking relationship state internally.

**Closed by runspired** 2018-04-18 03:38 UTC
