### ISSUE TITLE
isUpdating is broken since 2.4.3

### ISSUE THREAD

**Issue by kbbpartners** [emberjs/data#4339] opened 2016-04-17 03:59 UTC
Prior to version 2.5.0, we used `isUpdating` to determine the loading state of an ArrayProxy resulting from `findAll`. The reason for using `isUpdating` is that other states, such as `isFulfilled`, were not triggered during background loads.

To be clear, since version 2.5.0, `isUpdating` returns false when it used to return true. It used to return true when: (1) the `findAll` promise was resolving, where `reload: true` was set, and (2) the records were being (re)loaded in the background for ordinary `findAll` operations.

Did we miss an API change, or perhaps is there a better way of tracking the loading state of an ArrayProxy resulting from a find operation?

**Comment by pangratz** [comment] 2016-05-16 10:33
Looks like this regression has been introduced [in #4316](https://github.com/emberjs/data/pull/4316/files#diff-fd4c34d9a34dfde73cd3413128a3c973L1009). I am working on a fix.

**Comment by pangratz** [comment] 2016-05-16 11:14
@kbbpartners this regression should be fixed once #4386 is merged and a new version `2.5.3` is released. Many thanks for reporting this and sorry for the inconvenience.

**Closed** 2016-05-17 20:36 UTC
Labels: Bug, Regression

**Comment by pangratz** [comment] 2016-05-18 06:33
@kbbpartners FYI, `ember-data` `v2.5.3` has been released...

**Comment by kbbpartners** [comment] 2016-05-18 06:48
Looks good. Our loading indicators are back! Thank you.
