### ISSUE TITLE
Expected a stable identifier when unloading a record with Embedded Records

### ISSUE THREAD

**Issue by amk221** [emberjs/data#8398] opened 2023-01-18 10:09 UTC
### Reproduction
Test: https://github.com/amk221/-ember-data-embedded-rel-stable-id/commit/c27585cbd02ded7cc58f114af0cb66bd7ded979e#diff-06365fffd34e07c5b67034ec9384f2090ef54fd9a4d69ba4bb6f7807bd917717

### Description
`model.unloadRecord()` outputs `Expected a stable identifier`

### Versions
```cli
npm list ember-source && npm list ember-cli && npm list --pattern ember-data
example@0.0.0 ~/Desktop/example
├─┬ @ember/test-helpers@2.9.3
│ ├─┬ @embroider/util@1.9.0
│ │ └── ember-source@4.9.3 deduped
│ └── ember-source@4.9.3 deduped
├─┬ ember-data@4.9.1
│ └─┬ @ember-data/model@4.9.1
│   └─┬ ember-cached-decorator-polyfill@1.0.1
│     └── ember-source@4.9.3 deduped
├─┬ ember-qunit@6.1.1
│ └── ember-source@4.9.3 deduped
└── ember-source@4.9.3

example@0.0.0 ~/Desktop/example
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@4.9.2 deduped
└── ember-cli@4.9.2

example@0.0.0 ~/Desktop/example
└── ember-data@4.9.1
```

**Comment by runspired** [comment] 2023-02-25 04:08
embedded records have no affect on the store at all here, they are a serializer only concern. Records in the store are always received as top-level resources when using the default cache etc. If the mixin is required for the reproduction then likely the issue is the mixin is normalizing the data incorrectly.

unloadRecord is not synchronous. The test needs to `await settled()` before asserting against unloaded state.

**Comment by runspired** [comment] 2023-04-06 22:58
@amk221 @mjanjic01 any more info? else I think I'll close this as I suspect this is a user setup issue.

**Comment by mjanjic01** [comment] 2023-04-07 05:11
@runspired I'll try to reproduce this in a minimal repo next week. Will let you know how it goes

**Closed** 2023-04-12 16:32 UTC
Labels: Needs Bug Verification
