### ISSUE TITLE
hasMany relationship created the record with id: null

### ISSUE THREAD

**Issue by Shajansheriff** [emberjs/data#5083] opened 2017-07-23 07:28 UTC
We've two models Contact and phones. In contact model, we got  `phones: hasMany('phone'),` . When we try to create a contact record with multiple phones, the records are created with id:null. Once the response from the server is came back the id is not still resolved on contrary it created duplicate records.
Phone Model: 
`number: attr('string'),
  type: attr('string')`
For Example: In store, contact contains two phones [{id: null, number: +543210, type: 'main'}, {id: null, number: +543211, type: 'other'}]. Once the we got the response from backend, phone records will look like this  
`[{id: null, number: +543210, type: 'main'}, {id: null, number: +543211, type: 'other'},{id: 1, number: +543210, type: 'main'}, {id: 2, number: +543211, type: 'other'}]`
**Issue:** Duplicate records with id and without ids.
**Question:** How ember will map the response correctly with already created record with id:null? Or how to remove the null records to avoid duplication?

**Comment by JeffLuong** [comment] 2018-03-27 15:33
@Shajansheriff  Not sure if you still have this issue, but i've recently ran into a similar issue, but it was for `async` relationships. Are you passing `async: true` to your `phones`? If so, it may be that you're accessing the records from the `PromiseManyArray` and not the actual `ManyArray`.

If that's the case, try accessing it via `phones.content`.

**Comment by runspired** [comment] 2018-04-05 00:39
Closing as a duplicate of #1829. there is extensive discussion of this form of issue there.

**Closed by runspired** 2018-04-05 00:39 UTC
