### ISSUE TITLE
Irregular model name not being applied to return results

### ISSUE THREAD

**Issue by tomoguisuru** [emberjs/data#3802] opened 2015-09-28 17:14 UTC
In my project, I have a inflector setup for a model with an irregular name, `campus`
For some reason, after updating from Ember CLI 0.2.7 to Ember CLI 1.13.8, the inflector is no longer being applied to the model.

When trying to access the store, `this.store.findRecord('campus', params['campus_id'])`, I get the following error

`No model was found for 'campu' Error: No model was found for 'campu'`

The return payload looks something like this

```
{
  campus: {
    id: 1,
    name: "Default Campus"
  },
  meta: {
    total: 1,
    page: 1
  }
}
```

I have been using an initializer with previous success

``` javascript
import Ember from 'ember';

export function initialize(/* registry, application */) {
  var inflector = Ember.Inflector.inflector;
  inflector.irregular('campus', 'campuses');
}

export default {
  name: 'inflections',
  initialize: initialize
};
```

I've tried updating to the most recent version of Ember Data, 1.13.13, and updating the ember inflector to 1.9.3 but am no closer to resolving the issue

I'm assuming this is a bug since the store is showing correctly as campus and fails when a singular record is return as above since checking the singularization/pluralization seems to work fine

``` javascript
var inflector = Ember.Inflector.inflector;
inflector.singularize('campus') // returns "campus"
inflector.pluralize('campus') // returns "campuses"
```

**Comment by tomoguisuru** [comment] 2015-09-28 17:20
I forgot to add this warning that comes before the error
`WARNING: Encountered "campus" in payload, but no model was found for model name "campu" (resolved model name using deployment@serializer:campus:.modelNameFromPayloadKey("campus"))`

**Comment by pangratz** [comment] 2015-10-07 20:31
#3730 seems related. Can you test moving the definitions into `app/app.js` and check if it would work, as suggested in the issue?

**Comment by pangratz** [comment] 2015-10-07 20:45
After further digging I found https://github.com/emberjs/data/issues/3655#issuecomment-131702765, which suggests to update the dependency for `ember-inflector` to the latest version. Can you give this a try?

**Comment by tomoguisuru** [comment] 2015-10-08 14:47
@pangratz at the time of submitting this ticket, I mentioned that I was already using 1.9.3 of the ember-inflector. I also tried using 1.9.0, 1.9.1, and 1.9.2 without any success.

As far as moving the inflectors into app/app.js, I have not tried that yet since I gave up on trying to upgrade my project

**Comment by remkoboschker** [comment] 2015-10-09 08:08
I can confirm that putting the irregular ( or not in english) inflections in both an initializer and in app.js solves singularization / pluralization issues using json:api. This not seems very good practice though. Can anyone advise where they should go? Perhaps I can work on fixing the issue from there.

**Comment by bmac** [comment] 2015-10-12 14:43
Putting irregular inflections into an initializer seems like the right way to go. I think we should try to find out why that use case broke.

**Comment by bmac** [comment] 2015-10-21 19:43
@tomoguisuru I just created a sample Ember CLI project to try to re-create your issue and I was unable to reproduce it. Do you mind looking at this repo and letting me know what I'm missing? https://github.com/bmac/inflector-test

Thanks

**Comment by christophermlne** [comment] 2015-11-04 21:00
@bmac I am having the same issue, with the same words ('campus'/'campuses').

In your example app there are no relationships. If you had a program model that could have many campuses, you'd see the app start to break and the errors will complain about no model called 'campuse' or no model called 'campu'...

If anyone wants access to my code to try to figure this one out, let me know and i'll grant access. (Code has to stay private unfortunately). This is actually the second Ember app where I've had to deal with this. The other app is using an older version of Ember and is fine...

**Comment by bmac** [comment] 2015-11-04 21:10
@christophermlne do you mind testing out Ember Data 2.2.0-beta.3?

Prs https://github.com/emberjs/data/pull/3887 and https://github.com/emberjs/data/pull/3888 were recently merged which I suspect was contributing to this issue.

**Comment by christophermlne** [comment] 2015-11-04 22:03
I will try to do as you ask but it may not be until next week sometime.

In the mean-time I was able to get this to work by doing adding the inflector rules to app.js

**Comment by remkoboschker** [comment] 2015-11-05 14:27
@bmac The prs #3887 and #3888 do not seem to make any difference. I have spotted a difference with your test project https://github.com/bmac/inflector-test . You are not using the json-api json in your mocks https://github.com/bmac/inflector-test/blob/master/server/mocks/campuses.js also I'm using mirage. Perhaps this helps.

**Comment by evandavey** [comment] 2016-01-07 04:07
Might be related.  I am using a polymorphic model (with base class pcbprimitive) .  When the type/sub-model is 'pcbvia', the instance is of type pcbprimitive.  When I change the type/sub-model to 'pcbviax' is works as expected at the instance is of type 'pcbviax' so seems like it could be related to the 'a' at the end of the model name.

**Comment by wecc** [comment] 2016-10-22 00:15
Is this problem still present in current versions of Ember/Ember Data?

**Comment by christophermlne** [comment] 2016-10-25 18:36
I will retest.

**Comment by stefanpenner** [comment] 2017-04-18 03:22
This seems to have gone stale, if it is still an issue a reproduction on latest would be great, or even better a failing test.

**Closed by stefanpenner** 2017-04-18 03:22 UTC
Labels: Needs Bug Verification
