### ISSUE TITLE
belongsTo fails with no object - needs validation

### ISSUE THREAD

**Issue by ryanjm** [emberjs/data#1848] opened 2014-04-03 11:30 UTC
I'm doing a belongs to and it fails when there is empty data in the api request. I'm overwriting the `extract` method but no matter how I change the payload it still fails (null, empty array, empty hash, no payload at all).

In the other `find[relationship]` calls there is a validation check. I feel like there should be an assertion inside the `_findBelongsTo` also ([code here](https://github.com/emberjs/data/blob/0a0f40850faa6cee2d4c66e70aed9cf7f26f3cdd/packages/ember-data/lib/system/store.js#L1716)).

What is the correct way to handle no relationship?

I think part of the problem is that it is really a `hasOne` so the ID doesn't exist on the original object (which I'm building the relationship off of) and I've made it async. It is doing a nested call in order to find the object.

**Comment by bmac** [comment] 2015-06-02 17:51
Closing as a duplicate of #1810.

**Closed by bmac** 2015-06-02 17:51 UTC
