### ISSUE TITLE
ember-data 2.14.0: 'instrument' is imported from external module 'ember-data/-debug' but never used

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/data#5016] opened 2017-06-18 10:39 UTC
Launching application:

```
$ ember s
Livereload server on http://localhost:49153
'instrument' is imported from external module 'ember-data/-debug' but never used

Build successful (31681ms) – Serving on http://localhost:4200/
```

**Comment by runspired** [comment] 2017-06-19 21:45
Likely this means that linting is running before transpilation.

**Comment by rwjblue** [comment] 2017-06-19 23:21
FWIW, linting _should always_ be ran before transpilation. I guarantee that babels transpiled output would not pass most apps linting rules. 😃

**Comment by runspired** [comment] 2017-06-20 17:22
@rwjblue all of our instrument import locations are used. This suggests to me that linting occurs after something strips the usage but before another transform strips the left-behind import itself.

**Comment by rwjblue** [comment] 2017-06-20 20:13
> 'instrument' is imported from external module 'ember-data/-debug' but never used

This is not a linting error. This is a rollup thing.

**Comment by rwjblue** [comment] 2017-06-20 20:17
This is almost certainly because we run things through babel before passing them to `rollup`.  The `import` should be stripped by the babel plugin if all usages are removed (to get rid of this error).

**Comment by runspired** [comment] 2017-06-21 16:38
@rwjblue we have a babel plugin to strip pre-rollup, but it only runs in prod. Heimdall though is stripped all the time unless the flag is set. Might just need to reconfigure this to avoid polluting folks with this error.

**Comment by qarthandgi** [comment] 2017-06-22 03:58
Same Issue. What's the way to fix this?

**Comment by mminkoff** [comment] 2017-06-25 18:48
I'm seeing this in ember-data@2.13.0

**Comment by jtstrohl** [comment] 2017-06-29 21:26
Seeing the same in ember-cli@2.13.3 when running 'ember server' on brand new application on brand new installation of node and ember.

**Comment by kumkanillam** [comment] 2017-06-30 04:58
This error will not do any harm to your application, and it has been fixed in [ember-data@2.14.2](https://github.com/emberjs/data/issues/5021#issuecomment-309605333). Upcoming release of Ember CLI will include the fix.
This has been mentioned in ember-cli 2.13.3 release notes.

**Comment by syntaxval** [comment] 2017-07-07 04:46
ember-cli: 2.14.0
node: 6.11.0
os: darwin x64

'instrument' is imported from external module 'ember-data/-debug' but never used

Still there ...

**Comment by boztek** [comment] 2017-07-10 03:42
I can confirm that this warning is still displayed but only for development builds.
ember s -prod and ember build -prod do not display the warning.

ember-cli: 2.14.0
node: 6.11.0
os: darwin x64

**Comment by abbasovalex** [comment] 2017-07-13 16:53
Same problem:
$ ember -v
ember-cli: 2.15.0-beta.1
node: 8.0.0
os: darwin x64

**Comment by yawboakye** [comment] 2017-07-15 10:29
@abbasovalex that error/warning shouldn't be able to halt your project. If that's happening it's most likely a different problem. If you're already part of the [Ember Slack](https://embercommunity.slack.com/) community, let's continue the conversation there. Otherwise get an invitation :point_right: [here](https://ember-community-slackin.herokuapp.com/)

**Comment by robertbenjamin** [comment] 2017-07-26 23:17
Also getting this warning.

ember-cli: 2.14.1
node: 7.10.0
os: darwin x64

**Comment by GitSahib** [comment] 2017-07-27 12:21
Getting the same error for dev env.

version: 2.3.0
node: 6.10.1
os: win32 x64

**Comment by stefanpenner** [comment] 2017-07-27 21:41
> Getting the same error for dev env.

You mean warning right?

**Comment by Vinchens00** [comment] 2017-08-08 11:59
I'm still seeing the same warning:

ember -v
ember-cli: 2.14.2
node: 6.10.0
os: darwin x64

I got this error when I updated ember-cli from 2.13.3 to 2.14.0. I changed next versions in package.json:
ember-cli 2.13.3 -> 2.14.0
ember-cli-htmlbars: ^1.2.0 -> ^2.0.1
ember-cli-htmlbars-inline-precompile: ^0.4.0 -> ^0.4.3
ember-data: 2.13.2 -> 2.14.3
ember-source: 2.13.3 -> 2.14.0

Hope it helps.
Production build also shows this warning.

Do you have any estimation when this issue will be fixed?

**Comment by GitSahib** [comment] 2017-08-08 12:47
I have ember 2.3

Best Regards,

Sahib Zar Khan

Applications Developer (*Apex Systems)* – *GD&A* *BizOps*

*AT&T Global Customer Service*

*Phone – *919-536-5158
*Cell **Phone *: 641/451-9852
LinkedIn: www.linkedin.com/in/sahib-khan
Email: sahib.zer@gmail.com

**Comment by GitSahib** [comment] 2017-08-08 12:49
ember 2.3.2
ember data 2.14.9 
jquery 2.1.1

**Comment by phstoned** [comment] 2017-08-14 12:16
Same here.
`'instrument' is imported from external module 'ember-data/-debug' but never used`

`ember -v`

```
ember-cli: 2.6.2
node: 6.9.2
os: darwin x64
```

**Comment by mcfiredrill** [comment] 2017-08-18 07:07
Seeing this on a fresh ember app.

```
ember: 2.15.0-beta.3
ember-data: 2.15.0-beta.4
jquery: 3.2.1
```

**Comment by notmessenger** [comment] 2017-08-22 21:20
```
ember-cli: 2.12.3
node: 7.10.1
os: darwin x64
"ember-data": "2.14.10"
```

**Comment by joehany** [comment] 2017-08-23 15:12
```
node: 7.7.3
ember-cli: 2.14.2
ember-data: 2.14.9
```

**Comment by stefanpenner** [comment] 2017-08-23 15:49
fix https://github.com/emberjs/data/pull/5114 (pending some unit tests)

**Comment by stefanpenner** [comment] 2017-08-23 15:54
@runspired said he would look to add tests tonight, once those land. We can backport and release :)

**Comment by jontoewsdev** [comment] 2017-09-16 22:34
Anyone resolve this.

What's up with this?

ember-data/lib/stripped-build-plugins.js:    uniqueAdd(filteredImports, 'ember-data/-debug', ['instrument']);
ember-data/lib/stripped-build-plugins.js:    uniqueAdd(filteredImports, 'ember-data/-debug', [
ember-data/lib/stripped-build-plugins.js:    plugins.push([StripFilteredImports, 'ember-data/-debug']);

**Comment by xomaczar** [comment] 2017-10-11 02:35
This has been fixed, we should close this issue

**Comment by bmac** [comment] 2017-10-11 03:23
Thanks @xomaczar.

**Closed by bmac** 2017-10-11 03:23 UTC
Labels: Bug
