### ISSUE TITLE
model name param to belongsTo not usable

### ISSUE THREAD

**Issue by SpikedKira** [emberjs/data#4321] opened 2016-04-12 15:24 UTC
if I have `foo: DS.belongsTo( 'bar' )` in my model, and my server returns a relationship object with key `foo` that has a data object with key `type` that has value `foos`, then my `bar` explicit is disregarded?

What's the point of this param if you can't tell ember data that your client-side model uses a different name than your server-side model?

The property you are assigning to, in this case `foo`, is still required to be the name of the property on the model returned by the server.  That part makes sense.

**Comment by fivetanley** [comment] 2016-04-12 15:54
You can override http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_modelNameFromPayloadKey on your serializer (usually application serializer in this case) if you want `foos` to mean `bar`.

**Comment by SpikedKira** [comment] 2016-04-12 15:57
Right, this is my current route.  However, what would be the purpose of the param as clearly documented?

**Comment by fivetanley** [comment] 2016-04-12 16:27
For APIs that don't return `type`, it should assume that to be the correct type. I would expect this to throw an exception for relationships that aren't `polymorphic` though.

**Comment by SpikedKira** [comment] 2016-04-12 17:32
when I removed the type being returned by the server, it errored out on the parse, so it never got to the relationship link.... So that can't be the use case >.>

**Comment by fivetanley** [comment] 2016-04-12 18:42
What does the payload you're sending back look like?

**Comment by pangratz** [comment] 2016-05-04 18:12
I just chatted with @SpikedKira via slack and we were not able to reproduce the issue here. Using a combination of `payloadKeyFromModelName`, `modelNameFromPayloadKey` and `pathForType` should be enough to map types from the payload to ember data and vice versa.

I am going to close this issue. Feel free to reopen if you can reproduce this. Thanks!

**Closed by pangratz** 2016-05-04 18:12 UTC
