### ISSUE TITLE
Transform deserialize method not fired after record has been updated (saved)

### ISSUE THREAD

**Issue by dmagunov** [emberjs/data#4174] opened 2016-02-19 23:05 UTC
Running ember data 2.3.0.

**Comment by sly7-7** [comment] 2016-02-20 17:50
Hi, could you build a example demonstrating the bug please ? Using https://ember-twiddle.com/ as a starting point would help a lot.

**Comment by pangratz** [comment] 2016-04-14 14:08
@dmagunov I cannot reproduce this, see [this ember-twiddle](https://ember-twiddle.com/27258d34264cb8d1314b83fec3e47fea?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Cmodels.person.js%2Ctransforms.my-type.js): if you click `update` then the deserialized value from the transform is shown in the template.

I am going to close this issue. Feel free to reopen if you can share some code which demonstrates the issue you're having!

**Closed by pangratz** 2016-04-14 14:08 UTC
