### ISSUE TITLE
canonicalState property isn't updated when destroying a record in a async hasMany relationship

### ISSUE THREAD

**Issue by bobbysciacchitano** [emberjs/data#2639] opened 2014-12-30 10:45 UTC
I've upgraded to Ember Data 1.14 from 1.12 and now come across an issue when I destroy a related object in an async hasMany relationship, the object is successfully removed on the host (host returns 204) but when I push in a new object into the relationship the previously deleted object/s reappear.

When I inspect the relationship after deleting the related object, I can see that the content array is empty however the canonicalState still shows the original object in place. Likewise when I push a new object in, the content array is updated with the new object and the contents of canonicalState.

If I attempt to delete the object again. I get the following error:
Uncaught Error: Attempted to handle event `deleteRecord` on <fitamize@model:session-exercise::ember1263:null> while in state root.deleted.saved. 

I'll try and put together something to demonstrate the issue.

**Comment by matthooks** [comment] 2015-01-04 06:56
Just wanted to chime in to say I'm also running into this issue on beta.14.

**Comment by flexybiz** [comment] 2015-01-04 11:33
Got the same issue (beta.14.1) and figured out it occures in sync mode too.

**Comment by sly7-7** [comment] 2015-01-07 10:51
closing as duplicate of https://github.com/emberjs/data/issues/2639

**Closed by sly7-7** 2015-01-07 10:51 UTC
