### ISSUE TITLE
If a model errors while loading, saving a model with a relationship to it will set the relationship id to null

### ISSUE THREAD

**Issue by NLincoln** [emberjs/data#5229] opened 2017-10-15 02:12 UTC
[minimal(ish) reproduction](https://ember-twiddle.com/a3d240321d652ea597178b028cce2300?openFiles=templates.application.hbs%2C)

This occurs on the current LTS, and can lead to loss of user data.

**Comment by NLincoln** [comment] 2017-10-21 21:53
Some more background on this:

One of our services had a temporary outage. As a result, a model failed to load. I noticed afterwards that some columns that shouldn't have been null were marked as null. After some investigation, I discovered that the partial outage caused ember-data to save the model with the foreign key set to null, which caused some data loss.

Thankfully this only occurred to our internal models, but the likelihood of this happening again and possibly messing up our users data is high (in the event of another incident).

**Comment by runspired** [comment] 2017-10-23 16:09
@nlincoln thanks for the report and the reproduction, I'll dig into this as soon as I can.

**Comment by wycats** [comment] 2017-10-23 16:16
@NLincoln my understanding is that this is probably related to some regressions caused by two major new features: improved dematerialization and lazy relationships. The data team has been knocking down these regressions, so thanks for the report, especially since this regression could cause data loss.

**Comment by runspired** [comment] 2018-03-18 01:39
After investigating, I don't think this is a regression, and very possibly it's something end user's serializers would need to account for on their own. If a related record is in a loading or error state, it's unlikely we could serialize it correctly much of the time.

**Comment by igorT** [comment] 2020-02-26 22:58
Discussed this at the team meeting, not sure I fully agree with the previous answer, but assigned it to myself to investigate.

**Comment by runspired** [comment] 2020-05-13 21:44
Might be worth pairing with @snewcomer on this as part of fixing some issues similar to this that have open PRs for failing tests

**Comment by runspired** [comment] 2023-09-10 09:24
I think I agree with @igorT that there is a better behavior, in fact I described it here https://github.com/emberjs/data/issues/7632#issuecomment-994563391

**Closed** 2023-09-10 09:26 UTC
Labels: Improvement, Needs Team Discussion, Good for New Contributors, api-errors, unload-apis
