### ISSUE TITLE
peekAll contains null entries after unloadRecord

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/data#5111] opened 2017-08-02 23:58 UTC
This is related to #4963 and #5025 (probably). #4963 affected me though that exact issue appears to have been resolved. I'm thinking that #4963 was hiding #5025 from me before. Now i'm upgrading to 2.14.9 from 2.12 and i'm getting another issue. 

This code is run after i unload a number of records from the store. 
```
        let store = this.get('store');
        let records = store.peekAll('asset-position');
        let orderedBy = records.sortBy('utc');
```

the `sortBy('utc')` fails because the peekAll record array still contains references to unloaded records.
```
ember.debug.js:26513 Assertion Failed: Cannot call get with 'utc' on an undefined object.
Error
    at Object.assert (http://localhost:4200/skyrouter3/assets/vendor.js:29571:15)
    at get (http://localhost:4200/skyrouter3/assets/vendor.js:40963:64)
    at http://localhost:4200/skyrouter3/assets/vendor.js:54265:43
    at InternalArray.sort (native)
    at Array.sort (native)
    at Class.sortBy (http://localhost:4200/skyrouter3/assets/vendor.js:54261:29)
    at Class.loadMoreAssetPositionsLastUtcReset (http://localhost:4200/skyrouter3/assets/sky-router-3.js:42129:37)
    at Object.applyStr (http://localhost:4200/skyrouter3/assets/vendor.js:61345:18)
    at sendEvent (http://localhost:4200/skyrouter3/assets/vendor.js:38746:22)
    at Class.trigger (http://localhost:4200/skyrouter3/assets/vendor.js:54394:33)
```

If this is too close to those other issues please close. 

EDIT:
For show:
```
        let records = store.peekAll('asset-position');
        console.log(records.get('length'));
        console.log(records.filter(y => y != null).get('length');
```
This outputs `1844` and `700`. Big difference.

**Comment by workmanw** [comment] 2017-08-28 15:06
We just ran into a bug today where this happened in our application.

**Comment by stefanpenner** [comment] 2017-08-28 17:16
I think a similar to fix to the others can be applied here. Specifically, `unloadRecord` needs to act like client-side delete when it comes to recordArrays

**Comment by workmanw** [comment] 2017-08-28 20:45
@stefanpenner Failing test: #5157

**Comment by nag5000** [comment] 2017-09-01 23:02
I have the same bug, but in a little different situation:
```js
// /routes/courses.js
model() {
  return this.store.peekAll('course');
}

// /controllers/courses.js
draftCourses: computed('model.@each.isDraft', function() {
  return this.get('model').filterBy('isDraft');
})

// anywhere
store.unloadAll();
```

```
 "Error: Assertion Failed: Cannot call get with 'isDraft' on an undefined object.
    at new EmberError (https://localhost:4200/assets/vendor.js:30455:25)
    at Object.assert (https://localhost:4200/assets/vendor.js:30697:15)
    at get (https://localhost:4200/assets/vendor.js:42043:64)
    at i (https://localhost:4200/assets/vendor.js:54911:37)
    at https://localhost:4200/assets/vendor.js:55127:22
    at Class.forEach (https://localhost:4200/assets/vendor.js:55084:18)
    at Class.filter (https://localhost:4200/assets/vendor.js:55126:12)
    at Class.filterBy (https://localhost:4200/assets/vendor.js:55140:19)
    at Class.<anonymous> (https://localhost:4200/assets/rukuku-app.js:16579:32)
    at ComputedPropertyPrototype.get (https://localhost:4200/assets/vendor.js:42718:28)"
```

Versions:
$ npm ls ember-source ember-data               
├── ember-data@2.15.0  (actually, this bug I have since 2.13.0)
└── ember-source@2.15.0 

---------

In addition, when I trying to enter `route:course` again, I have several errors:
1. Assertion Failed: Cannot create a new chain watcher for `<app@model:course::ember756:B2haQWMgPTctdjE>` after it has been destroyed. 
2. Assertion Failed: You modified "model.length" twice on <DS.RecordArray:ember739> in a single render.
3. Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction
    ```at debugAssert (util.js:62)
    at Environment.begin (runtime.js:6378)
    at Environment.begin (environment.js:273)
    at InteractiveRenderer._renderRoots (renderer.js:311)
    at InteractiveRenderer._renderRootsTransaction (renderer.js:379)
    at InteractiveRenderer._revalidate (renderer.js:418)
    at invokeWithOnError (backburner.js:281)
    at Queue.flush (backburner.js:152)
    at DeferredActionQueues.flush (backburner.js:343)
    at Backburner.end (backburner.js:451)```

**Comment by vishusharmagit** [comment] 2017-09-07 07:24
Similar error as @nag5000.

But, In model computed property.

**Comment by workmanw** [comment] 2017-09-11 12:49
I submitted a failing test for this issue, #5157. Would it be possible to have this relabeled as a bug?

**Comment by catz** [comment] 2017-09-25 08:51
Getting mostly the same in similar conditions.

`Error: Assertion Failed: Cannot update watchers for `hello` on `<team@model:product::ember971:product:2000002178:apple>` after it has been destroyed.`

'hello' looks very confusing and it's written that way in code.. and "Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction" right after the previous message.
Trying to upgrade from 2.12.2 with no luck.

**Comment by stefanpenner** [comment] 2017-09-26 16:07
thanks for the failing test @workmanw, sorry I have been a tad busy to look into this further. But it it is on my radar, if by this weekend I haven't responded, please feel free to ping me :)

**Comment by workmanw** [comment] 2017-10-09 11:33
@stefanpenner Pinging you back :). To be honest, while this issue did impact our application, there are some clear workarounds we could take. However, we seem to be unable to come up with a workaround for issue: #5136. Sorry to hijack one issue to lobby for help with another. It's just the place our app finds itself in at the moment.

**Comment by Kilowhisky** [comment] 2017-10-12 17:17
The workarounds don't quire work if you use computed properties since they recompute before the second step can be performed. I'm still stuck on ED 2.12 even though i'm on Ember source 2.16.   The farther i fall behind the more concerning this becomes..

**Comment by sergiferran** [comment] 2017-11-02 08:08
@stefanpenner Any updates on that? Thank you very much

**Comment by Kilowhisky** [comment] 2017-11-21 06:03
Can't go any further with ember data until this is resolved. Anything i can do to help?

**Comment by sergiferran** [comment] 2017-11-21 06:25
What i've founded as workaround is to don't unload the records you are going to fetch again.
I was doing `unloadAll` and then `findAll`. Some records were the same and then it crashed because of that. What i do now is to fetch the new records and unload only the ones that there aren't in the new bulk of data.
Hope this help to you.

**Comment by Kilowhisky** [comment] 2017-11-21 06:40
Not really. My app lives long and the only way it prospers is if I run a garbage collection of sorts on records not currently in use. 

By long I mean anywhere from 20 minutes to 24 hours and that’s only because I force a page reload every 24 hours.😏

**Comment by ewwilson** [comment] 2017-11-21 14:27
We have not been able to upgrade past 2.12.2 because this and issues like it that manifest in different ways and workarounds do not seem resolve the issue when using the embedded records mixin

**Comment by ashrafhasson** [comment] 2017-11-21 19:52
I have the same issue tested with ED 2.16.3 and 2.13.2, when creating a new model that `belongsTo` another and both are unsaved at the time I `unloadRecord` of the child model. I expected unloading a record that's not saved not to affect its parent. I get the following when navigating back to the model where the child record was created:

```
essage: "Assertion Failed: Cannot create a new chain watcher for `<bmanager2@model:cash-request::ember1102:null>` after it has been destroyed."
```

**Comment by ewwilson** [comment] 2018-01-05 00:34
This still appears to be an issue in 2.18, any update on what release will have these issues addressed?

**Comment by RGL9032** [comment] 2018-01-05 02:34
At this point, it's best to assume it'll never be fixed and find your own workarounds. Ember-data allowed major regressions to be released in 9 months ago, despite reports from users during the beta cycle. And since little has done remedy it. 

Honestly the whole community would benefit greatly from abandonment of this addon. It would open the door for real competition and innovation in this space. As long as `ember-data` is officially promoted by Ember.js as "the data layer for Ember.js", competitive addons will never have a chance to rise up and gain real traction.

**Comment by alexanderbanks** [comment] 2018-01-20 00:16
Has anybody found an actual workaround to "I want to delete all the data in the store" without using unloadAll?

**Comment by JBoshart** [comment] 2018-01-23 19:25
@alexanderbanks - I have not, and I'm pretty [redacted explitive] frustrated by it at this point. Did you find a solution?

**Comment by alexanderbanks** [comment] 2018-01-23 19:33
@JBoshart No, we' switched over to a horrible hack to get around breaking the app via `unloadAll`

**Comment by JBoshart** [comment] 2018-01-23 20:12
@alexanderbanks - Thanks for your prompt response, I appreciate it. I'll post back here if I find a workaround.

**Comment by Kilowhisky** [comment] 2018-01-23 22:24
I almost thought i had progress here: https://github.com/emberjs/data/issues/5025  I think figuring this out for real is going to take a epic journey down the rabbit hole.

**Comment by JBoshart** [comment] 2018-01-24 21:15
I discovered in the adapter that findAll was returning the correct payload, but when it got to my route it shoved the payload onto the end of the store (which never unloaded, and thus had a bunch of records I did not want). I ended up continuing to use findAll to make my api call, passed a piece of identifying data through with the response in the adapter, and then added the identifying key to each record in the payload. When the data got to my route I filtered the records based on that identifying key, and then set it on the controller as an array of objects, abandoning use of the store. 

Real pain in the butt, and not an elegant work around, but there you go.

**Comment by henrymazza** [comment] 2018-01-25 11:48
@Kilowhisky 
If you call ‘record.get('_internalModel').transitionTo('deleted.saved');’ right before unloadRecord does it work? For me it’s an issue of RecordArrays not filtering out “root.empty” but does “root.deleted.saved”. 

Never saw peekRecord returning null values though. 

It worked for me in 2.17 and 2.18.

**Comment by nag5000** [comment] 2018-02-17 00:36
It seems to be fixed in 3.0.1 and 2.18.1 (#5273). I just upgraded to 3.0, everything is fine.

**Comment by Kilowhisky** [comment] 2018-02-17 03:10
Really??? Any idea what was done to fix it? I’m going to be working on migrating in the next couple weeks.

**Comment by Kilowhisky** [comment] 2018-02-20 22:42
So on 3.0.0 this particular issue appears to be fixed.

Unfortunately this issue seems related and is happening to me:
https://github.com/emberjs/data/issues/5343

Also i'm still getting computed properties holding onto the models after they are destroyed and issuing errors like this.

```
Assertion Failed: Cannot update watchers for `utc` on `<my-app@model:asset-position::ember9045:1058476022>` after it has been destroyed.
```

If i remember this was how it worked in 2.16+

So not really any progress here.

**Comment by sly7-7** [comment] 2018-02-21 09:00
@Kilowhisky did you try the beta release ? If so, and it does not work, I know @jlami is trying to figure out the issue in #5354, maybe you could be interrested ?

**Comment by runspired** [comment] 2018-03-17 02:10
I'll be looking into whether https://github.com/emberjs/data/pull/5378 fixes this issue, I suspect it does.

**Comment by runspired** [comment] 2018-03-17 08:45
I can confirm that #5378 will resolve this issue.

**Closed** 2018-03-26 12:43 UTC
Labels: Bug

**Comment by Kilowhisky** [comment] 2018-03-26 20:34
Sorry for the late reply, i was out of country.

I can confirm as well that #5378 resolves my issues. 

https://media.giphy.com/media/hsBZfDG7wiWHu/giphy.gif

**Comment by lakjain** [comment] 2018-11-26 11:57
Hi, Is there any resolution/workaround for this one - Cannot update watchers for model after it has been destroyed. I am working on Ember-data - 2.18
