### ISSUE TITLE
Computed property which depends on `someAsyncBelongsToRelationship.id` does not update via inverse relationship

### ISSUE THREAD

**Issue by nag5000** [emberjs/data#7766] opened 2021-11-20 15:40 UTC
### Reproduction

https://stackblitz.com/edit/github-eub2pa?file=app%2Fcontrollers%2Fapplication.js

### Description

Computed property which depends on `someAsyncBelongsToRelationship.id` does not update if `someAsyncBelongsToRelationship` is set via inverse async belongsTo relationship.

For example, having two models, `course` and `enrollment`:

```js
  // models/course.js
  enrollment: belongsTo('enrollment', { inverse: 'course', async: true }),

  isEnrolled: computed('enrollment.id', function() {
    return this.belongsTo('enrollment').id() !== null;
  }),
```

```js
  // models/enrollment.js
  course: belongsTo('course', { inverse: 'enrollment', async: true })
```

```js
let course = await store.findRecord('course', 123);
course.belongsTo('enrollment').id(); // null
course.isEnrolled; // false

let enrollment = this.store.createRecord('enrollment', { course });
await enrollment.save();

course.belongsTo('enrollment').id(); // 321
course.isEnrolled; // false <-------- BUG, expected true

course.notifyPropertyChange('isEnrolled');
course.isEnrolled; // true  <-------- Woah
```

### Versions

Ember: 3.25.4, 3.28.6
Ember Data: 3.25.0, 3.28.3

**Comment by runspired** [comment] 2021-12-13 21:51
closing as a duplicate of #7102, however this is a priority

**Closed by runspired** 2021-12-13 21:51 UTC

**Comment by runspired** [comment] 2021-12-15 03:07
#7796 will add this feature
