### ISSUE TITLE
Ember Data Not Using Irregular Route For Find But Is For CreateRecord

### ISSUE THREAD

**Issue by grahambaitson** [emberjs/data#4625] opened 2016-10-24 11:19 UTC
I was wondering would someone be able to help. I am using an irregular route name which seems to be working when calling the createRecord on the store but not on the find.

In the router.js file, I am specifying the route paths as follows:

    this.route('admin', function() {
        this.route('staff');
    });

    // This is so the parent route data does not display in the sub-route
    this.route('admin.staff.create-staff', { path: '/admin/staff/create-staff' });

Then in the inflector model file, I am specifying the following irregularities:

    inflector.irregular('create-staff', 'staff');

Now in the route, within the model function, I am specifying the following:

    model(params) {
        var model = null;

        const id = params.id;
        if(id) {
            model = this.store.find('create-staff', id);            
        } else {
            model = this.store.createRecord('create-staff'); 
        }

        return model;
    },

Everything is working when I call the model without any query parameters (i.e. it's calling a GET request to REST API endpoint at ...../staff/). But when I do specify the query parameters, it's not working correctly and not going to the irregular path as specified above (i.e. it's calling a GET request to the REST API at ......./createStaff/{id}).

Would anyone be able to help me with making sure that the 'find' and 'createRecord' are both directed to the irregular 'staff' endpoint on the REST API?

Thanks in advance Graham

**Comment by locks** [comment] 2016-10-24 11:35
Hi Graham,

You showed us your Ember application routes, but those are unrelated to Ember Data.
`store.createRecord` doesn't actually make a request to the server, it creates a record in Ember Data's store. You would need to call `.save()` on that model for it to be persisted to the server.

**Comment by grahambaitson** [comment] 2016-10-24 11:43
Hi @locks, thank you for your quick response. So on my page I have a create button, and when I click this, it calls the .save() on the model, this works as expected by going to the ....../staff as setup in the inflector. The issue I'm having is on the .find(). This doesn't seem to use the inflector and go to ......./staff but instead goes to ......../createStaff which results in a 404 because it doesn't exist. Is there any reason why .find() would not use the inflector and the .createRecord() - .save() does?

**Comment by pangratz** [comment] 2016-10-24 11:47
@grahambaitson I cannot reproduce this using latest Ember-Data, see [this ember-twiddle](https://ember-twiddle.com/dcc9e8561c5debe745b8e4d91314e7a7?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cinitializers.inflector-rules.js).

Can you update the the twiddle to demonstrate the issue you're having? Also, which versions are you using?

**Comment by grahambaitson** [comment] 2016-10-24 16:03
Thank you @pangratz, I can't reproduce it with your twiddle. I'll work on trying to see what I have done wrong, nothing much from what I can see, but I must have something wrong somewhere in how my model or route is defined. 

In my router file, I want my route to be placed at the following
    this.route('admin.staff.create-staff', { path: '/admin/staff/create-staff' });

So when I'm creating my route and model, I'm using ember g route admin/staff/create-staff and ember g model admin/staff/create-staff, this could be the reason. I'll look into it and restart and redefine my model and routes and see can I resolve the issue. Thanks for all your help, I will post once I have tested further. Graham

**Comment by pangratz** [comment] 2016-10-24 16:22
Ok, so this looks not like a bug at the moment. I will close this issue then. Feel free to reopen if you think this is still a bug (preferable with a reproducible example). Thanks!

If you have any further questions, feel free to chime in into the `-ember-data` channel in the emberjscommunity slack.

**Closed by pangratz** 2016-10-24 16:22 UTC
Labels: Needs Bug Verification

**Comment by grahambaitson** [comment] 2016-10-25 10:42
Thanks @pangratz. So I seem to be having a problem when I'm working on sub levels. So in your example, 'person' is at root level. If you where to create adapter as 'ember g adapter admin/person', model as 'ember g model admin/person', route as 'ember g route admin/person' and template as 'ember g template admin/person', this is when I can't get it to work. I've tried this with the inflector as 'Inflector.inflector.irregular('adminPerson', 'person')' and 'Inflector.inflector.irregular('admin.person', 'person')' but it still won't aim for ....../person. Would you have any direction at all on what's the best way to approach or resolve the problems I'm having????

**Comment by pangratz** [comment] 2016-10-25 13:33
I am not completely sure I understand why you want to use `irregular` at all here. Do you have different model definitions, aka `app/models/staff.js` and `app/models/create-staff.js`?

If not, why not use the correct models within the route in the first place?

```js
// app/admin/staff/create-staff.js
import Ember from "ember";

export default Route.extend({

  model(params) {
    if (params.id) {
      return this.store.findRecord("staff", params.id);
    } else {
      return this.store.createRecord("staff", { … });
    }
  }

});
```

**Comment by grahambaitson** [comment] 2016-10-26 14:23
@pangratz I was originally using separate models as you pointed out because I wanted to isolate some fields and validation checks to the create model, but I've just gone with the one model now. Thanks for all your help.
