### ISSUE TITLE
Embedded polymorphic record with custom id doesn't work.

### ISSUE THREAD

**Issue by mayatskiy** [emberjs/data#2793] opened 2015-02-16 12:44 UTC
If I have embedded polymorphic records and a custom primaryKey (for example '_id'). 
When I use EmbeddedRecordsMixin this code works incorrectly:

<pre>
function extractEmbeddedHasManyPolymorphic(store, key, hash) {
  ...
  forEach(hash[key], function(data) {
    var typeKey = data.type;
    var embeddedSerializer = store.serializerFor(typeKey);
    var embeddedType = store.modelFor(typeKey);
    var primaryKey = get(embeddedSerializer, 'primaryKey'); // returns '_id'

    var embeddedRecord = embeddedSerializer.normalize(embeddedType, data, null);
    store.push(embeddedType, embeddedRecord);
    ids.push({ id: embeddedRecord[primaryKey], type: typeKey }); // the error is here
  });
</pre>

next line:

<pre>
   ids.push({ id: embeddedRecord[primaryKey], type: typeKey });
</pre>

sets undefined id. Because embeddedRecord has no '_id' key after deserialization and have only 'id' key.

**Comment by lolmaus** [comment] 2015-02-16 13:55
Hey @mayatskiy, i'm using polymorphic embedded records successfully. Can you please reproduce the issue on http://emberjs.jsbin.com/ ?

**Comment by mayatskiy** [comment] 2015-02-16 14:06
@lolmaus with custom id?

**Comment by lolmaus** [comment] 2015-02-16 15:27
@mayatskiy, my polymorphic records are treated by the backend as nested attributes rather than child records. They arrive without ids. 

I override the `extractArray`, `extractSingle` and `serialize` methods of the parent model serializer and slip ids into the polymorphic items.

**Comment by bmac** [comment] 2015-02-16 23:22
Thanks for the bug report @mayatskiy.  Would you like to open a pr to fix this issue?

**Comment by igorT** [comment] 2015-05-31 01:22
@pangratz wanna take a stab at this? Shouldn't be too hard, we in fact don't need to worry about the primary key here because we already normalized, so if you just remove those couple lines + a test would be good to go

**Comment by pangratz** [comment] 2015-05-31 20:56
@igorT I will take stab at it tomorrow

**Comment by igorT** [comment] 2015-06-02 04:16
Fixed by #3138

**Closed** 2015-06-02 04:16 UTC
Labels: Bug
