### ISSUE TITLE
_crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by law-rence** [emberjs/data#8106] opened 2022-08-08 11:13 UTC
File: packages/store/addon/-private/identifier-cache.ts:37

Tested in Chrome Android Version 69 -> the functionality is available at Version 92
(https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)

The issue occurs on using "createRecord". The fast boot mode is false, so it uses window.crypto that results in an empty object. The consequence, the function "randomUUID" is not defined.

Is there any polyfill, downward compatibility ?

Thank you a lot for your work.

**Comment by samcic** [comment] 2022-08-08 14:36
Safari < 15.4 also doesn't have this method available so it's also quite relevant for iOS users (particularly those using the slightly older iPhone 5, 6 and 6 Plus models which are stuck at iOS 12.5.5 as the final OS).

**Comment by runspired** [comment] 2022-08-08 22:58
This is mostly a duplicate of #8097 so I'm going to close it in favor of that. We'll be adding the ability to include a polyfill when needed to address that ticket, especially as this isn't one of the API's that babel will typically polyfill for you based on target. The function is valid on all modern browser targets at this point, but ensuring there can be some lag seems like a good idea.

**Closed by runspired** 2022-08-08 22:58 UTC

**Comment by runspired** [comment] 2022-08-09 00:23
Oh I'd also add you actually can provide your own lid function and in doing so bypass the uuid generation by using setIdentifierGenerationMethod: https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fstore. We should make it polyfillable but in the mean time feel free to fix by override.

**Comment by gorner** [comment] 2024-07-16 20:12
For reference as to how to setup the above-referenced polyfill for anyone coming across this, since I can't really think of a better place to document:

- For Ember Data 4.7.0 through 5.3.3: first add `@embroider/macros` as a dependency in your package.json (even if it's already installed transitively), then setup the config indicated at https://github.com/emberjs/data/tree/v5.3.3?tab=readme-ov-file#randomuuid-polyfill
- For Ember Data 5.3.4+: see https://github.com/emberjs/data?tab=readme-ov-file#randomuuid-polyfill

Unfortunately this was not well-documented when my app recently upgraded to Ember Data 4.12. We came across the 5.3.4 instructions first and assumed it also applied to 4.12, then after finding the right config, we didn't know about needing to add the dependency until coming across a message to that effect in Discord.
