### ISSUE TITLE
Empty record's relationships serialization and JSONAPI specs

### ISSUE THREAD

**Issue by thomasdurin** [emberjs/data#5173] opened 2017-09-14 16:17 UTC
Hi,

Some changes have been recently made on record's relationships serialization (see https://github.com/emberjs/data/pull/5048)

As said, `createRecord` should only setup relationships with data, which sounds logic but it also causes some issues related to the JSONAPI specs. 

As mentioned here : http://jsonapi.org/format/#document-resource-object-linkage

> Resource linkage **MUST** be represented as one of the following:
>  - **null for empty to-one relationships.**
>  - an empty array ([]) for empty to-many relationships.
>  - a single resource identifier object for non-empty to-one relationships.
>  - an array of resource identifier objects for non-empty to-many relationships.

In result, my JSONAPI handler reject requests and is asking for relationships to be present in the payload, empty or not.

@hjdivad @stefanpenner @runspired @bmac Maybe I'm missing something, could you please clarify this ?

Thanks !

**Comment by fabriciotav** [comment] 2018-02-11 10:04
It seems that now (since ember-data 2.14.4) you'll have to explicitly set the "empty" relationship. For instance:

```
// This will be serialized as you expect
const post = this.store.createRecord('post', {
  title: 'Lorem ipsum',
  comments: []
});

post.save();
```

```
// This will **not** be serialized as you expect
const post = this.store.createRecord('post', {
  title: 'Lorem ipsum'
});

post.set('comments', []);
post.save();
```

**Comment by runspired** [comment] 2018-04-06 12:34
@fabriciotav thanks for the clear delineation. I should be able to address this rather easily in #5410

**Comment by runspired** [comment] 2018-04-18 03:17
I suspect this and #5100 are manifestations of the same issue.

**Comment by runspired** [comment] 2018-05-08 21:50
This was likely related but I don't think it was the root cause: https://github.com/emberjs/data/pull/5466

**Comment by runspired** [comment] 2019-07-24 00:24
A number of fixes were landed to ensure we always serialize as much as we should, if more are needed please open a new ticket. That said, for most situations the answer is to customize the serialization to fit your API.

**Closed by runspired** 2019-07-24 00:24 UTC
Labels: Good for New Contributors, Improvement

**Comment by a1723** [comment] 2023-10-31 13:03
> It seems that now (since ember-data 2.14.4) you'll have to explicitly set the "empty" relationship. For instance:
> 
> ```
> // This will be serialized as you expect
> const post = this.store.createRecord('post', {
>   title: 'Lorem ipsum',
>   comments: []
> });
> 
> post.save();
> ```
> 
> ```
> // This will **not** be serialized as you expect
> const post = this.store.createRecord('post', {
>   title: 'Lorem ipsum'
> });
> 
> post.set('comments', []);
> post.save();
> ```

thanks, it helps me to resolve warning.
Ember 5.3.0
