### ISSUE TITLE
setting the namespace for a model sets the namespace for all models

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/data#3768] opened 2015-09-15 01:06 UTC
They should set per model, yeah?

    let host = this.get('host');
    let hostId = host.get('id');
    let hostType = host.get('type');
    let parentPath = Ember.String.underscore(hostType);
    parentPath = Ember.String.pluralize(parentPath);

    let adapter = this.store.adapterFor('packages');

    let rootNamespace = adapter.namespace; // api/
    let eventDiscountNamespace = rootNamespace + '/' + parentPath + '/' + hostId + '/packages';

    adapter.set('namespace', eventDiscountNamespace);

    console.log(adapter.namespace);  // api/events/16/packages
    console.log(this.store.adapterFor('packages').namespace); // api/events/16/packages

    this.store.adapterFor('application').namespace = rootNamespace

    console.log(adapter.namespace);  // api/
    console.log(this.store.adapterFor('packages').namespace); // api/

as you can see, setting the namespace for `packages` also sets for the `application` and then setting for the application sets the packages namespace.

I believe this could result in race conditions issues

**Comment by fivetanley** [comment] 2015-09-15 17:26
Can you post your adapter definitions?

**Comment by fivetanley** [comment] 2015-09-15 17:30
Actually I think this is pre-existing behavior. If you don't have a packages adapter defined, it will use the existing instance for the application adapter.

**Comment by NullVoxPopuli** [comment] 2015-09-15 17:34
oh, ok. so, if I manually define the adapter, then I shouldn't have the above matching console.logs.
I'll try that out tonight.

**Comment by NullVoxPopuli** [comment] 2015-09-15 21:58
just tried. same issue. :-(

both adapters have the same namespace. :-(

**Comment by pangratz** [comment] 2015-10-09 10:28
Looks like this works, see http://ember-twiddle.com/25804368a1d4ea121ed2

@NullVoxPopuli can you reproduce this in another Ember Twiddle or JSBin?

**Comment by NullVoxPopuli** [comment] 2015-10-09 13:39
I was using ActiveModelAdapter, I've recently switched to json-api, so I'll give this another go.

**Comment by bmac** [comment] 2015-10-12 14:41
@NullVoxPopuli did you get a chance test this issue again?

**Comment by NullVoxPopuli** [comment] 2015-10-12 14:42
not yet. been taking a small break from the project. I'll dive in to it again this week though.

**Comment by pangratz** [comment] 2016-02-29 22:49
@NullVoxPopuli did you have a chance to check if this is still valid?

**Comment by NullVoxPopuli** [comment] 2016-03-01 00:12
I actually migrated everything and have been re-architecting my backend to accomodate a flat-api as having relationship-related namespaces is too difficult.

**Comment by pangratz** [comment] 2016-03-01 10:23
Okay, seems good. I am going to close this issue as it couldn't be reproduced. If somebody stumbles upon this and can reproduce, please open a new issue and back-reference this one.

**Closed by pangratz** 2016-03-01 10:23 UTC
