### ISSUE TITLE
Fetching polymorphic records directly

### ISSUE THREAD

**Issue by jackmatt2** [emberjs/data#2749] opened 2015-02-02 21:43 UTC
[stackoverflow question](http://stackoverflow.com/questions/28270937/returning-polymorphic-payload-using-restserializer/28271033?noredirect=1#comment44914869_28271033)

It appears that ember-data does not allow direct fetching for polymorphic records without some sort of intermediary model.  In my case I have a typeahead search component that gets passed the modelClass to search for.

```javascript
this.store.fetch('animal') //all records are returned as animal objects
```

in the case above we need an intermediary.

```javascript
//zoo.js
export default DS.Model.extend({
    animals: DS.hasMany('animal', { polymorphic: true });
});
```

```javascript
this.store.fetch('zoo') //now records are parsed properly
```

I propose we need a way to force polymorphism in the payload without the intermediary.

```javascript
this.store.fetchPolymorphic('animal') //cat, dog will get created according to the type property in the json payload`
```

**Comment by dschmidt** [comment] 2015-02-02 21:52
How would you imagine the JSON payload for the RESTAdapter to look?

**Comment by jackmatt2** [comment] 2015-02-02 22:01
No change to what it is currently for normal polymorphic records:

```
{
  "animals": [
      {
      // ... other attributes
      "type": "dog" // attribute that tells ember data what kind of Animal to instantiate
      },
      {
      // ... other attributes 
      "type": "cat" // attribute that tells ember data what kind of Animal to instantiate
      },
      {
      // ... other attributes
      "type": "bird" // attribute that tells ember data what kind of Animal to instantiate
      },
  ]
}
```

**Comment by bmac** [comment] 2015-02-03 03:02
I believe json-api is planning on updating the spec to require the type key for a similar reasons.  See https://github.com/dgeb/json-api/tree/v1rc2.

**Comment by jackmatt2** [comment] 2015-02-03 11:44
@bmac The thing is, ember-data already currently supports the `type` property for polymorphic records, however, it requires that the polymorphic record be an attribute on an existing DS.Model with `{polymorphic:true}` which is of no use when you are simply fetching polymorphic record directly like I am that are not part of another model.

**Comment by wecc** [comment] 2015-02-04 20:33
Is this is dupe of #1766?

**Comment by jackmatt2** [comment] 2015-02-05 01:55
I have a workaround that does what I want but requires a custom DS.Store and a `type` parameter in the payload with the subclass name.  It would be good if this was part of ember-data.  I suppose it might be when jsonapi work out how to handle polymorphic records.  

```javascript
//app/store.js
import DS from 'ember-data';

export default DS.Store.extend({
    init: function() {
        console.log('Using custom store!');
        return this._super.apply(this, arguments);
    },

    /**
     * Polymorphic type support: http://vimeo.com/115987599 (7:21)
     */
    push : function(type, data, _partial) {
        var dataType, modelType, oldRecord, oldType;

        modelType = oldType = type;
        dataType = data.type;

        if(dataType && (this.modelFor(oldType) !== this.modelFor(dataType))) {
            modelType = dataType;

            if(oldRecord = this.getById(oldType, data.id)) {
                this.dematerializeRecord(oldRecord);
            }

        }

        return this._super(this.modelFor(modelType), data, _partial);

    }
});
```

**Comment by SimonKaluza** [comment] 2015-04-18 00:41
Nice work @jackmatt2, your workaround worked well for my use case too.

For future users, since the call to `dematerializeRecord` is deprecated in the latest version of Ember Data, note that replacing that line with `this.unloadRecord(oldRecord);` works just as well.

**Comment by igorT** [comment] 2015-04-18 00:52
This will soon be possible with #2991

**Comment by igorT** [comment] 2015-05-25 01:22
closing as a dupe of #1766

**Closed by igorT** 2015-05-25 01:22 UTC
Labels: Feature

**Comment by jackmatt2** [comment] 2015-06-18 11:17
@igorT I have just updated to 1.13.0 and my above code does not work.  You suggest that this is now possible.  It is just a matter of supplying a dasherized "type" key in the payload?

```json
{
   "animals": [{
    "name": "Roger",
    "type" : "dog"
  },{
    "name": "Moggie",
    "type" : "cat"
  }]
}
```
