### ISSUE TITLE
must use set to modify current state

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5922] opened 2019-03-20 06:20 UTC
ED 3.6.0
When calling store.push:

```
Uncaught Error: Assertion Failed: You must use set() to set the `currentState` property (of <DS.ManyArray:ember917>) to `<asset:tBVuV5sWAuO_dA>,<asset:MBwvP5ijatW0ZA>,<asset:WoK8mhwkiG1-Hg>,<asset:bVlib_k6W5InxQ>`.
    at assert (index.js:163)
    at Class.SETTER_FUNCTION [as currentState] (metal.js:953)
    at Class.flushCanonical (-private.js:2120)
    at Class.retrieveLatest (-private.js:2159)
    at InternalModel.notifyHasManyChange (-private.js:4099)
    at RecordDataWrapper._flushPendingManyArrayUpdates (-private.js:6981)
    at invoke (backburner.js:331)
    at Queue.flush (backburner.js:223)
    at DeferredActionQueues.flush (backburner.js:427)
    at Backburner._end (backburner.js:1003)
```

**Comment by runspired** [comment] 2019-03-21 01:12
@BryanCrotaz this suggests that other code you have has somehow reached in and begun observing the `currentState` on the internal has-many relationship state class.

**Comment by runspired** [comment] 2019-12-10 23:59
Closing this due to lack of reproduction.

**Closed by runspired** 2019-12-10 23:59 UTC
Labels: Needs Submitter Response
