### ISSUE TITLE
[1.13.6 Regression] RESTAdapter.findRecord does not accept a list of records anymore 

### ISSUE THREAD

**Issue by dschmidt** [emberjs/data#3587] opened 2015-07-26 18:43 UTC
Hey,

my server returns a list of records for findRecord requests, which used to work just fine up until 1.13.6. 

E.g.:
/artist/45
```javascript
{
  artists: { id: 45, name: 'Foobar' } 
}
```

triggers now
```
TypeError: Cannot read property '_internalModel' of undefined
```
here: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/finders.js#L32

For now I worked around it like this:
```javascript
   const pluralize = Ember.Inflector.inflector.pluralize.bind(Ember.Inflector.inflector);

   [...]

    findRecord(store, typeClass, id, internalModel, options) {
        return this._super(...arguments).then((response) => {
            const modelName = internalModel.modelName;
            if(!response[modelName] && response[pluralize(modelName)]) {
                response[modelName] = response[pluralize(modelName)][0];
                response[pluralize(modelName)].shift();
            }

            return response;
        });
    },
```

**Comment by fivetanley** [comment] 2015-07-27 18:07
It looks like @bmac released 1.13.7. Can you try with that? Thanks.

**Comment by bmac** [comment] 2015-07-27 18:17
fwiw I don't think 1.13.7 contains a fix for this bug.

**Comment by dschmidt** [comment] 2015-07-28 21:26
Right now I cant reproduce with neither 1.13.6 nor 1.13.7. It appears it's not triggered at all by calling findRecord on the store at all, but only with side-loading individual records - which I don't remember where I triggered this the last time in my app.

Maybe https://github.com/emberjs/data/pull/3554 this could have any effect on this?
Then I would be fine with closing this until I run into it again with 1.13.7 - or can anyone else reproduce?

**Comment by wecc** [comment] 2015-07-29 19:22
I don't think #3554 should impact this. Weird :confused: 

I'm closing this but will happily reopen if issue can be reproduced.

**Closed by wecc** 2015-07-29 19:22 UTC
