### ISSUE TITLE
Saving a record immediately after unloading a record with the same id fails

### ISSUE THREAD

**Issue by kaeufl** [emberjs/data#5125] opened 2017-08-14 13:47 UTC
Given a record in the store with type 'person' and id 'person-1', the following currently fails with ember data >= 2.13:

`store.peekRecord('person', 'person-1').unloadRecord();`
`store.createRecord('person').save();`

If the backend returns a payload that again contains the id 'person-1', the save operation fails with the error:
`You cannot update the id index of an InternalModel once set. Attempted to update person-1`

We run into this issue in an appplication where we can end up with a record being pushed to the store via a websocket push notification before the HTTP POST request initiated by the save operation has returned. We used to workaround this situation by unloading the record in the adapter's createRecord() hook before returning the payload to the store. This has worked until ember data 2.12. This issue thus currently keeps us from upgrading.

Potentially related issues: https://github.com/emberjs/data/issues/5041, https://github.com/emberjs/data/issues/4972, https://github.com/emberjs/data/issues/5006, https://github.com/emberjs/data/issues/4972

**Comment by buschtoens** [comment] 2017-08-15 09:14
Just as #4942 this issue is probably caused by #4821.

**Comment by stefanpenner** [comment] 2017-08-23 18:46
https://github.com/emberjs/data/issues/5125 is merged

**Closed** 2017-08-23 18:45 UTC

**Comment by dmtask** [comment] 2017-08-29 09:45
@stefanpenner When will the new release be released?
