### ISSUE TITLE
Ember not persisting belongsTo data

### ISSUE THREAD

**Issue by ssurana2** [emberjs/data#4635] opened 2016-11-09 16:25 UTC
I am encountering issues with `belongsTo` attribute not pushing the relationship data to server. Not sure whether I am doing something wrong or this is genuinely an issue.

I have the following Tags model:

```javascript
import DS from 'ember-data';
    
export default DS.Model.extend({
  label: DS.attr('string'),
  isRoot: DS.attr('boolean', {defaultValue: false}),
  parent: DS.belongsTo('tag') 
});
```

I have another service called `tag` with the following method:

```javascript
import Ember from 'ember';

export default Ember.Service.extend({
    
  parent: null,

  children: Ember.A(),

  //Some other code

  save: function(){
   this.get('parent').save().then(() => {
      this.get('children').map(tag => {
          return tag.save();
        });
      });
    }
  });
}
```

The logic here is that a user can enter multiple sub tags for a given root tag. And to save the sub tags and the root tags I am using a save method from tag service.

Now the problem here is that when I have say five subtags, say `one`, `two`, `three`, `four` and `five` and there is a root parent tag called `root`. Then when the save method is called from the tag service, then ideally the following data should be going to the servers.

```javascript
{data: {id: 1, type: 'tags', attributes: {label: "root", "is-root": true}, relationships: {parent: {data: null}}}}
{data: {id: 2, type: 'tags', attributes: {label: "one", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
{data: {id: 3, type: 'tags', attributes: {label: "two", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
{data: {id: 4, type: 'tags', attributes: {label: "three", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
{data: {id: 5, type: 'tags', attributes: {label: "four", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
{data: {id: 6, type: 'tags', attributes: {label: "five", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
```

but the actual data that is going to the server is

```javascript
{data: {id: 1, type: 'tags', attributes: {label: "root", "is-root": true}, relationships: {parent: {data: null}}}}
{data: {id: 2, type: 'tags', attributes: {label: "one", "is-root": false}, relationships: {parent: {data: null}}}}
{data: {id: 3, type: 'tags', attributes: {label: "two", "is-root": false}, relationships: {parent: {data: null}}}}
{data: {id: 4, type: 'tags', attributes: {label: "three", "is-root": false}, relationships: {parent: {data: null}}}}
{data: {id: 5, type: 'tags', attributes: {label: "four", "is-root": false}, relationships: {parent: {data: null}}}}
{data: {id: 6, type: 'tags', attributes: {label: "five", "is-root": false}, relationships: {parent: {data: {id: 1, type: "tags"}}}}}
```

Creating JSFiddle for this issue was not possible, so created the following repo https://github.com/ssurana2/tagManager.

Please follow the below steps to reproduce the issue
1. Clone the repo and run `ember s`.
2. After the page loads up click on 'tags' button to navigate to `localhost:4200/tags` page. 
3. Click on `tags1` labelled button and navigate to `localhost:4200/tags/1` page. 
4. Click on `Add` button 4 to 5 times and enter some text in the input fields. 
5. Click on update button and go back to the command line terminal
6. Only the last value has the relationships data
7. Expected is that the relationships data should be present for the newly created tags.

The stackoverflow question raised is http://stackoverflow.com/questions/40500824/ember-not-persisting-belongsto-data

**Comment by wecc** [comment] 2016-11-09 18:24
You should be able to add `{ inverse: null }` to the `parent` relationship, see [Explicit Inverses ](https://guides.emberjs.com/v2.9.0/models/relationships/#toc_explicit-inverses).

**Comment by wecc** [comment] 2016-11-09 18:28
I tried adding `{ inverse: null }` to your example app and that seem to work as expected.

I'm going to close this as it's not a bug with Ember Data – feel free to re-open if I'm mistaken!

**Closed by wecc** 2016-11-09 18:28 UTC

**Comment by ssurana2** [comment] 2016-11-10 07:37
@wecc this solved the issue. Thanks
