### ISSUE TITLE
ready() not ready

### ISSUE THREAD

**Issue by shaunc** [emberjs/data#3727] opened 2015-09-05 03:39 UTC
I'm using ember data 2.1.0-beta-1; I have a model:

    export default DS.Model.extend(NodeMixin, {
      name: DS.attr('string'),
      parent: DS.belongsTo('folder', {inverse: 'sheets', async: true}),
     ...
    });

The mixin defines:

    ready() {
      console.log('ready');
      return this.get('parent').then((p)=>{ console.log("parent", p); }
    }

When I define a model in route.model:

    return this.store.push( {type: 'sheet', id: 10, attributes: {
        name: 'Assets' }, 
      relationships: {
        parent: { data: { type: 'node/folder', id: daily.id }}
     ...

Then (trapping in route.afterModel) -- I see in console:

> ready
> parent null

...
ie ready is called before "parent" is set. However, "didUpdate" is not called with parent set either.

Interestingly enough, if I change "ready" to be:

    ready() {
      console.log('ready');
      return this.get('parent').then((p)=>{ 
        return this.get('parent').then((p)=>{console.log("parent", p); }
    }

I do see parent model for parent. (!)

**Comment by fivetanley** [comment] 2015-09-07 17:28
What happens if you call `this._super`?

**Comment by shaunc** [comment] 2015-09-07 17:59
Nope -- that doesn't do it either.

Currently, I use the following as a wrapper in all of the callbacks:

    // workaround for https://github.com/emberjs/data/issues/3727
    _getReady(cb) {
      // grumble ... workaround for getting relationship names :(
      let names = Ember.get(this.constructor, 'relationshipsByName')._keys.list  
      let relationships = this.getProperties.apply(this, names);
      return Ember.RSVP.hash(relationships).then(()=>cb());
    },

e.g. :

    ready() {
      let node = this.getNode(true);
      this._getReady(()=>{
        return this.syncToNode(node);
      //});
    },

Then anything called inside of "_getReady" wrapper will work as expected. It would be hard to put this code in super, unless super were to return a promise and it were used as `this._super().then(()=>{...});`
Better would be to put the setup in whatever calls the callbacks (IMHO).

**Comment by pangratz** [comment] 2015-10-10 19:05
Hey @shaunc, I have trouble reproducing your issue. Can you take a look at http://ember-twiddle.com/4ae18dd2c9db3eaeb166 and update the twiddle or check what is different to your situation?

**Comment by fivetanley** [comment] 2016-01-16 06:22
@pangratz it says that twiddle is private.

**Comment by pangratz** [comment] 2016-01-16 06:24
That's strange. I will look into that and report back...

**Comment by pangratz** [comment] 2016-01-18 20:07
I created a [new twiddle](https://ember-twiddle.com/bb034a6d04af5245d28a?openFiles=mixins.node.js%2Cmodels.folder.js). Somehow the original one got lost.

@shaunc I still have trouble reproducing. Can you take a look and check what is different for your case?

**Comment by shaunc** [comment] 2016-01-18 20:30
I'm deep in the middle of something else -- can check in a few days. At first glance -- try "async"...

**Comment by pangratz** [comment] 2016-01-18 20:37
I updated the twiddle to use `async: true` and also tried `async: false`. Looks like both variants work with `ready`...

**Comment by shaunc** [comment] 2016-01-18 20:44
Ok ... in my code I'm recursively building a tree from raw data, and using getProperties and then RSVP.hash to wait on a number of properties at once. And recursing by using "ready"... I've looked carefully at the code to make sure I didn't do something like forget to return a promise, but something like that could be the problem.

Thanks for looking into this! I don't have time right now to try to isolate/simplify but promise to give it a good look in a couple days (perhaps weds night, for instance, I should have a bit of time).

**Comment by pangratz** [comment] 2016-02-13 14:23
@shaunc kindly asking if you had any chance to look at this?

**Comment by pangratz** [comment] 2016-03-29 08:42
I am closing this as it couldn't be reproduced. @shaunc feel free to reopen if you still experience this issue!

**Closed by pangratz** 2016-03-29 08:42 UTC

**Comment by thermokarst** [comment] 2016-04-23 04:39
I just ran into the same problem that @shaunc detailed in his initial comment. I have a model that I was mixing in some behavior by using the `ready()` hook. Specifically I am caching some `belongsTo` data. When the model is instantiated using `this.store.findRecord('model', id)` things seem to work as expected --- the ids for the `belongsTo` relationships are there as expected, but when the model is instantiated by fetching it as part of a relationship the relationships are all null.

Throwing in a `.toJSON()` in the `ready()` hook reveals the following:
- `{side: false, contact: "230", ear_tag: "265", status: "1"}` for the `findRecord` instance
- `{side: false, contact: null, ear_tag: null, status: null}` for the `get` instance

Both instances have the `id` set correctly.

I can provide more detail if anyone is interested in discussing this further. For what it is worth, throwing in @shaunc's [fix](https://github.com/emberjs/data/issues/3727#issuecomment-138349963) seems to work just fine for me. I am running ED 2.5.2. Thanks!

**Comment by pangratz** [comment] 2016-04-23 05:44
Hey @thermokarst, would you be able to provide a ember-twiddle which demonstrates the issue you're having? This would help greatly to trace down the root of this problem. You can use [this one](https://ember-twiddle.com/6e506f341d78ff34c377c08618097862?numColumns=2&openFiles=mixins.node.js%2Capplication.route.js) as a starting point. Thanks!

**Comment by thermokarst** [comment] 2016-04-23 16:26
@pangratz: I whipped up a quick [twiddle](https://ember-twiddle.com/4d3ddda774cb648d3f52dda2e8e93676?numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs), [gist](https://gist.github.com/thermokarst/4d3ddda774cb648d3f52dda2e8e93676). In the process, I noticed a bit of a smoking gun: I initially set up my models using the default `JSONAPIAdapter`, but when I checked the console log (where I was debugging the `ready` hook), everything looked okay. Then I looked back at my project that prompted me to comment on this issue last night, and I noticed the adapter that I am using ([drf-adapter](https://github.com/dustinfarris/ember-django-adapter)) extends `RESTAdapter`. I refactored my example to use the `RESTAdapter`, but I still wasn't able to reproduce. Then I imported the `DRFAdapter` into my twiddle and voila: there was the problem. Specifically it has to do with [Hyperlinked Related Fields](http://dustinfarris.com/ember-django-adapter/hyperlinked-related-fields/). My guess is that it is unlikely that this is an ED problem, so I will also report these findings on the `DRFAdapter` repo. The most recent saved revision of that gist reproduces my errors exactly, in case someone feels like they need to look at it more closely.

Thanks for letting me ramble!

**Comment by pangratz** [comment] 2016-04-23 16:47
Thanks for the detailed example @thermokarst ❤️  Can you add some `console.log` statements to clarify in which parts of your application you would expect that some data of a specific value, but it isn't? I am not sure I fully understand the problem here yet 😔  Thanks!

**Comment by thermokarst** [comment] 2016-04-23 16:48
@pangratz: I want to revise my early statement. I took a closer look at the `DRFAdapter` code, and wanted to pin down what was happening. I decided to set up another [twiddle](https://ember-twiddle.com/18ae6b782e46d39917909a42f2d8cefa?openFiles=models.comment.js%2C) that uses the `links` attribute for a plain `JSONAPIAdapter` (which is what the DRF project leverages for hyperlinked fields). Looks like the same problem crops up as before: the related `hasMany` isn't completely loaded by the time the `ready` hook is called (see the console output for tagged "before"). Throwing in the related/promise boilerplate that @shaunc demoed sets up the related attributes (see the console output for tagged "after").

```
before 1 Object {message: "my favorite!", post: null, user: null}
after 1 Object {message: "my favorite!", post: "1", user: "1"}
```

Thanks so much for your help, I really appreciate it!

**Comment by thermokarst** [comment] 2016-04-23 16:57
@pangratz: Wow, I was writing my followup comment while you responded 🎉 ❤️, so sorry if it didn't quite answer what you were asking, I hadn't seen your response yet. I think the revised twiddle has a more clear set of console statements. Specifically, I would expect all of the attributes on the related comment to be available when the `ready` hook on the comment model hits. Those attributes are ready if the relationship is conveyed via the data attribute in the API response, but isn't when using the links attribute. I am also available on ember slack (as @thermokarst) if you would like to discuss there as well. Thanks!!

**Comment by thermokarst** [comment] 2016-06-07 22:46
@pangratz: pinging to see if there is anything I can do for this. Thanks!
