### ISSUE TITLE
Can not create model with "container" attribute 

### ISSUE THREAD

**Issue by petey** [emberjs/data#4511] opened 2016-08-24 18:24 UTC
The following simple model fails tests in ember/ember-data 2.7.0
```
import DS from 'ember-data';

export default DS.Model.extend({
  container: DS.attr('string'),
});
```

```
not ok 17 PhantomJS 2.1 - Unit | Model | build: it exists
    ---
        actual: >
            null
        stack: >
            get@http://localhost:7357/assets/vendor.js:69887:26
            giveDescriptorSuper@http://localhost:7357/assets/vendor.js:32444:30
            addNormalizedProperty@http://localhost:7357/assets/vendor.js:32557:36
            mergeMixins@http://localhost:7357/assets/vendor.js:32606:32
            mergeMixins@http://localhost:7357/assets/vendor.js:32614:20
            applyMixin@http://localhost:7357/assets/vendor.js:32715:16
            applyPartial@http://localhost:7357/assets/vendor.js:32941:22
            proto@http://localhost:7357/assets/vendor.js:48250:42
            validatePropertyInjections@http://localhost:7357/assets/vendor.js:43616:30
            injectedPropertyAssertion@http://localhost:7357/assets/vendor.js:48654:110
            factoryFor@http://localhost:7357/assets/vendor.js:11537:26
            lookupFactory@http://localhost:7357/assets/vendor.js:11395:24
            factory@http://localhost:7357/assets/test-support.js:8349:39
            http://localhost:7357/assets/test-support.js:8437:75
            http://localhost:7357/assets/tests.js:305:29
            runTest@http://localhost:7357/assets/test-support.js:2991:32
            run@http://localhost:7357/assets/test-support.js:2976:11
            http://localhost:7357/assets/test-support.js:3139:14
            process@http://localhost:7357/assets/test-support.js:2815:24
            begin@http://localhost:7357/assets/test-support.js:2797:9
            http://localhost:7357/assets/test-support.js:3567:9
        message: >
            Died on test #1 http://localhost:7357/assets/tests.js:304:24
            exports@http://localhost:7357/assets/vendor.js:131:37
            requireModule@http://localhost:7357/assets/vendor.js:30:25
            require@http://localhost:7357/assets/test-support.js:7044:14
            loadModules@http://localhost:7357/assets/test-support.js:7036:21
            load@http://localhost:7357/assets/test-support.js:7066:33
            http://localhost:7357/assets/test-support.js:6949:22: null is not an object (evaluating 'this.store.container')
        Log: |
            { type: 'warn',
              text: '\'DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container]\\n    http://localhost:7357/assets/vendor.js:16783:15\\n    raiseOnDeprecation@http://localhost:7357/assets/vendor.js:16706:17\\n    http://localhost:7357/assets/vendor.js:16783:15\\n    invoke@http://localhost:7357/assets/vendor.js:16799:21\\n    deprecate@http://localhost:7357/assets/vendor.js:16767:37\\n    deprecate@http://localhost:7357/assets/vendor.js:29639:42\\n    deprecate@http://localhost:7357/assets/vendor.js:66605:45\\n    get@http://localhost:7357/assets/vendor.js:69885:46\\n    giveDescriptorSuper@http://localhost:7357/assets/vendor.js:32444:30\\n    addNormalizedProperty@http://localhost:7357/assets/vendor.js:32557:36\\n    mergeMixins@http://localhost:7357/assets/vendor.js:32606:32\\n    mergeMixins@http://localhost:7357/assets/vendor.js:32614:20\\n    applyMixin@http://localhost:7357/assets/vendor.js:32715:16\\n    applyPartial@http://localhost:7357/assets/vendor.js:32941:22\\n    proto@http://localhost:7357/assets/vendor.js:48250:42\\n    validatePropertyInjections@http://localhost:7357/assets/vendor.js:43616:30\\n    injectedPropertyAssertion@http://localhost:7357/assets/vendor.js:48654:110\\n    factoryFor@http://localhost:7357/assets/vendor.js:11537:26\\n    lookupFactory@http://localhost:7357/assets/vendor.js:11395:24\\n    factory@http://localhost:7357/assets/test-support.js:8349:39\\n    http://localhost:7357/assets/test-support.js:8437:75\\n    http://localhost:7357/assets/tests.js:305:29\\n    runTest@http://localhost:7357/assets/test-support.js:2991:32\\n    run@http://localhost:7357/assets/test-support.js:2976:11\\n    http://localhost:7357/assets/test-support.js:3139:14\\n    process@http://localhost:7357/assets/test-support.js:2815:24\\n    begin@http://localhost:7357/assets/test-support.js:2797:9\\n    http://localhost:7357/assets/test-support.js:3567:9\'\n' }
    ...
```

**Comment by bmac** [comment] 2016-08-25 12:33
Unfortunately, this is a limitation of how dependency injection works with Ember Data. This issue should be fixed when Ember 3.0 is released and the deprecation for the `container` property is removed but until then its unlikely to be fixed because it would be a backwards incompatible change.

**Comment by petey** [comment] 2016-08-25 17:32
Yeah, I understand it is too late to turn the ship around. Are there other keys that are unavailable due to issues like this? Are these documented anywhere? 
In ember-data 3.x is all dependency injection going to go into private or namespaced properties so they do not interfere with user-defined ones?

**Comment by fivetanley** [comment] 2016-09-12 02:03
@petey All the Ember Data ones are documented on [DS.Model](http://emberjs.com/api/data/classes/DS.Model.html) . It is difficult to document them because they are all the public properties and methods on a DS.Model could also be an attribute if you choose to override with that.

This `container` one is an implementation detail of Ember, not Ember Data.

**Comment by fivetanley** [comment] 2016-09-12 02:03
> In ember-data 3.x is all dependency injection going to go into private or namespaced properties so they do not interfere with user-defined ones?

**Comment by fivetanley** [comment] 2016-09-12 02:09
> In ember-data 3.x is all dependency injection going to go into private or namespaced properties so they do not interfere with user-defined ones?

It's possible we could let users opt into this by adding an `attributes` namespace to all `attr`, but we probably wouldn't remove the collision aspect of it because it would just be too difficult for most apps to upgrade.

**Comment by wecc** [comment] 2016-10-20 21:56
Closing this as it's not a bug

**Closed by wecc** 2016-10-20 21:56 UTC
