### ISSUE TITLE
Obscure error message when upgrading to 4.7.1

### ISSUE THREAD

**Issue by kpfefferle** [emberjs/data#8173] opened 2022-09-08 14:20 UTC
### Description

When attempting to upgrade to 4.7.1, we have a couple of tests failing with the following error:

```
Error: Assertion Failed: You attempted to update `ref` on `Tag`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.
```

The items being referenced don't exist in our app code, so we're not sure what exactly we might be doing to trigger this error. Would you have any ideas what might have changed that we're now infringing on @runspired?

### Versions

```cli
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@4.7.0
✨  Done in 0.44s.
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@4.6.0
✨  Done in 0.43s.
yarn list v1.22.19
├─ @ember-data/adapter@4.7.1
├─ @ember-data/canary-features@4.7.1
├─ @ember-data/debug@4.7.1
├─ @ember-data/model@4.7.1
├─ @ember-data/private-build-infra@4.7.1
├─ @ember-data/record-data@4.7.1
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@4.7.1
├─ @ember-data/store@4.7.1
├─ @types/ember-data__adapter@4.0.0
├─ @types/ember-data__model@4.0.0
├─ @types/ember-data__serializer@4.0.0
├─ @types/ember-data__store@4.0.0
├─ @types/ember-data@4.4.1
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@4.7.1
✨  Done in 0.43s.
```

**Comment by alexraputa** [comment] 2022-09-08 15:40
@kpfefferle Are you using `createRecord` in a native getter with the `@cached` decorator?

```js
@cached
get record() {
  return this.store.createRecord('record');
}
```

Maybe some code like that caused the error.

**Comment by runspired** [comment] 2022-09-08 15:43
I’m seeing this in an app at work and haven’t tracked it down yet. Tag is basically isValid/isError etc flags where ref is the tracked property on it (we create individual companion props for each of these to deal with various requirements of both the computed world and the tracked world)

**Comment by runspired** [comment] 2022-09-08 15:45
Incidentally this is why the internals of EmberData don’t use tracked properties, it would pretty much be impossible for us to avoid these sorts of errors if we did 😅

My best guess is that something around property creation/access has started generating a change notification that dirties itself during mutation.

**Comment by kpfefferle** [comment] 2022-09-08 15:52
@alexraputa We're not doing that exactly, but the constructor in the "offending" Component does use `createRecord` to initialize a new data model that is internal to the Component. Something like this:

```ts
import Component from '@glimmer/component';
import { service } from '@ember/service';
import StoreService from '@ember-data/store';
import ComponentModel from 'my-app/models/component-model';

interface MyComponentArgs {
  // ...
}

interface MyComponentSignature {
  Args: MyComponentArgs;
}

export default class MyComponent extends Component<MyComponentSignature> {
  @service declare store: StoreService;

  @tracked declare newModel: Partial<ComponentModel>;

  constructor(owner: unknown, args: MyComponentArgs) {
    super(owner, args);
    this.createNewModel();
  }

  createNewModel() {
    this.newModel = this.store.createRecord('component-model', {
      // set some attrs on the new model...
    });
  }
}
```

Is this method of creating a new model within a Component no longer supported? Or is this a bug? 🤔

**Comment by runspired** [comment] 2022-09-08 15:53
Most definitely this error is a bug.

**Comment by runspired** [comment] 2022-10-14 07:06
was hoping to fix this in the next 4.7 patch but I don't have a good test for it. I have some suspicions around what might be triggering it (some of which are sadly unfixable as they are limitations of how tracking works in Ember unless Ember were to directly expose `untracked` used by `computed` as a primitive for us to build with). I'll see if I can find one of the failures in our app and use it to create a failing test.

**Comment by runspired** [comment] 2022-10-14 08:39
Most of the instances of this in our app are around arrays, not createRecord specifically (though it sometimes may be a createRecord where a peekAll is also in use). @kpfefferle @alexraputa does that align with your experience?

**Comment by kpfefferle** [comment] 2022-10-14 17:27
@runspired Ours is not a `createRecord` with `peekAll`, but it is a `createRecord` that is associating the new model with an existing model that has been passed into the component via `this.args`. If I remove the relationship from `createRecord`, I do not get the error. I've updated [the above code sample](https://github.com/emberjs/data/issues/8173#issuecomment-1240906122) to reflect this aspect of our failure case.

**Comment by kpfefferle** [comment] 2022-10-14 17:51
@runspired I can understand how a component associating a new record with an existing one could reasonably be understood as mutating the related component in a way that invalidates it in a wider context (and in this case, as an argument to the component itself). However, the use case seems to be a common one: the user has clicked a button that opens a form to create a new model related to a given existing model.

Do you have a suggestion for how ember-data users should accomplish this goal without triggering this error? Should we preemptively create the new model in the route (even if the user may never click on the button to open the form)?

**Comment by runspired** [comment] 2022-10-14 17:54
@kpfefferle I typically create it as part of the click action to open the modal, or if I prefer to buffer I create it on the click action to submit the modal. In both of these cases you will avoid any backtracking.

**Comment by kpfefferle** [comment] 2022-10-14 17:56
@runspired We literally only have one component in our application that's doing this, so I'll give those approaches a shot to get us back on the latest stable train 👍

**Comment by runspired** [comment] 2022-10-14 17:57
All this said I am poking at this to see if there's something simple I can do. I don't want to go back to two pass, but maybe I can defer the relationship and record-array notifications with a deprecation that you resolve via a special flag (since we can't possibly detect this ourselves). Along the lines of the sync=>async observer switch over.

**Comment by alexraputa** [comment] 2022-10-14 19:09
@runspired, this code also cause the deprecation:

```js
import { inject as service } from '@ember/service';
import Component from '@glimmer/component';

export default class Checkout extends Component {
  @service store;

  order;

  constructor(owner, args) {
    super(owner, args);

    this.order = this.findOrder();
  }

  findOrder() {
    let order;
    const orders = this.store.peekAll('order');

    if (orders.length !== 0) {
      order = orders.find((found) => found.isNew);
    }

    return order ?? this.store.createRecord('order');
  }
}
```

**Comment by runspired** [comment] 2022-10-14 19:15
Yeah. That's where folks using the resource pattern are regularly adding await Promise.resolve() to sever the notifications from the tracking context. It's frustrating because it's clearly not an error here but it also is. "Untracked" would be a good thing here. I pinged @wycats for some general thoughts. I'm increasingly finding way too many of these footguns with tracked as old convert more code out of computeds.

**Comment by runspired** [comment] 2022-10-14 19:32
One thought, the actual primitive needed here is a tracking transaction. While `untracked` would work for the case above, you might find yourself in a similar situation in which you need to read-before-modify but still want to subscribe. This is in fact exactly the case for resources where I'm seeing folks bash their heads against the wall, and it's something where I've had to repeatedly write complicated work-arounds for code very similar to `findOrder` in the example above.

An example where folks are regularly hitting failures are things like `query`, where you end up with a length subscription when `store.query` is called that mutates when the request resolves re-triggering the initial code which is now unnecessarily subscribed.

Since EmberData has fairly good control of its tracking updates, I could probably create such a transaction primitive specific to ours to silently dirty props and only notify `ref` after a transaction. That said, it would be better if this was built into `@glimmer/tracking`.

A rough API for this might be

```ts
import { transact } from '@ember-data/tracking';


function findOrder(store) {
    return transact(() => {
      let order;
      const orders = store.peekAll('order');
  
      if (orders.length !== 0) {
        order = orders.find((found) => found.isNew);
      }
  
      return order ?? this.store.createRecord('order');
    });
}
```

Though a memoized version might be nicer:

```ts
import { memoTransact } from '@ember-data/tracking';

const findOrder = memoTransact((store) => {
   let order;
    const orders = store.peekAll('order');

    if (orders.length !== 0) {
      order = orders.find((found) => found.isNew);
    }

    return order ?? this.store.createRecord('order');
})

```

**Comment by runspired** [comment] 2022-10-14 19:34
I'm also curious if @developit has given any thought to these sorts of issues for Signals.

**Comment by alexraputa** [comment] 2022-10-14 19:50
> transaction primitive

It would be nice to have API like that.

> That said, it would be better if this was built into @glimmer/tracking.

@wycats, maybe @starbeamjs have the similar API?

**Comment by runspired** [comment] 2022-10-14 22:06
Impl for data: https://github.com/emberjs/data/pull/8214/commits/c1e058c92f637fbe4b170764ab0e73d86f714e15#diff-e007ce9be17cc346c9a985014647c88c62a07f706d18a74eb813de2cd9b813c7

**Comment by runspired** [comment] 2022-10-15 00:26
@alexraputa @kpfefferle I have a spike of transact working in this PR: #8214 

The public API for it will be exactly as I showed above, and I'm shipping it with typescript support 🎉

**Comment by runspired** [comment] 2022-11-11 22:51
Closing as tracking lib has shipped

**Closed by runspired** 2022-11-11 22:51 UTC
Labels: Bug

**Comment by bartocc** [comment] 2023-04-14 11:08
I hit this bug when migrating to ember-data@4.7 as well.

I believe our use case is slightly different than what has been previously
described in this issue, but we do hit the bug because we use store.peekAll and
store.createRecord.

In `RouteA`, we render `ComponentA`
When rendered, `ComponentA` calls `store.peekAll("model-a")`

We then transition to `RouteB`, which renders `ComponentB`, but not `ComponentA`.
`RouteB` is not nested under `RouteA`.
When rendered, `ComponentB` (a form) calls `store.createRecord("model-a")`.
And we hit the bug.

I've worked around this regression by buffering the creation of "model-a" in `ComponentB` with a proxy.
`store.createRecord("model-a")` is now only called when submitting the form.
This is what @runspired suggested in https://github.com/emberjs/data/issues/8173#issuecomment-1279301545

I also tried to import `untracked` from `@ember-data/tracking`, and wrap the
call to `store.peekAll("model-a")` in `ComponentA` with it, but this did not fix the
regression.

I should add that our app uses an in-repo-addon and that `ComponentA` and `ComponentB` are part of this addon.

@runspired, do you believe our use case is not supported by @ember-data/tracking?

**Comment by runspired** [comment] 2023-04-14 22:35
> We then transition to RouteB, which renders ComponentB, but not ComponentA.
RouteB is not nested under RouteA.

the way ember/glimmer works, this should not result in this issue if this is in fact true, which suggests to me that this is not true or some other thing also consumes the state.

I don't know that I'd use a proxy to bugger the creation, but I wouldn't call `createRecord` via a component constructor ever, as that doesn't really make sense. You want to change state on user action or during navigation, not during render.

**Comment by bartocc** [comment] 2023-04-17 15:46
> > We then transition to RouteB, which renders ComponentB, but not ComponentA.
> > RouteB is not nested under RouteA.
> 
> the way ember/glimmer works, this should not result in this issue if this is in fact true, which suggests to me that this is not true or some other thing also consumes the state.

I agree, this is strange!

But when we directly access `RouteB` via its URL, we do not hit the bug…
which suggests we do not consume the state in the template rendered with `RouteB`

I am out of ideas here 😊

> I don't know that I'd use a proxy to buffer the creation, but I wouldn't call createRecord via a component constructor ever, as that doesn't really make sense. You want to change state on user action or during navigation, not during render.

How would you buffer the creation then? I'd like to add you idea of the implementation to my choices. Thx 🙏
