### ISSUE TITLE
hasRecordForId returns true when model is not loaded

### ISSUE THREAD

**Issue by jordpo** [emberjs/data#2799] opened 2015-02-18 17:16 UTC
if the id is already loaded in the store through an Ember Data relationship, this method tries to reload the model even though its actually not fully loaded in the store. 

https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/store.js#L802

I opened a pr that I think patches this:
https://github.com/emberjs/data/pull/2798

**Comment by sly7-7** [comment] 2015-02-19 07:13
Closing as duplicate of #2659

**Closed by sly7-7** 2015-02-19 07:13 UTC
