### ISSUE TITLE
`type` attribute breaks things

### ISSUE THREAD

**Issue by amk221** [emberjs/data#3731] opened 2015-09-08 11:43 UTC
Prior to Ember Data 2 (i.e. 2.0.0-beta.2) this simple example worked:

jsfiddle: http://jsfiddle.net/amk221/aocdzyct/
example cli project: [https://github.com/amk221/-ember-data-type-issue](https://github.com/amk221/-ember-data-type-issue#ember-data-type-issue)

It's something to do with a model having an attribute called `type`, which also happens to be the name of an existing model.

**Comment by wecc** [comment] 2015-09-08 20:19
Closing as a duplicate of #3702

**Closed by wecc** 2015-09-08 20:19 UTC
