### ISSUE TITLE
Serializer issue with embedded relationships.

### ISSUE THREAD

**Issue by jcbvm** [emberjs/data#3424] opened 2015-06-23 10:09 UTC
Got a lot of `you must include an 'id' for some-model in an object passed to 'push'` errors since I upgraded to 1.13.4. Tracked it down and it seems to come from my embedded relationships. When I do not define a custom serializer for the embedded relationship, above error is thrown. When I do create a custom serializer (just an empty RESTSerializer), above error disappears.

**Comment by wecc** [comment] 2015-06-23 11:28
Thanks for reporting! Would you be able to reproduce the error in a JSBin?

**Comment by jcbvm** [comment] 2015-06-23 11:33
Will try to later this afternoon.

**Comment by wecc** [comment] 2015-06-23 11:39
Here's a pre-configured JSBin using Ember 1.13.2 and Ember Data 1.13.4 without any deprecation warnings you can use: http://emberjs.jsbin.com/zotuta/edit?html,js,output

**Comment by jcbvm** [comment] 2015-06-23 12:59
Here's a JSBin reproducing the error http://emberjs.jsbin.com/kubupaluma/edit?html,js,output

**Comment by wecc** [comment] 2015-06-23 13:13
Thanks @jcbvm! This seem to be a bug where your `serializer:book` extracts it's embedded `author` and looks up the `serializer:author` to normalize the author's data. Since you have defined `serializer:book` it is _not_ using the new Serializer API but `serializer:author` is looked up and automatically opted in to the new Serializer API... so two serializers are working together on two different APIs.

I'm not sure how to solve this but it should be fixed.

Until then you can either have your `serializer:book` opt into the new Serializer API by setting `isNewSerializerAPI: true` or just define `serializer:author` to make sure it too uses the old Serializer API.

**Comment by jcbvm** [comment] 2015-06-23 13:24
Thanks for looking into, makes some sense now. Currently I'm working around this by defining an empty serializer, so using the old API.

**Comment by igorT** [comment] 2015-06-27 22:40
@wecc this is actually tricky, we should think if there is a way to make sure you always use new or old serializer throughout the request

**Comment by wecc** [comment] 2015-06-28 00:19
@igorT there's an assert in RESTSerializer that doesn't solve this particular problem, but might at least give some information about what's happening, see https://github.com/emberjs/data/blob/release/packages/ember-data/lib/serializers/rest-serializer.js#L218

We could implement this assert in multiple places (where we do `serializerFor` within serializers, practically)

**Comment by bmac** [comment] 2015-06-29 13:11
> We could implement this assert in multiple places (where we do serializerFor within serializers, practically)

I think this sounds like a great idea.

**Comment by wecc** [comment] 2015-07-07 23:54
Closing since #3511 has been merged.

**Closed by wecc** 2015-07-07 23:54 UTC
