### ISSUE TITLE
Cannot use the decorators and decorators-legacy plugin together

### ISSUE THREAD

**Issue by KHMtravel** [emberjs/data#5942] opened 2019-03-28 15:12 UTC
I have an ember project running in a docker container.
It started yesterday when I rebuilt the container I received the following error:

> Cannot use the decorators and decorators-legacy plugin together

I did not add any new plugins to package.json.
This is the output of yarn list [https://pastebin.com/ds3ET03F](https://pastebin.com/ds3ET03F) and this of yarn why ember-cli-babel [https://pastebin.com/5Zciiqag](https://pastebin.com/5Zciiqag).

I'm not sure what is causing this error. It seems that some dependencies changed their ember-cli-babel dependency. Especially the 
Maybe someone can point me into the right direction.

**Comment by alejandrodevs** [comment] 2019-03-28 19:16
I'm having the same issue in travis without any change.

**Comment by dcyriller** [comment] 2019-03-28 21:32
Do you happen to have a repo that would be public (to have a reproduction)?

@alejandrodevs is your issue with ember-{source,data,cli}@3.7 as well?

**Comment by alejandrodevs** [comment] 2019-03-28 21:56
I was using ember cli 3.7.1 after I upgraded to 3.8.1 the problem was fixed.

**Comment by KHMtravel** [comment] 2019-03-29 10:12
Upgrading to ember-cli 3.8.1 solved the issue for me, too.
Thank you!

Unfortunately the repo I'm working on is not public.

**Comment by KHMtravel** [comment] 2019-03-29 10:31
It seems like the update to 3.8.1 was not the actual reason the pipeline doesnt fail anymore.
Now other branches with 3.7.1 also dont get the error anymore.
Probably some dependency changed again.

**Comment by runspired** [comment] 2019-03-30 23:46
Closing as this seems resolved. :)

**Closed by runspired** 2019-03-30 23:46 UTC
