### ISSUE TITLE
Setting a `hasMany` relationship object back to itself clears all relationships

### ISSUE THREAD

**Issue by pswai** [emberjs/data#5109] opened 2017-07-31 02:15 UTC
[Twiddle](https://ember-twiddle.com/0426217e1ba4b8094b11aa0b4992ceca?openFiles=controllers.application.js%2C)

I don't know how to search for this issue, so sorry if there is already an existing one.

Basically if we get a relationship object and set the exact object back, it relationships become empty

**Comment by sly7-7** [comment] 2017-07-31 07:00
I wonder why you don't get this assert: https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/has-many.js#L150. If you pass relationship.toArray(), then it works.

**Comment by pswai** [comment] 2017-08-01 02:21
@sly7-7 Now looking at the line you pointed out, I'm curious too. As you can see in the twiddle it's not triggering.

**Comment by sly7-7** [comment] 2017-08-01 07:03
I think in twiddle, this is a production build, so I guess asserts are stripped.

**Comment by pangratz** [comment] 2017-10-06 21:22
I am closing as this is not a bug.

As @sly7-7 correctly points out, using the development build an assertion would be thrown.

**Closed by pangratz** 2017-10-06 21:22 UTC
