### ISSUE TITLE
queryRecord throws when the response is empty

### ISSUE THREAD

**Issue by XrXr** [emberjs/data#3890] opened 2015-10-26 19:30 UTC
http://emberjs.jsbin.com/fekufi/1/edit?js,console

> Error: Assertion Failed: You must include an 'id' for undefined in an object passed to 'push'

If the payload for `authors` is changed to `null`, the same error happens. 

This use to just resolve with `undefined` in ED 1.3.x, so I assumed it's a convenience feature.

I asked about this on Slack, the consensus seems to be that the promise should reject like a 404.

**Comment by XrXr** [comment] 2015-10-26 19:41
Here is a bin for JSONAPIAdapter

http://emberjs.jsbin.com/fekufi/edit?js,console

> SyntaxError: Unexpected end of input
    at Object.parse (native)
    at x.extend.parseJSON

**Comment by sescobb27** [comment] 2015-10-31 14:40
@XrXr http://jsonapi.org/format/#fetching in JSONAPI payload can't be empty. you SHOULD return
```
{
  "data": []
}
```
or
```
{
  "data": null
}
```

**Comment by jherdman** [comment] 2015-10-31 14:42
I ran into this too. The JSON payload _isn't_ empty though. Here's another contrived example: http://emberjs.jsbin.com/sikivanomi/edit?html,js,output. Simply put, my query found nothing on the back end. This was a valid response in ED 1.13, I don't see why my API response wouldn't be valid now.

**Comment by sescobb27** [comment] 2015-10-31 14:43
This works as expected
```js
// Returns books embedded in authors
$.mockjax({
  type: 'GET',
  url: '/authors',
  status: '204',
  dataType: 'json',
  responseText: '{"data": []}'
});
```

**Comment by jherdman** [comment] 2015-10-31 14:45
I think the issue is more accurately stated as "`queryRecord` shits the bed with REST Adapter when empty response returned"

**Comment by sescobb27** [comment] 2015-10-31 14:45
@jherdman I think is because you are querying just a record, but you are returning an array (an empty one)

**Comment by jherdman** [comment] 2015-10-31 14:48
Indeed, but that's how this jazz works. Peep this:

https://github.com/emberjs/data/blob/31bf0715734e3573a4a7bfe54d833aa07db38d9f/packages/ember-data/lib/serializers/rest-serializer.js#L305-L327

This is the meat and potatoes of how the REST Adapter goes about figuring out which record to pluck out of a response when you're querying for a record. Indeed the adapter is expecting an array response. The trick seems to be further down in the stack. After this your normalized response look like this: `{ data: null, included: [] }`. The `data: null` bit causes all sorts of barfage and sadness.

**Comment by sescobb27** [comment] 2015-10-31 15:00
but that's because REST adapter serialize plain JSON payload into JSON API compliant payload in order to ED load it into the store

**Comment by wecc** [comment] 2015-10-31 15:51
Seems related to #3790

**Comment by pangratz** [comment] 2016-05-16 09:19
I am going to close this issue as the behavior of `queryRecord` has been overhauled in #4300. Please see that PR for more context but basically returning `{ data: null }` or `{ data: [] }` for a `queryRecord` using the `rest` adapter/serializer now resolves the promise with `null`.

Please note that returning an array for the primary data of a `queryRecord` is deprecated, as this method should only be used for use cases where a single record is returned. In all other cases `query` should be used instead.

**Closed by pangratz** 2016-05-16 09:19 UTC
