### ISSUE TITLE
relationships and background reloading 

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/data#4679] opened 2016-11-23 18:51 UTC
I'm finding that relationships aren't background reloading, and I'm not sure if this is intended or not.

I was able to replicate in the Ember JSBin. Here is the exported gist that shows this issue: https://gist.github.com/anonymous/e39efd513cafff3ef84726660d3d2bbd

Say I have `/authors` and it returns:

```js
{
  data: [{
    id: 1, type: 'authors', 
    attributes: { name: "Mark Twain" }
  }, { 
    id: 2, type: 'authors', 
    attributes: { name: "Ernest Hemingway" }
  }, {
    id: 3, type: 'authors', 
    attributes: { name: "Stephen King" }
  }]
}
```

And `/authors/1` returns:

```js
{
  data: {
    id: 1, type: 'authors', 
    attributes: { name: "Mark Twain" },
    relationships: {
      books: {
        links: {
          related: '/authors/1/books'
        }
      }
    }
  }
}
```

Now say you call `findAll()` and then call `findRecord()`. The data returned from `findRecord()` has the `relationships` key but this isn't in the resource collection. In this scenario, if you try and get the async relationship `books`, it won't use the relationship links to fetch it. No request will be made. For example:

```js
var store = this.get('store');
return store.findAll('author').then(function(authors) {
  return store.findRecord('author', 1).then(function(author) {
    return author.get('books').then(function() {
      // a request to /authors/1/books won't be made
    });
  });
});
```

However, if you don't call `findAll()`, the relationship links will be used. It seems like relationship links for a resource will only be used if the resource was pushed into the store with them.

The quick fix I found was to have `shouldReloadRecord()` in the adapter return `true`. 

Is this the intended behavior or is it a bug? If it is a bug, I'd be happy to look into it and make a fix! Thank you!

**Comment by wecc** [comment] 2016-11-23 18:57
I'd say this is by design but somewhat of a gotcha.

In your example you call `findAll('author')` and then `findRecord('author', 1)` right after that. Since the author with ID 1 is already in the store when you do the `findRecord('author', 1)` call it will resolve immediately... so when you do `author.get('books')` Ember Data knows nothing about the relationship (because the background fetch to `/authors/1` hasn't resolved yet.

I'd expect this should go away if you did `store.findRecord('author', 1, { reload: true })` which prevents it from resolving until the request to `/authors/1` has finished.

**Comment by skaterdav85** [comment] 2016-11-23 19:04
ah! That makes sense! Yes, `store.findRecord('author', 1, { reload: true })` does the trick. You're right, this seems more like a gotcha and in line with how background reloading works instead of a bug. I can close this issue if you agree. Thanks so much!!

**Comment by wecc** [comment] 2016-11-23 19:12
Happy to help!

**Closed by wecc** 2016-11-23 19:12 UTC
Labels: Needs Bug Verification
